# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter/filter_dock_base.ui'
#
# Created: Tue Mar  3 12:10:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FilterDock(object):
    def setupUi(self, FilterDock):
        FilterDock.setObjectName(_fromUtf8("FilterDock"))
        FilterDock.resize(328, 296)
        self.FilterDockContents = QtGui.QWidget()
        self.FilterDockContents.setObjectName(_fromUtf8("FilterDockContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.FilterDockContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadDataButton = QtGui.QPushButton(self.FilterDockContents)
        self.loadDataButton.setObjectName(_fromUtf8("loadDataButton"))
        self.horizontalLayout.addWidget(self.loadDataButton)
        self.zoomButton = QtGui.QPushButton(self.FilterDockContents)
        self.zoomButton.setObjectName(_fromUtf8("zoomButton"))
        self.horizontalLayout.addWidget(self.zoomButton)
        self.buildFilterButton = QtGui.QPushButton(self.FilterDockContents)
        self.buildFilterButton.setObjectName(_fromUtf8("buildFilterButton"))
        self.horizontalLayout.addWidget(self.buildFilterButton)
        self.clearFilterButton = QtGui.QPushButton(self.FilterDockContents)
        self.clearFilterButton.setObjectName(_fromUtf8("clearFilterButton"))
        self.horizontalLayout.addWidget(self.clearFilterButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.subGroupFilterLabel = QtGui.QLabel(self.FilterDockContents)
        self.subGroupFilterLabel.setObjectName(_fromUtf8("subGroupFilterLabel"))
        self.gridLayout.addWidget(self.subGroupFilterLabel, 1, 0, 1, 1)
        self.groupFilterCombo = QtGui.QComboBox(self.FilterDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupFilterCombo.sizePolicy().hasHeightForWidth())
        self.groupFilterCombo.setSizePolicy(sizePolicy)
        self.groupFilterCombo.setEditable(True)
        self.groupFilterCombo.setObjectName(_fromUtf8("groupFilterCombo"))
        self.gridLayout.addWidget(self.groupFilterCombo, 2, 1, 1, 1)
        self.groupFilterButton = QtGui.QPushButton(self.FilterDockContents)
        self.groupFilterButton.setObjectName(_fromUtf8("groupFilterButton"))
        self.gridLayout.addWidget(self.groupFilterButton, 2, 2, 1, 1)
        self.contextFilterCombo = QtGui.QComboBox(self.FilterDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextFilterCombo.sizePolicy().hasHeightForWidth())
        self.contextFilterCombo.setSizePolicy(sizePolicy)
        self.contextFilterCombo.setEditable(True)
        self.contextFilterCombo.setObjectName(_fromUtf8("contextFilterCombo"))
        self.gridLayout.addWidget(self.contextFilterCombo, 0, 1, 1, 1)
        self.groupFilterLabel = QtGui.QLabel(self.FilterDockContents)
        self.groupFilterLabel.setObjectName(_fromUtf8("groupFilterLabel"))
        self.gridLayout.addWidget(self.groupFilterLabel, 2, 0, 1, 1)
        self.subGroupFilterCombo = QtGui.QComboBox(self.FilterDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subGroupFilterCombo.sizePolicy().hasHeightForWidth())
        self.subGroupFilterCombo.setSizePolicy(sizePolicy)
        self.subGroupFilterCombo.setEditable(True)
        self.subGroupFilterCombo.setObjectName(_fromUtf8("subGroupFilterCombo"))
        self.gridLayout.addWidget(self.subGroupFilterCombo, 1, 1, 1, 1)
        self.contextFilterLabel = QtGui.QLabel(self.FilterDockContents)
        self.contextFilterLabel.setObjectName(_fromUtf8("contextFilterLabel"))
        self.gridLayout.addWidget(self.contextFilterLabel, 0, 0, 1, 1)
        self.subGroupFilterButton = QtGui.QPushButton(self.FilterDockContents)
        self.subGroupFilterButton.setObjectName(_fromUtf8("subGroupFilterButton"))
        self.gridLayout.addWidget(self.subGroupFilterButton, 1, 2, 1, 1)
        self.contextFilterButton = QtGui.QPushButton(self.FilterDockContents)
        self.contextFilterButton.setObjectName(_fromUtf8("contextFilterButton"))
        self.gridLayout.addWidget(self.contextFilterButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.filterEdit = QtGui.QLineEdit(self.FilterDockContents)
        self.filterEdit.setReadOnly(True)
        self.filterEdit.setObjectName(_fromUtf8("filterEdit"))
        self.verticalLayout.addWidget(self.filterEdit)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.showSchematicsLabel = QtGui.QLabel(self.FilterDockContents)
        self.showSchematicsLabel.setObjectName(_fromUtf8("showSchematicsLabel"))
        self.gridLayout_3.addWidget(self.showSchematicsLabel, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.showLinesCheck = QtGui.QCheckBox(self.FilterDockContents)
        self.showLinesCheck.setText(_fromUtf8(""))
        self.showLinesCheck.setChecked(True)
        self.showLinesCheck.setObjectName(_fromUtf8("showLinesCheck"))
        self.gridLayout_3.addWidget(self.showLinesCheck, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.showPointsLabel = QtGui.QLabel(self.FilterDockContents)
        self.showPointsLabel.setObjectName(_fromUtf8("showPointsLabel"))
        self.gridLayout_3.addWidget(self.showPointsLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.showSchematicsCheck = QtGui.QCheckBox(self.FilterDockContents)
        self.showSchematicsCheck.setText(_fromUtf8(""))
        self.showSchematicsCheck.setChecked(True)
        self.showSchematicsCheck.setObjectName(_fromUtf8("showSchematicsCheck"))
        self.gridLayout_3.addWidget(self.showSchematicsCheck, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.showPolygonsLabel = QtGui.QLabel(self.FilterDockContents)
        self.showPolygonsLabel.setObjectName(_fromUtf8("showPolygonsLabel"))
        self.gridLayout_3.addWidget(self.showPolygonsLabel, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.showLabel = QtGui.QLabel(self.FilterDockContents)
        self.showLabel.setObjectName(_fromUtf8("showLabel"))
        self.gridLayout_3.addWidget(self.showLabel, 1, 0, 1, 1)
        self.showLinesLabel = QtGui.QLabel(self.FilterDockContents)
        self.showLinesLabel.setObjectName(_fromUtf8("showLinesLabel"))
        self.gridLayout_3.addWidget(self.showLinesLabel, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.showPointsCheck = QtGui.QCheckBox(self.FilterDockContents)
        self.showPointsCheck.setText(_fromUtf8(""))
        self.showPointsCheck.setChecked(True)
        self.showPointsCheck.setObjectName(_fromUtf8("showPointsCheck"))
        self.gridLayout_3.addWidget(self.showPointsCheck, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.showPolygonsCheck = QtGui.QCheckBox(self.FilterDockContents)
        self.showPolygonsCheck.setText(_fromUtf8(""))
        self.showPolygonsCheck.setChecked(True)
        self.showPolygonsCheck.setObjectName(_fromUtf8("showPolygonsCheck"))
        self.gridLayout_3.addWidget(self.showPolygonsCheck, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 7, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        FilterDock.setWidget(self.FilterDockContents)
        self.subGroupFilterLabel.setBuddy(self.subGroupFilterCombo)
        self.groupFilterLabel.setBuddy(self.groupFilterCombo)
        self.contextFilterLabel.setBuddy(self.contextFilterCombo)

        self.retranslateUi(FilterDock)
        QtCore.QMetaObject.connectSlotsByName(FilterDock)

    def retranslateUi(self, FilterDock):
        FilterDock.setWindowTitle(_translate("FilterDock", "Filter Ark Layers", None))
        self.loadDataButton.setText(_translate("FilterDock", "Data", None))
        self.zoomButton.setText(_translate("FilterDock", "Zoom", None))
        self.buildFilterButton.setText(_translate("FilterDock", "Build", None))
        self.clearFilterButton.setText(_translate("FilterDock", "Clear", None))
        self.subGroupFilterLabel.setText(_translate("FilterDock", "Sub-Groups:", None))
        self.groupFilterButton.setText(_translate("FilterDock", "Apply", None))
        self.groupFilterLabel.setText(_translate("FilterDock", "Groups:", None))
        self.contextFilterLabel.setText(_translate("FilterDock", "Contexts:", None))
        self.subGroupFilterButton.setText(_translate("FilterDock", "Apply", None))
        self.contextFilterButton.setText(_translate("FilterDock", "Apply", None))
        self.showSchematicsLabel.setText(_translate("FilterDock", "Schms", None))
        self.showLinesCheck.setToolTip(_translate("FilterDock", "Show existing lines", None))
        self.showPointsLabel.setText(_translate("FilterDock", "Points", None))
        self.showSchematicsCheck.setToolTip(_translate("FilterDock", "Show existing schematics", None))
        self.showPolygonsLabel.setText(_translate("FilterDock", "Polys", None))
        self.showLabel.setText(_translate("FilterDock", "Show:", None))
        self.showLinesLabel.setText(_translate("FilterDock", "Lines", None))
        self.showPointsCheck.setToolTip(_translate("FilterDock", "Show existing levels", None))
        self.showPolygonsCheck.setToolTip(_translate("FilterDock", "Show existing polygons", None))

from ..core.dock import QgsDockWidget
