# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ark/gui/ui/project_wizard_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProjectWizard(object):
    def setupUi(self, ProjectWizard):
        ProjectWizard.setObjectName(_fromUtf8("ProjectWizard"))
        ProjectWizard.resize(704, 426)
        ProjectWizard.setOptions(QtGui.QWizard.CancelButtonOnLeft|QtGui.QWizard.NoBackButtonOnStartPage|QtGui.QWizard.NoDefaultButton)
        self.serverPage = ServerWizardPage()
        self.serverPage.setObjectName(_fromUtf8("serverPage"))
        self.serverLayout = QtGui.QGridLayout(self.serverPage)
        self.serverLayout.setObjectName(_fromUtf8("serverLayout"))
        self.arkLabel = QtGui.QLabel(self.serverPage)
        self.arkLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.arkLabel.setWordWrap(True)
        self.arkLabel.setObjectName(_fromUtf8("arkLabel"))
        self.serverLayout.addWidget(self.arkLabel, 0, 0, 1, 2)
        self.serverWidget = ServerWidget(self.serverPage)
        self.serverWidget.setObjectName(_fromUtf8("serverWidget"))
        self.serverLayout.addWidget(self.serverWidget, 1, 0, 1, 2)
        ProjectWizard.addPage(self.serverPage)
        self.projectPage = ProjectPage()
        self.projectPage.setObjectName(_fromUtf8("projectPage"))
        self.projectLayout = QtGui.QGridLayout(self.projectPage)
        self.projectLayout.setObjectName(_fromUtf8("projectLayout"))
        self.crsWidget = QgsProjectionSelectionWidget(self.projectPage)
        self.crsWidget.setObjectName(_fromUtf8("crsWidget"))
        self.projectLayout.addWidget(self.crsWidget, 6, 1, 1, 2)
        self.projectCodeLabel = QtGui.QLabel(self.projectPage)
        self.projectCodeLabel.setObjectName(_fromUtf8("projectCodeLabel"))
        self.projectLayout.addWidget(self.projectCodeLabel, 1, 0, 1, 1)
        self.projectNameLabel = QtGui.QLabel(self.projectPage)
        self.projectNameLabel.setObjectName(_fromUtf8("projectNameLabel"))
        self.projectLayout.addWidget(self.projectNameLabel, 2, 0, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(self.projectPage)
        self.siteCodeLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.siteCodeLabel.setWordWrap(True)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.projectLayout.addWidget(self.siteCodeLabel, 3, 0, 1, 1)
        self.locationLabel = QtGui.QLabel(self.projectPage)
        self.locationLabel.setObjectName(_fromUtf8("locationLabel"))
        self.projectLayout.addWidget(self.locationLabel, 4, 0, 1, 1)
        self.locationEastingEdit = QtGui.QLineEdit(self.projectPage)
        self.locationEastingEdit.setObjectName(_fromUtf8("locationEastingEdit"))
        self.projectLayout.addWidget(self.locationEastingEdit, 4, 1, 1, 1)
        self.crsAuthidLabel = QtGui.QLabel(self.projectPage)
        self.crsAuthidLabel.setObjectName(_fromUtf8("crsAuthidLabel"))
        self.projectLayout.addWidget(self.crsAuthidLabel, 6, 0, 1, 1)
        self.siteRadiusLabel = QtGui.QLabel(self.projectPage)
        self.siteRadiusLabel.setObjectName(_fromUtf8("siteRadiusLabel"))
        self.projectLayout.addWidget(self.siteRadiusLabel, 5, 0, 1, 1)
        self.siteRadiusSpin = QtGui.QDoubleSpinBox(self.projectPage)
        self.siteRadiusSpin.setDecimals(1)
        self.siteRadiusSpin.setMinimum(0.0)
        self.siteRadiusSpin.setSingleStep(0.25)
        self.siteRadiusSpin.setProperty("value", 1.0)
        self.siteRadiusSpin.setObjectName(_fromUtf8("siteRadiusSpin"))
        self.projectLayout.addWidget(self.siteRadiusSpin, 5, 1, 1, 1)
        self.projectNameEdit = QtGui.QLineEdit(self.projectPage)
        self.projectNameEdit.setEnabled(True)
        self.projectNameEdit.setObjectName(_fromUtf8("projectNameEdit"))
        self.projectLayout.addWidget(self.projectNameEdit, 2, 1, 1, 2)
        self.projectCodeCombo = QtGui.QComboBox(self.projectPage)
        self.projectCodeCombo.setEditable(True)
        self.projectCodeCombo.setMaxVisibleItems(1)
        self.projectCodeCombo.setMaxCount(1)
        self.projectCodeCombo.setObjectName(_fromUtf8("projectCodeCombo"))
        self.projectLayout.addWidget(self.projectCodeCombo, 1, 1, 1, 2)
        self.siteCodeEdit = QtGui.QLineEdit(self.projectPage)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.projectLayout.addWidget(self.siteCodeEdit, 3, 1, 1, 2)
        self.locationNorthingEdit = QtGui.QLineEdit(self.projectPage)
        self.locationNorthingEdit.setObjectName(_fromUtf8("locationNorthingEdit"))
        self.projectLayout.addWidget(self.locationNorthingEdit, 4, 2, 1, 1)
        self.projectLabel = QtGui.QLabel(self.projectPage)
        self.projectLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.projectLabel.setWordWrap(True)
        self.projectLabel.setObjectName(_fromUtf8("projectLabel"))
        self.projectLayout.addWidget(self.projectLabel, 0, 0, 1, 3)
        ProjectWizard.addPage(self.projectPage)
        self.userPage = UserPage()
        self.userPage.setObjectName(_fromUtf8("userPage"))
        self.userLayout = QtGui.QGridLayout(self.userPage)
        self.userLayout.setObjectName(_fromUtf8("userLayout"))
        self.userFullNameLabel = QtGui.QLabel(self.userPage)
        self.userFullNameLabel.setObjectName(_fromUtf8("userFullNameLabel"))
        self.userLayout.addWidget(self.userFullNameLabel, 1, 0, 1, 1)
        self.userInitialsEdit = QtGui.QLineEdit(self.userPage)
        self.userInitialsEdit.setObjectName(_fromUtf8("userInitialsEdit"))
        self.userLayout.addWidget(self.userInitialsEdit, 2, 1, 1, 1)
        self.userInitialsLabel = QtGui.QLabel(self.userPage)
        self.userInitialsLabel.setObjectName(_fromUtf8("userInitialsLabel"))
        self.userLayout.addWidget(self.userInitialsLabel, 2, 0, 1, 1)
        self.userFullNameEdit = QtGui.QLineEdit(self.userPage)
        self.userFullNameEdit.setObjectName(_fromUtf8("userFullNameEdit"))
        self.userLayout.addWidget(self.userFullNameEdit, 1, 1, 1, 1)
        self.userPageLabel = QtGui.QLabel(self.userPage)
        self.userPageLabel.setObjectName(_fromUtf8("userPageLabel"))
        self.userLayout.addWidget(self.userPageLabel, 0, 0, 1, 2)
        ProjectWizard.addPage(self.userPage)
        self.confirmPage = ConfirmPage()
        self.confirmPage.setObjectName(_fromUtf8("confirmPage"))
        self.gridLayout = QtGui.QGridLayout(self.confirmPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.projectFolderEdit = QtGui.QLineEdit(self.confirmPage)
        self.projectFolderEdit.setObjectName(_fromUtf8("projectFolderEdit"))
        self.gridLayout.addWidget(self.projectFolderEdit, 2, 2, 1, 1)
        self.projectFileLabel = QtGui.QLabel(self.confirmPage)
        self.projectFileLabel.setObjectName(_fromUtf8("projectFileLabel"))
        self.gridLayout.addWidget(self.projectFileLabel, 4, 0, 1, 2)
        self.confirmPageLabel = QtGui.QLabel(self.confirmPage)
        self.confirmPageLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.confirmPageLabel.setWordWrap(True)
        self.confirmPageLabel.setObjectName(_fromUtf8("confirmPageLabel"))
        self.gridLayout.addWidget(self.confirmPageLabel, 0, 0, 1, 3)
        self.projectFolderLabel = QtGui.QLabel(self.confirmPage)
        self.projectFolderLabel.setObjectName(_fromUtf8("projectFolderLabel"))
        self.gridLayout.addWidget(self.projectFolderLabel, 2, 0, 1, 2)
        self.projectFolderButton = QtGui.QToolButton(self.confirmPage)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.projectFolderButton.setIcon(icon)
        self.projectFolderButton.setObjectName(_fromUtf8("projectFolderButton"))
        self.gridLayout.addWidget(self.projectFolderButton, 2, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 2, 1, 1)
        self.projectFileEdit = QtGui.QLineEdit(self.confirmPage)
        self.projectFileEdit.setObjectName(_fromUtf8("projectFileEdit"))
        self.gridLayout.addWidget(self.projectFileEdit, 4, 2, 1, 1)
        self.projectFullPath = QtGui.QLabel(self.confirmPage)
        self.projectFullPath.setObjectName(_fromUtf8("projectFullPath"))
        self.gridLayout.addWidget(self.projectFullPath, 5, 2, 1, 1)
        self.clearProjectCheck = QtGui.QCheckBox(self.confirmPage)
        self.clearProjectCheck.setText(_fromUtf8(""))
        self.clearProjectCheck.setObjectName(_fromUtf8("clearProjectCheck"))
        self.gridLayout.addWidget(self.clearProjectCheck, 6, 2, 1, 1)
        self.projectFullPathLabel = QtGui.QLabel(self.confirmPage)
        self.projectFullPathLabel.setObjectName(_fromUtf8("projectFullPathLabel"))
        self.gridLayout.addWidget(self.projectFullPathLabel, 5, 0, 1, 2)
        self.label = QtGui.QLabel(self.confirmPage)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 6, 0, 1, 2)
        ProjectWizard.addPage(self.confirmPage)
        self.projectCodeLabel.setBuddy(self.projectCodeCombo)
        self.projectNameLabel.setBuddy(self.projectNameEdit)
        self.siteCodeLabel.setBuddy(self.siteCodeEdit)
        self.locationLabel.setBuddy(self.locationEastingEdit)
        self.userFullNameLabel.setBuddy(self.userFullNameEdit)
        self.userInitialsLabel.setBuddy(self.userInitialsEdit)
        self.projectFileLabel.setBuddy(self.projectFileEdit)
        self.projectFolderLabel.setBuddy(self.projectFolderEdit)

        self.retranslateUi(ProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(ProjectWizard)
        ProjectWizard.setTabOrder(self.projectCodeCombo, self.projectNameEdit)
        ProjectWizard.setTabOrder(self.projectNameEdit, self.siteCodeEdit)
        ProjectWizard.setTabOrder(self.siteCodeEdit, self.locationEastingEdit)
        ProjectWizard.setTabOrder(self.locationEastingEdit, self.locationNorthingEdit)
        ProjectWizard.setTabOrder(self.locationNorthingEdit, self.userFullNameEdit)
        ProjectWizard.setTabOrder(self.userFullNameEdit, self.userInitialsEdit)

    def retranslateUi(self, ProjectWizard):
        ProjectWizard.setWindowTitle(_translate("ProjectWizard", "ARKspatial Project Wizard", None))
        self.serverPage.setTitle(_translate("ProjectWizard", "ARKspatial Project Wizard", None))
        self.serverPage.setSubTitle(_translate("ProjectWizard", "This wizard will walk you through setting up a new or existing ARKspatial project.", None))
        self.arkLabel.setText(_translate("ProjectWizard", "If you use an ARK database for project management or site recording, enter the server details to enable automatic population of your project details.", None))
        self.projectPage.setTitle(_translate("ProjectWizard", "Project Details", None))
        self.projectPage.setSubTitle(_translate("ProjectWizard", "Enter the details for the Project.", None))
        self.projectCodeLabel.setText(_translate("ProjectWizard", "Project Code:", None))
        self.projectNameLabel.setText(_translate("ProjectWizard", "Project Name:", None))
        self.siteCodeLabel.setText(_translate("ProjectWizard", "Site Code:", None))
        self.locationLabel.setText(_translate("ProjectWizard", "Location:", None))
        self.locationEastingEdit.setPlaceholderText(_translate("ProjectWizard", "Easting", None))
        self.crsAuthidLabel.setText(_translate("ProjectWizard", "CRS:", None))
        self.siteRadiusLabel.setText(_translate("ProjectWizard", "Radius:", None))
        self.siteRadiusSpin.setSuffix(_translate("ProjectWizard", " km", None))
        self.projectNameEdit.setPlaceholderText(_translate("ProjectWizard", "Shuqba Cave, Wadi an-Natuf", None))
        self.siteCodeEdit.setPlaceholderText(_translate("ProjectWizard", "SHU28", None))
        self.locationNorthingEdit.setPlaceholderText(_translate("ProjectWizard", "Northing", None))
        self.projectLabel.setText(_translate("ProjectWizard", "You must enter at least a Project Code and Name. If no Site Code is entered, the Project Code is used instead. The Location will be used to create a site centre point and (optionally) a site radius.", None))
        self.userPage.setTitle(_translate("ProjectWizard", "User Details", None))
        self.userPage.setSubTitle(_translate("ProjectWizard", "Enter your user details.", None))
        self.userFullNameLabel.setText(_translate("ProjectWizard", "Full Name:", None))
        self.userInitialsEdit.setPlaceholderText(_translate("ProjectWizard", "DG", None))
        self.userInitialsLabel.setText(_translate("ProjectWizard", "Initials:", None))
        self.userFullNameEdit.setPlaceholderText(_translate("ProjectWizard", "Dorothy Garrod", None))
        self.userPageLabel.setText(_translate("ProjectWizard", "Enter your name and initials to be recorded as metadata on edits that you make.", None))
        self.confirmPage.setTitle(_translate("ProjectWizard", "Create Project", None))
        self.confirmPage.setSubTitle(_translate("ProjectWizard", "Confirm your project file details.", None))
        self.projectFolderEdit.setPlaceholderText(_translate("ProjectWizard", "/Disk/Data/Projects/TST01/GIS", None))
        self.projectFileLabel.setText(_translate("ProjectWizard", "Project Filename:", None))
        self.confirmPageLabel.setText(_translate("ProjectWizard", "You can choose to save the project details in the currently open project, or to save the project in a new project file.\n"
"\n"
"This folder is usually something like \"Projects/TST01/GIS\" where TST01 is the Project Code. The folder will be created if it does not already exist.\n"
"\n"
"ARK Spatial will automatically organise the data under this folder.\n"
"", None))
        self.projectFolderLabel.setText(_translate("ProjectWizard", "Project Folder:", None))
        self.projectFileEdit.setPlaceholderText(_translate("ProjectWizard", "SHU28", None))
        self.projectFullPathLabel.setText(_translate("ProjectWizard", "Full Path:", None))
        self.label.setText(_translate("ProjectWizard", "Clear Project:", None))

from ..server_widget import ServerWidget
from ..server_wizard_page import ServerWizardPage
from ..wizard_page import ConfirmPage, ProjectPage, UserPage
from qgis.gui import QgsProjectionSelectionWidget
