# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/settings_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogBase(object):
    def setupUi(self, SettingsDialogBase):
        SettingsDialogBase.setObjectName(_fromUtf8("SettingsDialogBase"))
        SettingsDialogBase.resize(554, 406)
        self.gridLayout = QtGui.QGridLayout(SettingsDialogBase)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(SettingsDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.userTab = QtGui.QWidget()
        self.userTab.setObjectName(_fromUtf8("userTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.userTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.drawingTransparencySpin = QtGui.QSpinBox(self.userTab)
        self.drawingTransparencySpin.setMaximum(100)
        self.drawingTransparencySpin.setProperty("value", 50)
        self.drawingTransparencySpin.setObjectName(_fromUtf8("drawingTransparencySpin"))
        self.horizontalLayout_4.addWidget(self.drawingTransparencySpin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.drawingTransparencyLabel = QtGui.QLabel(self.userTab)
        self.drawingTransparencyLabel.setObjectName(_fromUtf8("drawingTransparencyLabel"))
        self.gridLayout_3.addWidget(self.drawingTransparencyLabel, 3, 0, 1, 1)
        self.userInitialsLabel = QtGui.QLabel(self.userTab)
        self.userInitialsLabel.setObjectName(_fromUtf8("userInitialsLabel"))
        self.gridLayout_3.addWidget(self.userInitialsLabel, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 1, 1, 1)
        self.userInitialEdit = QtGui.QLineEdit(self.userTab)
        self.userInitialEdit.setObjectName(_fromUtf8("userInitialEdit"))
        self.gridLayout_3.addWidget(self.userInitialEdit, 1, 1, 1, 1)
        self.userFullnameEdit = QtGui.QLineEdit(self.userTab)
        self.userFullnameEdit.setObjectName(_fromUtf8("userFullnameEdit"))
        self.gridLayout_3.addWidget(self.userFullnameEdit, 0, 1, 1, 1)
        self.userFullnameLabel = QtGui.QLabel(self.userTab)
        self.userFullnameLabel.setObjectName(_fromUtf8("userFullnameLabel"))
        self.gridLayout_3.addWidget(self.userFullnameLabel, 0, 0, 1, 1)
        self.arkUserIdLabel = QtGui.QLabel(self.userTab)
        self.arkUserIdLabel.setObjectName(_fromUtf8("arkUserIdLabel"))
        self.gridLayout_3.addWidget(self.arkUserIdLabel, 2, 0, 1, 1)
        self.arkUserIdEdit = QtGui.QLineEdit(self.userTab)
        self.arkUserIdEdit.setObjectName(_fromUtf8("arkUserIdEdit"))
        self.gridLayout_3.addWidget(self.arkUserIdEdit, 2, 1, 1, 1)
        self.tabWidget.addTab(self.userTab, _fromUtf8(""))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.arkUrlLabel = QtGui.QLabel(self.projectTab)
        self.arkUrlLabel.setObjectName(_fromUtf8("arkUrlLabel"))
        self.gridLayout_5.addWidget(self.arkUrlLabel, 2, 0, 1, 1)
        self.planDrawingFolderLayout = QtGui.QHBoxLayout()
        self.planDrawingFolderLayout.setObjectName(_fromUtf8("planDrawingFolderLayout"))
        self.planDrawingFolderCheck = QtGui.QCheckBox(self.projectTab)
        self.planDrawingFolderCheck.setText(_fromUtf8(""))
        self.planDrawingFolderCheck.setObjectName(_fromUtf8("planDrawingFolderCheck"))
        self.planDrawingFolderLayout.addWidget(self.planDrawingFolderCheck)
        self.planDrawingFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.planDrawingFolderEdit.setEnabled(False)
        self.planDrawingFolderEdit.setObjectName(_fromUtf8("planDrawingFolderEdit"))
        self.planDrawingFolderLayout.addWidget(self.planDrawingFolderEdit)
        self.planDrawingFolderButton = QtGui.QPushButton(self.projectTab)
        self.planDrawingFolderButton.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.planDrawingFolderButton.setIcon(icon)
        self.planDrawingFolderButton.setObjectName(_fromUtf8("planDrawingFolderButton"))
        self.planDrawingFolderLayout.addWidget(self.planDrawingFolderButton)
        self.gridLayout_5.addLayout(self.planDrawingFolderLayout, 5, 2, 1, 1)
        self.planDrawingFolderLabel = QtGui.QLabel(self.projectTab)
        self.planDrawingFolderLabel.setObjectName(_fromUtf8("planDrawingFolderLabel"))
        self.gridLayout_5.addWidget(self.planDrawingFolderLabel, 5, 0, 1, 1)
        self.sectionDrawingFolderLayout = QtGui.QHBoxLayout()
        self.sectionDrawingFolderLayout.setObjectName(_fromUtf8("sectionDrawingFolderLayout"))
        self.sectionDrawingFolderCheck = QtGui.QCheckBox(self.projectTab)
        self.sectionDrawingFolderCheck.setText(_fromUtf8(""))
        self.sectionDrawingFolderCheck.setObjectName(_fromUtf8("sectionDrawingFolderCheck"))
        self.sectionDrawingFolderLayout.addWidget(self.sectionDrawingFolderCheck)
        self.sectionDrawingFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.sectionDrawingFolderEdit.setEnabled(False)
        self.sectionDrawingFolderEdit.setObjectName(_fromUtf8("sectionDrawingFolderEdit"))
        self.sectionDrawingFolderLayout.addWidget(self.sectionDrawingFolderEdit)
        self.sectionDrawingFolderButton = QtGui.QPushButton(self.projectTab)
        self.sectionDrawingFolderButton.setEnabled(False)
        self.sectionDrawingFolderButton.setIcon(icon)
        self.sectionDrawingFolderButton.setObjectName(_fromUtf8("sectionDrawingFolderButton"))
        self.sectionDrawingFolderLayout.addWidget(self.sectionDrawingFolderButton)
        self.gridLayout_5.addLayout(self.sectionDrawingFolderLayout, 6, 2, 1, 1)
        self.logUpdatesLabel = QtGui.QLabel(self.projectTab)
        self.logUpdatesLabel.setObjectName(_fromUtf8("logUpdatesLabel"))
        self.gridLayout_5.addWidget(self.logUpdatesLabel, 8, 0, 1, 1)
        self.projectCodeEdit = QtGui.QLineEdit(self.projectTab)
        self.projectCodeEdit.setObjectName(_fromUtf8("projectCodeEdit"))
        self.gridLayout_5.addWidget(self.projectCodeEdit, 0, 2, 1, 1)
        self.arkUrlEdit = QtGui.QLineEdit(self.projectTab)
        self.arkUrlEdit.setEnabled(False)
        self.arkUrlEdit.setObjectName(_fromUtf8("arkUrlEdit"))
        self.gridLayout_5.addWidget(self.arkUrlEdit, 2, 2, 1, 1)
        self.siteCodesLabel = QtGui.QLabel(self.projectTab)
        self.siteCodesLabel.setObjectName(_fromUtf8("siteCodesLabel"))
        self.gridLayout_5.addWidget(self.siteCodesLabel, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 10, 2, 1, 1)
        self.siteCodesEdit = QtGui.QLineEdit(self.projectTab)
        self.siteCodesEdit.setObjectName(_fromUtf8("siteCodesEdit"))
        self.gridLayout_5.addWidget(self.siteCodesEdit, 1, 2, 1, 1)
        self.logUpdatesCheck = QtGui.QCheckBox(self.projectTab)
        self.logUpdatesCheck.setText(_fromUtf8(""))
        self.logUpdatesCheck.setChecked(True)
        self.logUpdatesCheck.setObjectName(_fromUtf8("logUpdatesCheck"))
        self.gridLayout_5.addWidget(self.logUpdatesCheck, 8, 2, 1, 1)
        self.contextDrawingFolderLayout = QtGui.QHBoxLayout()
        self.contextDrawingFolderLayout.setObjectName(_fromUtf8("contextDrawingFolderLayout"))
        self.contextDrawingFolderCheck = QtGui.QCheckBox(self.projectTab)
        self.contextDrawingFolderCheck.setText(_fromUtf8(""))
        self.contextDrawingFolderCheck.setObjectName(_fromUtf8("contextDrawingFolderCheck"))
        self.contextDrawingFolderLayout.addWidget(self.contextDrawingFolderCheck)
        self.contextDrawingFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.contextDrawingFolderEdit.setEnabled(False)
        self.contextDrawingFolderEdit.setObjectName(_fromUtf8("contextDrawingFolderEdit"))
        self.contextDrawingFolderLayout.addWidget(self.contextDrawingFolderEdit)
        self.contextDrawingFolderButton = QtGui.QPushButton(self.projectTab)
        self.contextDrawingFolderButton.setEnabled(False)
        self.contextDrawingFolderButton.setIcon(icon)
        self.contextDrawingFolderButton.setObjectName(_fromUtf8("contextDrawingFolderButton"))
        self.contextDrawingFolderLayout.addWidget(self.contextDrawingFolderButton)
        self.gridLayout_5.addLayout(self.contextDrawingFolderLayout, 4, 2, 1, 1)
        self.sectionDrawingFolderLabel = QtGui.QLabel(self.projectTab)
        self.sectionDrawingFolderLabel.setObjectName(_fromUtf8("sectionDrawingFolderLabel"))
        self.gridLayout_5.addWidget(self.sectionDrawingFolderLabel, 6, 0, 1, 1)
        self.contextDrawingFolderLabel = QtGui.QLabel(self.projectTab)
        self.contextDrawingFolderLabel.setObjectName(_fromUtf8("contextDrawingFolderLabel"))
        self.gridLayout_5.addWidget(self.contextDrawingFolderLabel, 4, 0, 1, 1)
        self.projectCodeLabel = QtGui.QLabel(self.projectTab)
        self.projectCodeLabel.setObjectName(_fromUtf8("projectCodeLabel"))
        self.gridLayout_5.addWidget(self.projectCodeLabel, 0, 0, 1, 1)
        self.styleFolderLabel = QtGui.QLabel(self.projectTab)
        self.styleFolderLabel.setObjectName(_fromUtf8("styleFolderLabel"))
        self.gridLayout_5.addWidget(self.styleFolderLabel, 7, 0, 1, 1)
        self.styleFolderLayout = QtGui.QHBoxLayout()
        self.styleFolderLayout.setObjectName(_fromUtf8("styleFolderLayout"))
        self.styleFolderCheck = QtGui.QCheckBox(self.projectTab)
        self.styleFolderCheck.setText(_fromUtf8(""))
        self.styleFolderCheck.setObjectName(_fromUtf8("styleFolderCheck"))
        self.styleFolderLayout.addWidget(self.styleFolderCheck)
        self.styleFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.styleFolderEdit.setEnabled(False)
        self.styleFolderEdit.setObjectName(_fromUtf8("styleFolderEdit"))
        self.styleFolderLayout.addWidget(self.styleFolderEdit)
        self.styleFolderButton = QtGui.QPushButton(self.projectTab)
        self.styleFolderButton.setEnabled(False)
        self.styleFolderButton.setIcon(icon)
        self.styleFolderButton.setIconSize(QtCore.QSize(12, 12))
        self.styleFolderButton.setObjectName(_fromUtf8("styleFolderButton"))
        self.styleFolderLayout.addWidget(self.styleFolderButton)
        self.gridLayout_5.addLayout(self.styleFolderLayout, 7, 2, 1, 1)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.siteCodesLabel.setBuddy(self.siteCodesEdit)
        self.contextDrawingFolderLabel.setBuddy(self.contextDrawingFolderCheck)
        self.styleFolderLabel.setBuddy(self.styleFolderEdit)

        self.retranslateUi(SettingsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogBase.reject)
        QtCore.QObject.connect(self.styleFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.styleFolderButton.setEnabled)
        QtCore.QObject.connect(self.styleFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.styleFolderEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogBase)
        SettingsDialogBase.setTabOrder(self.siteCodesEdit, self.styleFolderCheck)
        SettingsDialogBase.setTabOrder(self.styleFolderCheck, self.styleFolderEdit)
        SettingsDialogBase.setTabOrder(self.styleFolderEdit, self.styleFolderButton)
        SettingsDialogBase.setTabOrder(self.styleFolderButton, self.tabWidget)
        SettingsDialogBase.setTabOrder(self.tabWidget, self.buttonBox)

    def retranslateUi(self, SettingsDialogBase):
        SettingsDialogBase.setWindowTitle(_translate("SettingsDialogBase", "Settings", None))
        self.drawingTransparencySpin.setSuffix(_translate("SettingsDialogBase", "%", None))
        self.drawingTransparencyLabel.setText(_translate("SettingsDialogBase", "Drawing Tranparency:", None))
        self.userInitialsLabel.setText(_translate("SettingsDialogBase", "Initials:", None))
        self.userFullnameLabel.setText(_translate("SettingsDialogBase", "Full Name:", None))
        self.arkUserIdLabel.setText(_translate("SettingsDialogBase", "ARK User ID:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.userTab), _translate("SettingsDialogBase", "User", None))
        self.arkUrlLabel.setText(_translate("SettingsDialogBase", "ARK URL:", None))
        self.planDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Plan Drawings:", None))
        self.logUpdatesLabel.setText(_translate("SettingsDialogBase", "Log Updates:", None))
        self.siteCodesLabel.setText(_translate("SettingsDialogBase", "Site Code(s):", None))
        self.sectionDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Section Drawings:", None))
        self.contextDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Context Drawings:", None))
        self.projectCodeLabel.setText(_translate("SettingsDialogBase", "Project Code", None))
        self.styleFolderLabel.setText(_translate("SettingsDialogBase", "Styles Folder:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("SettingsDialogBase", "Project", None))

import resources
