# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ark_georef_dialog_base.ui'
#
# Created: Mon Jan 12 12:49:09 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ArkGeorefDialogBase(object):
    def setupUi(self, ArkGeorefDialogBase):
        ArkGeorefDialogBase.setObjectName(_fromUtf8("ArkGeorefDialogBase"))
        ArkGeorefDialogBase.resize(1089, 906)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ArkGeorefDialogBase.sizePolicy().hasHeightForWidth())
        ArkGeorefDialogBase.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(ArkGeorefDialogBase)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.m_gridLabel1 = QtGui.QLabel(ArkGeorefDialogBase)
        self.m_gridLabel1.setObjectName(_fromUtf8("m_gridLabel1"))
        self.horizontalLayout.addWidget(self.m_gridLabel1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.m_autoButton1 = QtGui.QPushButton(ArkGeorefDialogBase)
        self.m_autoButton1.setObjectName(_fromUtf8("m_autoButton1"))
        self.horizontalLayout.addWidget(self.m_autoButton1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.m_gridView1 = ArkGeorefGraphicsView(ArkGeorefDialogBase)
        self.m_gridView1.setInteractive(False)
        self.m_gridView1.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.m_gridView1.setObjectName(_fromUtf8("m_gridView1"))
        self.verticalLayout.addWidget(self.m_gridView1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton = QtGui.QPushButton(ArkGeorefDialogBase)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.m_runButton = QtGui.QPushButton(ArkGeorefDialogBase)
        self.m_runButton.setObjectName(_fromUtf8("m_runButton"))
        self.horizontalLayout_5.addWidget(self.m_runButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(ArkGeorefDialogBase)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(ArkGeorefDialogBase)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.m_gcpTable = QtGui.QTableWidget(ArkGeorefDialogBase)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.m_gcpTable.setFont(font)
        self.m_gcpTable.setRowCount(3)
        self.m_gcpTable.setColumnCount(6)
        self.m_gcpTable.setObjectName(_fromUtf8("m_gcpTable"))
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.m_gcpTable.setItem(2, 5, item)
        self.m_gcpTable.horizontalHeader().setDefaultSectionSize(70)
        self.m_gcpTable.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_4.addWidget(self.m_gcpTable)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.m_gridLabel2 = QtGui.QLabel(ArkGeorefDialogBase)
        self.m_gridLabel2.setObjectName(_fromUtf8("m_gridLabel2"))
        self.horizontalLayout_2.addWidget(self.m_gridLabel2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.m_autoButton2 = QtGui.QPushButton(ArkGeorefDialogBase)
        self.m_autoButton2.setObjectName(_fromUtf8("m_autoButton2"))
        self.horizontalLayout_2.addWidget(self.m_autoButton2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.m_gridView2 = ArkGeorefGraphicsView(ArkGeorefDialogBase)
        self.m_gridView2.setInteractive(False)
        self.m_gridView2.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.m_gridView2.setObjectName(_fromUtf8("m_gridView2"))
        self.verticalLayout_2.addWidget(self.m_gridView2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.m_gridLabel3 = QtGui.QLabel(ArkGeorefDialogBase)
        self.m_gridLabel3.setObjectName(_fromUtf8("m_gridLabel3"))
        self.horizontalLayout_3.addWidget(self.m_gridLabel3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.m_autoButton3 = QtGui.QPushButton(ArkGeorefDialogBase)
        self.m_autoButton3.setObjectName(_fromUtf8("m_autoButton3"))
        self.horizontalLayout_3.addWidget(self.m_autoButton3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.m_gridView3 = ArkGeorefGraphicsView(ArkGeorefDialogBase)
        self.m_gridView3.setInteractive(False)
        self.m_gridView3.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.m_gridView3.setObjectName(_fromUtf8("m_gridView3"))
        self.verticalLayout_3.addWidget(self.m_gridView3)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(ArkGeorefDialogBase)
        QtCore.QMetaObject.connectSlotsByName(ArkGeorefDialogBase)

    def retranslateUi(self, ArkGeorefDialogBase):
        ArkGeorefDialogBase.setWindowTitle(_translate("ArkGeorefDialogBase", "Dialog", None))
        self.m_gridLabel1.setText(_translate("ArkGeorefDialogBase", "000 / 000 :", None))
        self.m_autoButton1.setText(_translate("ArkGeorefDialogBase", "Auto", None))
        self.pushButton.setText(_translate("ArkGeorefDialogBase", "Auto All", None))
        self.m_runButton.setText(_translate("ArkGeorefDialogBase", "Run", None))
        self.label.setText(_translate("ArkGeorefDialogBase", "Grid Square:", None))
        item = self.m_gcpTable.verticalHeaderItem(0)
        item.setText(_translate("ArkGeorefDialogBase", "GCP1", None))
        item = self.m_gcpTable.verticalHeaderItem(1)
        item.setText(_translate("ArkGeorefDialogBase", "GCP2", None))
        item = self.m_gcpTable.verticalHeaderItem(2)
        item.setText(_translate("ArkGeorefDialogBase", "GCP3", None))
        item = self.m_gcpTable.horizontalHeaderItem(0)
        item.setText(_translate("ArkGeorefDialogBase", "Raw X", None))
        item = self.m_gcpTable.horizontalHeaderItem(1)
        item.setText(_translate("ArkGeorefDialogBase", "Raw Y", None))
        item = self.m_gcpTable.horizontalHeaderItem(2)
        item.setText(_translate("ArkGeorefDialogBase", "Grid X", None))
        item = self.m_gcpTable.horizontalHeaderItem(3)
        item.setText(_translate("ArkGeorefDialogBase", "Grid Y", None))
        item = self.m_gcpTable.horizontalHeaderItem(4)
        item.setText(_translate("ArkGeorefDialogBase", "Geo X", None))
        item = self.m_gcpTable.horizontalHeaderItem(5)
        item.setText(_translate("ArkGeorefDialogBase", "Geo Y", None))
        __sortingEnabled = self.m_gcpTable.isSortingEnabled()
        self.m_gcpTable.setSortingEnabled(False)
        item = self.m_gcpTable.item(0, 0)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(0, 1)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(0, 2)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(0, 3)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(0, 4)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(0, 5)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(1, 0)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(1, 1)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(1, 2)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(1, 3)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(1, 4)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(1, 5)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(2, 0)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(2, 1)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(2, 2)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(2, 3)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(2, 4)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        item = self.m_gcpTable.item(2, 5)
        item.setText(_translate("ArkGeorefDialogBase", "0", None))
        self.m_gcpTable.setSortingEnabled(__sortingEnabled)
        self.m_gridLabel2.setText(_translate("ArkGeorefDialogBase", "000 / 000 :", None))
        self.m_autoButton2.setText(_translate("ArkGeorefDialogBase", "Auto", None))
        self.m_gridLabel3.setText(_translate("ArkGeorefDialogBase", "000 / 000 :", None))
        self.m_autoButton3.setText(_translate("ArkGeorefDialogBase", "Auto", None))

from ark_georef_graphics_view import ArkGeorefGraphicsView
