# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dock.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_m_arkPlanDockWidget(object):
    def setupUi(self, m_arkPlanDockWidget):
        m_arkPlanDockWidget.setObjectName(_fromUtf8("m_arkPlanDockWidget"))
        m_arkPlanDockWidget.resize(286, 665)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.m_newContextGroup = QtGui.QGroupBox(self.dockWidgetContents)
        self.m_newContextGroup.setObjectName(_fromUtf8("m_newContextGroup"))
        self.formLayout = QtGui.QFormLayout(self.m_newContextGroup)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.m_contextLabel = QtGui.QLabel(self.m_newContextGroup)
        self.m_contextLabel.setObjectName(_fromUtf8("m_contextLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.m_contextLabel)
        self.m_contextSpin = QtGui.QSpinBox(self.m_newContextGroup)
        self.m_contextSpin.setMaximum(9999)
        self.m_contextSpin.setObjectName(_fromUtf8("m_contextSpin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.m_contextSpin)
        self.m_sourceLabel = QtGui.QLabel(self.m_newContextGroup)
        self.m_sourceLabel.setObjectName(_fromUtf8("m_sourceLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.m_sourceLabel)
        self.m_sourceEdit = QtGui.QLineEdit(self.m_newContextGroup)
        self.m_sourceEdit.setObjectName(_fromUtf8("m_sourceEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.m_sourceEdit)
        self.m_editModeGroup = QtGui.QGroupBox(self.m_newContextGroup)
        self.m_editModeGroup.setObjectName(_fromUtf8("m_editModeGroup"))
        self.gridLayout = QtGui.QGridLayout(self.m_editModeGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.m_extentTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_extentTool.setObjectName(_fromUtf8("m_extentTool"))
        self.gridLayout.addWidget(self.m_extentTool, 0, 0, 1, 1)
        self.m_verticalEdgeTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_verticalEdgeTool.setObjectName(_fromUtf8("m_verticalEdgeTool"))
        self.gridLayout.addWidget(self.m_verticalEdgeTool, 0, 1, 1, 1)
        self.m_uncertainEdgeTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_uncertainEdgeTool.setObjectName(_fromUtf8("m_uncertainEdgeTool"))
        self.gridLayout.addWidget(self.m_uncertainEdgeTool, 0, 2, 1, 1)
        self.m_limitOfExcavationTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_limitOfExcavationTool.setObjectName(_fromUtf8("m_limitOfExcavationTool"))
        self.gridLayout.addWidget(self.m_limitOfExcavationTool, 0, 3, 1, 1)
        self.m_verticalTruncationTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_verticalTruncationTool.setObjectName(_fromUtf8("m_verticalTruncationTool"))
        self.gridLayout.addWidget(self.m_verticalTruncationTool, 1, 0, 1, 1)
        self.m_truncationTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_truncationTool.setObjectName(_fromUtf8("m_truncationTool"))
        self.gridLayout.addWidget(self.m_truncationTool, 1, 1, 1, 1)
        self.m_breakOfSlopeTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_breakOfSlopeTool.setObjectName(_fromUtf8("m_breakOfSlopeTool"))
        self.gridLayout.addWidget(self.m_breakOfSlopeTool, 1, 2, 1, 1)
        self.m_verticalBreakOfSlopeTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_verticalBreakOfSlopeTool.setObjectName(_fromUtf8("m_verticalBreakOfSlopeTool"))
        self.gridLayout.addWidget(self.m_verticalBreakOfSlopeTool, 1, 3, 1, 1)
        self.m_hachureTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_hachureTool.setObjectName(_fromUtf8("m_hachureTool"))
        self.gridLayout.addWidget(self.m_hachureTool, 2, 0, 1, 1)
        self.m_undercutTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_undercutTool.setObjectName(_fromUtf8("m_undercutTool"))
        self.gridLayout.addWidget(self.m_undercutTool, 2, 1, 1, 1)
        self.m_returnOfSlopeTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_returnOfSlopeTool.setObjectName(_fromUtf8("m_returnOfSlopeTool"))
        self.gridLayout.addWidget(self.m_returnOfSlopeTool, 2, 2, 1, 1)
        self.m_cbmTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_cbmTool.setObjectName(_fromUtf8("m_cbmTool"))
        self.gridLayout.addWidget(self.m_cbmTool, 3, 0, 1, 1)
        self.m_brickTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_brickTool.setObjectName(_fromUtf8("m_brickTool"))
        self.gridLayout.addWidget(self.m_brickTool, 3, 1, 1, 1)
        self.m_tileTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_tileTool.setObjectName(_fromUtf8("m_tileTool"))
        self.gridLayout.addWidget(self.m_tileTool, 3, 2, 1, 1)
        self.m_mortarTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_mortarTool.setObjectName(_fromUtf8("m_mortarTool"))
        self.gridLayout.addWidget(self.m_mortarTool, 3, 3, 1, 1)
        self.m_charcoalTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_charcoalTool.setObjectName(_fromUtf8("m_charcoalTool"))
        self.gridLayout.addWidget(self.m_charcoalTool, 4, 0, 1, 1)
        self.m_stoneTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_stoneTool.setObjectName(_fromUtf8("m_stoneTool"))
        self.gridLayout.addWidget(self.m_stoneTool, 4, 1, 1, 1)
        self.m_potTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_potTool.setObjectName(_fromUtf8("m_potTool"))
        self.gridLayout.addWidget(self.m_potTool, 4, 2, 1, 1)
        self.m_flintTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_flintTool.setObjectName(_fromUtf8("m_flintTool"))
        self.gridLayout.addWidget(self.m_flintTool, 4, 3, 1, 1)
        self.m_levelTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_levelTool.setObjectName(_fromUtf8("m_levelTool"))
        self.gridLayout.addWidget(self.m_levelTool, 5, 0, 1, 1)
        self.m_schematicTool = QtGui.QToolButton(self.m_editModeGroup)
        self.m_schematicTool.setObjectName(_fromUtf8("m_schematicTool"))
        self.gridLayout.addWidget(self.m_schematicTool, 5, 1, 1, 1)
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.m_editModeGroup)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.m_saveButton = QtGui.QPushButton(self.m_newContextGroup)
        self.m_saveButton.setObjectName(_fromUtf8("m_saveButton"))
        self.horizontalLayout.addWidget(self.m_saveButton)
        self.m_clearButton = QtGui.QPushButton(self.m_newContextGroup)
        self.m_clearButton.setObjectName(_fromUtf8("m_clearButton"))
        self.horizontalLayout.addWidget(self.m_clearButton)
        self.m_mergeButton = QtGui.QPushButton(self.m_newContextGroup)
        self.m_mergeButton.setObjectName(_fromUtf8("m_mergeButton"))
        self.horizontalLayout.addWidget(self.m_mergeButton)
        self.formLayout.setLayout(3, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout.addWidget(self.m_newContextGroup)
        self.m_existingContextsGroup = QtGui.QGroupBox(self.dockWidgetContents)
        self.m_existingContextsGroup.setObjectName(_fromUtf8("m_existingContextsGroup"))
        self.formLayout_2 = QtGui.QFormLayout(self.m_existingContextsGroup)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.m_hideAllCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_hideAllCheck.setObjectName(_fromUtf8("m_hideAllCheck"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.m_hideAllCheck)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_4 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.m_showLinesCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_showLinesCheck.setText(_fromUtf8(""))
        self.m_showLinesCheck.setObjectName(_fromUtf8("m_showLinesCheck"))
        self.gridLayout_2.addWidget(self.m_showLinesCheck, 1, 1, 1, 1)
        self.m_snapLinesCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_snapLinesCheck.setText(_fromUtf8(""))
        self.m_snapLinesCheck.setObjectName(_fromUtf8("m_snapLinesCheck"))
        self.gridLayout_2.addWidget(self.m_snapLinesCheck, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.m_showPolygonsCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_showPolygonsCheck.setText(_fromUtf8(""))
        self.m_showPolygonsCheck.setObjectName(_fromUtf8("m_showPolygonsCheck"))
        self.gridLayout_2.addWidget(self.m_showPolygonsCheck, 2, 1, 1, 1)
        self.m_snapPolygonsCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_snapPolygonsCheck.setText(_fromUtf8(""))
        self.m_snapPolygonsCheck.setObjectName(_fromUtf8("m_snapPolygonsCheck"))
        self.gridLayout_2.addWidget(self.m_snapPolygonsCheck, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.m_showSchematicsCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_showSchematicsCheck.setText(_fromUtf8(""))
        self.m_showSchematicsCheck.setObjectName(_fromUtf8("m_showSchematicsCheck"))
        self.gridLayout_2.addWidget(self.m_showSchematicsCheck, 3, 1, 1, 1)
        self.m_snapSchematicsCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_snapSchematicsCheck.setText(_fromUtf8(""))
        self.m_snapSchematicsCheck.setObjectName(_fromUtf8("m_snapSchematicsCheck"))
        self.gridLayout_2.addWidget(self.m_snapSchematicsCheck, 3, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.m_showLevelsCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_showLevelsCheck.setText(_fromUtf8(""))
        self.m_showLevelsCheck.setObjectName(_fromUtf8("m_showLevelsCheck"))
        self.gridLayout_2.addWidget(self.m_showLevelsCheck, 4, 1, 1, 1)
        self.m_snapLevelsCheck = QtGui.QCheckBox(self.m_existingContextsGroup)
        self.m_snapLevelsCheck.setText(_fromUtf8(""))
        self.m_snapLevelsCheck.setObjectName(_fromUtf8("m_snapLevelsCheck"))
        self.gridLayout_2.addWidget(self.m_snapLevelsCheck, 4, 2, 1, 1)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.SpanningRole, self.gridLayout_2)
        self.label_9 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.m_contextFilter = QtGui.QLineEdit(self.m_existingContextsGroup)
        self.m_contextFilter.setObjectName(_fromUtf8("m_contextFilter"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.m_contextFilter)
        self.label_10 = QtGui.QLabel(self.m_existingContextsGroup)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.m_sourceFilter = QtGui.QLineEdit(self.m_existingContextsGroup)
        self.m_sourceFilter.setObjectName(_fromUtf8("m_sourceFilter"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.m_sourceFilter)
        self.verticalLayout.addWidget(self.m_existingContextsGroup)
        m_arkPlanDockWidget.setWidget(self.dockWidgetContents)
        self.m_contextLabel.setBuddy(self.m_contextSpin)
        self.m_sourceLabel.setBuddy(self.m_sourceEdit)
        self.label_9.setBuddy(self.m_contextFilter)
        self.label_10.setBuddy(self.m_contextFilter)

        self.retranslateUi(m_arkPlanDockWidget)
        QtCore.QMetaObject.connectSlotsByName(m_arkPlanDockWidget)

    def retranslateUi(self, m_arkPlanDockWidget):
        m_arkPlanDockWidget.setWindowTitle(_translate("m_arkPlanDockWidget", "ArkPlan", None))
        self.m_newContextGroup.setTitle(_translate("m_arkPlanDockWidget", "New Context", None))
        self.m_contextLabel.setText(_translate("m_arkPlanDockWidget", "Context:", None))
        self.m_contextSpin.setToolTip(_translate("m_arkPlanDockWidget", "Context Number", None))
        self.m_sourceLabel.setText(_translate("m_arkPlanDockWidget", "Source:", None))
        self.m_sourceEdit.setToolTip(_translate("m_arkPlanDockWidget", "Source", None))
        self.m_editModeGroup.setTitle(_translate("m_arkPlanDockWidget", "Edit mode", None))
        self.m_extentTool.setToolTip(_translate("m_arkPlanDockWidget", "Extent of context", None))
        self.m_extentTool.setText(_translate("m_arkPlanDockWidget", "ext", None))
        self.m_verticalEdgeTool.setToolTip(_translate("m_arkPlanDockWidget", "Vertical Edge", None))
        self.m_verticalEdgeTool.setText(_translate("m_arkPlanDockWidget", "Veg", None))
        self.m_uncertainEdgeTool.setToolTip(_translate("m_arkPlanDockWidget", "Uncertain Edge", None))
        self.m_uncertainEdgeTool.setText(_translate("m_arkPlanDockWidget", "ueg", None))
        self.m_limitOfExcavationTool.setToolTip(_translate("m_arkPlanDockWidget", "Limit of Excavation", None))
        self.m_limitOfExcavationTool.setText(_translate("m_arkPlanDockWidget", "loe", None))
        self.m_verticalTruncationTool.setToolTip(_translate("m_arkPlanDockWidget", "Vertical Truncation", None))
        self.m_verticalTruncationTool.setText(_translate("m_arkPlanDockWidget", "Vtr", None))
        self.m_truncationTool.setToolTip(_translate("m_arkPlanDockWidget", "Truncation", None))
        self.m_truncationTool.setText(_translate("m_arkPlanDockWidget", "Trn", None))
        self.m_breakOfSlopeTool.setToolTip(_translate("m_arkPlanDockWidget", "Break of Slope", None))
        self.m_breakOfSlopeTool.setText(_translate("m_arkPlanDockWidget", "bos", None))
        self.m_verticalBreakOfSlopeTool.setToolTip(_translate("m_arkPlanDockWidget", "Vertical Break of Slope", None))
        self.m_verticalBreakOfSlopeTool.setText(_translate("m_arkPlanDockWidget", "vbs", None))
        self.m_hachureTool.setToolTip(_translate("m_arkPlanDockWidget", "Hachure", None))
        self.m_hachureTool.setText(_translate("m_arkPlanDockWidget", "hch", None))
        self.m_undercutTool.setToolTip(_translate("m_arkPlanDockWidget", "Undercut", None))
        self.m_undercutTool.setText(_translate("m_arkPlanDockWidget", "unc", None))
        self.m_returnOfSlopeTool.setToolTip(_translate("m_arkPlanDockWidget", "Return of Slope", None))
        self.m_returnOfSlopeTool.setText(_translate("m_arkPlanDockWidget", "ros", None))
        self.m_cbmTool.setToolTip(_translate("m_arkPlanDockWidget", "CBM", None))
        self.m_cbmTool.setText(_translate("m_arkPlanDockWidget", "cbm", None))
        self.m_brickTool.setToolTip(_translate("m_arkPlanDockWidget", "Brick", None))
        self.m_brickTool.setText(_translate("m_arkPlanDockWidget", "brk", None))
        self.m_tileTool.setToolTip(_translate("m_arkPlanDockWidget", "Tile", None))
        self.m_tileTool.setText(_translate("m_arkPlanDockWidget", "til", None))
        self.m_mortarTool.setToolTip(_translate("m_arkPlanDockWidget", "Mortar", None))
        self.m_mortarTool.setText(_translate("m_arkPlanDockWidget", "mtr", None))
        self.m_charcoalTool.setToolTip(_translate("m_arkPlanDockWidget", "Charcoal", None))
        self.m_charcoalTool.setText(_translate("m_arkPlanDockWidget", "cha", None))
        self.m_stoneTool.setToolTip(_translate("m_arkPlanDockWidget", "Stone", None))
        self.m_stoneTool.setText(_translate("m_arkPlanDockWidget", "sto", None))
        self.m_potTool.setToolTip(_translate("m_arkPlanDockWidget", "Pot", None))
        self.m_potTool.setText(_translate("m_arkPlanDockWidget", "pot", None))
        self.m_flintTool.setToolTip(_translate("m_arkPlanDockWidget", "Flint", None))
        self.m_flintTool.setText(_translate("m_arkPlanDockWidget", "fli", None))
        self.m_levelTool.setToolTip(_translate("m_arkPlanDockWidget", "Level", None))
        self.m_levelTool.setText(_translate("m_arkPlanDockWidget", "lvl", None))
        self.m_schematicTool.setToolTip(_translate("m_arkPlanDockWidget", "Schematic", None))
        self.m_schematicTool.setText(_translate("m_arkPlanDockWidget", "sch", None))
        self.m_saveButton.setToolTip(_translate("m_arkPlanDockWidget", "Save edits to work layers", None))
        self.m_saveButton.setText(_translate("m_arkPlanDockWidget", "Save", None))
        self.m_clearButton.setToolTip(_translate("m_arkPlanDockWidget", "Clear unsaved changes from work layers", None))
        self.m_clearButton.setText(_translate("m_arkPlanDockWidget", "Clear", None))
        self.m_mergeButton.setToolTip(_translate("m_arkPlanDockWidget", "Move new context to main layers", None))
        self.m_mergeButton.setText(_translate("m_arkPlanDockWidget", "Merge", None))
        self.m_existingContextsGroup.setTitle(_translate("m_arkPlanDockWidget", "Existing Contexts", None))
        self.m_hideAllCheck.setToolTip(_translate("m_arkPlanDockWidget", "Hide all existing context details.", None))
        self.m_hideAllCheck.setText(_translate("m_arkPlanDockWidget", "Hide All", None))
        self.label_4.setText(_translate("m_arkPlanDockWidget", "Show", None))
        self.label_5.setText(_translate("m_arkPlanDockWidget", "Snap", None))
        self.label_3.setText(_translate("m_arkPlanDockWidget", "Lines:", None))
        self.m_showLinesCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing lines", None))
        self.m_snapLinesCheck.setToolTip(_translate("m_arkPlanDockWidget", "Snap to existing lines", None))
        self.label_6.setText(_translate("m_arkPlanDockWidget", "Polygons:", None))
        self.m_showPolygonsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing polygons", None))
        self.m_snapPolygonsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Snap to existing polygons", None))
        self.label_7.setText(_translate("m_arkPlanDockWidget", "Schematics:", None))
        self.m_showSchematicsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing schematics", None))
        self.m_snapSchematicsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Snap to existing schematics", None))
        self.label_8.setText(_translate("m_arkPlanDockWidget", "Levels:", None))
        self.m_showLevelsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing levels", None))
        self.m_snapLevelsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Snap to existing levels", None))
        self.label_9.setText(_translate("m_arkPlanDockWidget", "Context Filter:", None))
        self.m_contextFilter.setToolTip(_translate("m_arkPlanDockWidget", "Only show selected contexts", None))
        self.label_10.setText(_translate("m_arkPlanDockWidget", "Source Filter:", None))
        self.m_sourceFilter.setToolTip(_translate("m_arkPlanDockWidget", "Only show selected sources", None))

