# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dock.ui'
#
# Created: Wed Feb 25 16:00:46 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_m_arkPlanDockWidget(object):
    def setupUi(self, m_arkPlanDockWidget):
        m_arkPlanDockWidget.setObjectName(_fromUtf8("m_arkPlanDockWidget"))
        m_arkPlanDockWidget.resize(385, 843)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(m_arkPlanDockWidget.sizePolicy().hasHeightForWidth())
        m_arkPlanDockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 791))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.m_loadRawButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.m_loadRawButton.setObjectName(_fromUtf8("m_loadRawButton"))
        self.horizontalLayout_4.addWidget(self.m_loadRawButton)
        self.m_loadGeoButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.m_loadGeoButton.setObjectName(_fromUtf8("m_loadGeoButton"))
        self.horizontalLayout_4.addWidget(self.m_loadGeoButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.m_planGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.m_planGroup.setObjectName(_fromUtf8("m_planGroup"))
        self.formLayout = QtGui.QFormLayout(self.m_planGroup)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.m_siteLabel = QtGui.QLabel(self.m_planGroup)
        self.m_siteLabel.setObjectName(_fromUtf8("m_siteLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.m_siteLabel)
        self.m_siteEdit = QtGui.QLineEdit(self.m_planGroup)
        self.m_siteEdit.setReadOnly(False)
        self.m_siteEdit.setObjectName(_fromUtf8("m_siteEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.m_siteEdit)
        self.m_contextLabel = QtGui.QLabel(self.m_planGroup)
        self.m_contextLabel.setObjectName(_fromUtf8("m_contextLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.m_contextLabel)
        self.m_contextSpin = QtGui.QSpinBox(self.m_planGroup)
        self.m_contextSpin.setMaximum(9999)
        self.m_contextSpin.setObjectName(_fromUtf8("m_contextSpin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.m_contextSpin)
        self.m_sourceEdit = QtGui.QLineEdit(self.m_planGroup)
        self.m_sourceEdit.setObjectName(_fromUtf8("m_sourceEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.m_sourceEdit)
        self.m_sourceLabel = QtGui.QLabel(self.m_planGroup)
        self.m_sourceLabel.setObjectName(_fromUtf8("m_sourceLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.m_sourceLabel)
        self.m_commentEdit = QtGui.QLineEdit(self.m_planGroup)
        self.m_commentEdit.setReadOnly(False)
        self.m_commentEdit.setObjectName(_fromUtf8("m_commentEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.m_commentEdit)
        self.m_commentLabel = QtGui.QLabel(self.m_planGroup)
        self.m_commentLabel.setObjectName(_fromUtf8("m_commentLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.m_commentLabel)
        self.verticalLayout.addWidget(self.m_planGroup)
        self.m_drawingToolsGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.m_drawingToolsGroup.setObjectName(_fromUtf8("m_drawingToolsGroup"))
        self.gridLayout = QtGui.QGridLayout(self.m_drawingToolsGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.m_extentTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_extentTool.setCheckable(True)
        self.m_extentTool.setObjectName(_fromUtf8("m_extentTool"))
        self.gridLayout.addWidget(self.m_extentTool, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_verticalEdgeTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_verticalEdgeTool.setCheckable(True)
        self.m_verticalEdgeTool.setObjectName(_fromUtf8("m_verticalEdgeTool"))
        self.gridLayout.addWidget(self.m_verticalEdgeTool, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_uncertainEdgeTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_uncertainEdgeTool.setCheckable(True)
        self.m_uncertainEdgeTool.setObjectName(_fromUtf8("m_uncertainEdgeTool"))
        self.gridLayout.addWidget(self.m_uncertainEdgeTool, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_limitOfExcavationTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_limitOfExcavationTool.setCheckable(True)
        self.m_limitOfExcavationTool.setObjectName(_fromUtf8("m_limitOfExcavationTool"))
        self.gridLayout.addWidget(self.m_limitOfExcavationTool, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_verticalTruncationTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_verticalTruncationTool.setCheckable(True)
        self.m_verticalTruncationTool.setObjectName(_fromUtf8("m_verticalTruncationTool"))
        self.gridLayout.addWidget(self.m_verticalTruncationTool, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_truncationTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_truncationTool.setCheckable(True)
        self.m_truncationTool.setObjectName(_fromUtf8("m_truncationTool"))
        self.gridLayout.addWidget(self.m_truncationTool, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_breakOfSlopeTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_breakOfSlopeTool.setCheckable(True)
        self.m_breakOfSlopeTool.setObjectName(_fromUtf8("m_breakOfSlopeTool"))
        self.gridLayout.addWidget(self.m_breakOfSlopeTool, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_verticalBreakOfSlopeTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_verticalBreakOfSlopeTool.setCheckable(True)
        self.m_verticalBreakOfSlopeTool.setObjectName(_fromUtf8("m_verticalBreakOfSlopeTool"))
        self.gridLayout.addWidget(self.m_verticalBreakOfSlopeTool, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_hachureTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_hachureTool.setCheckable(True)
        self.m_hachureTool.setObjectName(_fromUtf8("m_hachureTool"))
        self.gridLayout.addWidget(self.m_hachureTool, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_undercutTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_undercutTool.setCheckable(True)
        self.m_undercutTool.setObjectName(_fromUtf8("m_undercutTool"))
        self.gridLayout.addWidget(self.m_undercutTool, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_returnOfSlopeTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_returnOfSlopeTool.setCheckable(True)
        self.m_returnOfSlopeTool.setObjectName(_fromUtf8("m_returnOfSlopeTool"))
        self.gridLayout.addWidget(self.m_returnOfSlopeTool, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_cbmTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_cbmTool.setCheckable(True)
        self.m_cbmTool.setObjectName(_fromUtf8("m_cbmTool"))
        self.gridLayout.addWidget(self.m_cbmTool, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_brickTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_brickTool.setCheckable(True)
        self.m_brickTool.setObjectName(_fromUtf8("m_brickTool"))
        self.gridLayout.addWidget(self.m_brickTool, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_tileTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_tileTool.setCheckable(True)
        self.m_tileTool.setObjectName(_fromUtf8("m_tileTool"))
        self.gridLayout.addWidget(self.m_tileTool, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_mortarTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_mortarTool.setCheckable(True)
        self.m_mortarTool.setObjectName(_fromUtf8("m_mortarTool"))
        self.gridLayout.addWidget(self.m_mortarTool, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_charcoalTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_charcoalTool.setCheckable(True)
        self.m_charcoalTool.setObjectName(_fromUtf8("m_charcoalTool"))
        self.gridLayout.addWidget(self.m_charcoalTool, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_stoneTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_stoneTool.setCheckable(True)
        self.m_stoneTool.setObjectName(_fromUtf8("m_stoneTool"))
        self.gridLayout.addWidget(self.m_stoneTool, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_potTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_potTool.setCheckable(True)
        self.m_potTool.setObjectName(_fromUtf8("m_potTool"))
        self.gridLayout.addWidget(self.m_potTool, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_flintTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_flintTool.setCheckable(True)
        self.m_flintTool.setObjectName(_fromUtf8("m_flintTool"))
        self.gridLayout.addWidget(self.m_flintTool, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_levelTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_levelTool.setCheckable(True)
        self.m_levelTool.setObjectName(_fromUtf8("m_levelTool"))
        self.gridLayout.addWidget(self.m_levelTool, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_schematicTool = QtGui.QToolButton(self.m_drawingToolsGroup)
        self.m_schematicTool.setCheckable(True)
        self.m_schematicTool.setObjectName(_fromUtf8("m_schematicTool"))
        self.gridLayout.addWidget(self.m_schematicTool, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.m_drawingToolsGroup)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.m_topologicalLabel = QtGui.QLabel(self.groupBox)
        self.m_topologicalLabel.setObjectName(_fromUtf8("m_topologicalLabel"))
        self.horizontalLayout_3.addWidget(self.m_topologicalLabel)
        self.m_topologicalTool = TopoEditToolButton(self.groupBox)
        self.m_topologicalTool.setCheckable(True)
        self.m_topologicalTool.setObjectName(_fromUtf8("m_topologicalTool"))
        self.horizontalLayout_3.addWidget(self.m_topologicalTool)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.m_snapPolygonsLayerTool = SnappingToolButton(self.groupBox)
        self.m_snapPolygonsLayerTool.setCheckable(True)
        self.m_snapPolygonsLayerTool.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.m_snapPolygonsLayerTool.setObjectName(_fromUtf8("m_snapPolygonsLayerTool"))
        self.gridLayout_3.addWidget(self.m_snapPolygonsLayerTool, 3, 3, 1, 1)
        self.m_snapPolygonsBufferTool = SnappingToolButton(self.groupBox)
        self.m_snapPolygonsBufferTool.setCheckable(True)
        self.m_snapPolygonsBufferTool.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.m_snapPolygonsBufferTool.setObjectName(_fromUtf8("m_snapPolygonsBufferTool"))
        self.gridLayout_3.addWidget(self.m_snapPolygonsBufferTool, 2, 3, 1, 1)
        self.m_showPolygonsCheck = QtGui.QCheckBox(self.groupBox)
        self.m_showPolygonsCheck.setText(_fromUtf8(""))
        self.m_showPolygonsCheck.setChecked(True)
        self.m_showPolygonsCheck.setObjectName(_fromUtf8("m_showPolygonsCheck"))
        self.gridLayout_3.addWidget(self.m_showPolygonsCheck, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_showLevelsCheck = QtGui.QCheckBox(self.groupBox)
        self.m_showLevelsCheck.setText(_fromUtf8(""))
        self.m_showLevelsCheck.setChecked(True)
        self.m_showLevelsCheck.setObjectName(_fromUtf8("m_showLevelsCheck"))
        self.gridLayout_3.addWidget(self.m_showLevelsCheck, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.m_showLinesCheck = QtGui.QCheckBox(self.groupBox)
        self.m_showLinesCheck.setText(_fromUtf8(""))
        self.m_showLinesCheck.setChecked(True)
        self.m_showLinesCheck.setObjectName(_fromUtf8("m_showLinesCheck"))
        self.gridLayout_3.addWidget(self.m_showLinesCheck, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.m_snapLinesBufferTool = SnappingToolButton(self.groupBox)
        self.m_snapLinesBufferTool.setCheckable(True)
        self.m_snapLinesBufferTool.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.m_snapLinesBufferTool.setObjectName(_fromUtf8("m_snapLinesBufferTool"))
        self.gridLayout_3.addWidget(self.m_snapLinesBufferTool, 2, 2, 1, 1)
        self.m_snapSchematicsLayerTool = SnappingToolButton(self.groupBox)
        self.m_snapSchematicsLayerTool.setCheckable(True)
        self.m_snapSchematicsLayerTool.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.m_snapSchematicsLayerTool.setObjectName(_fromUtf8("m_snapSchematicsLayerTool"))
        self.gridLayout_3.addWidget(self.m_snapSchematicsLayerTool, 3, 4, 1, 1)
        self.m_snapSchematicsBufferTool = SnappingToolButton(self.groupBox)
        self.m_snapSchematicsBufferTool.setCheckable(True)
        self.m_snapSchematicsBufferTool.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.m_snapSchematicsBufferTool.setObjectName(_fromUtf8("m_snapSchematicsBufferTool"))
        self.gridLayout_3.addWidget(self.m_snapSchematicsBufferTool, 2, 4, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 4, 1, 1)
        self.m_snapLinesLayerTool = SnappingToolButton(self.groupBox)
        self.m_snapLinesLayerTool.setCheckable(True)
        self.m_snapLinesLayerTool.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.m_snapLinesLayerTool.setObjectName(_fromUtf8("m_snapLinesLayerTool"))
        self.gridLayout_3.addWidget(self.m_snapLinesLayerTool, 3, 2, 1, 1)
        self.m_showSchematicsCheck = QtGui.QCheckBox(self.groupBox)
        self.m_showSchematicsCheck.setText(_fromUtf8(""))
        self.m_showSchematicsCheck.setChecked(True)
        self.m_showSchematicsCheck.setObjectName(_fromUtf8("m_showSchematicsCheck"))
        self.gridLayout_3.addWidget(self.m_showSchematicsCheck, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.m_existingContextsGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.m_existingContextsGroup.setObjectName(_fromUtf8("m_existingContextsGroup"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.m_existingContextsGroup)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.m_contextFilterCombo = QtGui.QComboBox(self.m_existingContextsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_contextFilterCombo.sizePolicy().hasHeightForWidth())
        self.m_contextFilterCombo.setSizePolicy(sizePolicy)
        self.m_contextFilterCombo.setEditable(True)
        self.m_contextFilterCombo.setObjectName(_fromUtf8("m_contextFilterCombo"))
        self.horizontalLayout_2.addWidget(self.m_contextFilterCombo)
        self.m_contextFilterButton = QtGui.QPushButton(self.m_existingContextsGroup)
        self.m_contextFilterButton.setObjectName(_fromUtf8("m_contextFilterButton"))
        self.horizontalLayout_2.addWidget(self.m_contextFilterButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.m_existingContextsGroup)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.m_clearButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.m_clearButton.setObjectName(_fromUtf8("m_clearButton"))
        self.horizontalLayout.addWidget(self.m_clearButton)
        self.m_mergeButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.m_mergeButton.setObjectName(_fromUtf8("m_mergeButton"))
        self.horizontalLayout.addWidget(self.m_mergeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(17, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        m_arkPlanDockWidget.setWidget(self.dockWidgetContents)
        self.m_contextLabel.setBuddy(self.m_contextSpin)
        self.m_sourceLabel.setBuddy(self.m_sourceEdit)
        self.m_commentLabel.setBuddy(self.m_commentEdit)

        self.retranslateUi(m_arkPlanDockWidget)
        QtCore.QMetaObject.connectSlotsByName(m_arkPlanDockWidget)

    def retranslateUi(self, m_arkPlanDockWidget):
        m_arkPlanDockWidget.setWindowTitle(_translate("m_arkPlanDockWidget", "ArkPlan", None))
        self.m_loadRawButton.setText(_translate("m_arkPlanDockWidget", "Load Raw", None))
        self.m_loadGeoButton.setText(_translate("m_arkPlanDockWidget", "Load Geo", None))
        self.m_planGroup.setTitle(_translate("m_arkPlanDockWidget", "Attributes", None))
        self.m_siteLabel.setText(_translate("m_arkPlanDockWidget", "Site Code", None))
        self.m_contextLabel.setText(_translate("m_arkPlanDockWidget", "Context:", None))
        self.m_contextSpin.setToolTip(_translate("m_arkPlanDockWidget", "Context Number", None))
        self.m_sourceEdit.setToolTip(_translate("m_arkPlanDockWidget", "Source", None))
        self.m_sourceLabel.setText(_translate("m_arkPlanDockWidget", "Source:", None))
        self.m_commentLabel.setText(_translate("m_arkPlanDockWidget", "Comment", None))
        self.m_drawingToolsGroup.setTitle(_translate("m_arkPlanDockWidget", "Drawing Tools", None))
        self.m_extentTool.setToolTip(_translate("m_arkPlanDockWidget", "Extent of context", None))
        self.m_extentTool.setText(_translate("m_arkPlanDockWidget", "ext", None))
        self.m_verticalEdgeTool.setToolTip(_translate("m_arkPlanDockWidget", "Vertical Edge", None))
        self.m_verticalEdgeTool.setText(_translate("m_arkPlanDockWidget", "veg", None))
        self.m_uncertainEdgeTool.setToolTip(_translate("m_arkPlanDockWidget", "Uncertain Edge", None))
        self.m_uncertainEdgeTool.setText(_translate("m_arkPlanDockWidget", "ueg", None))
        self.m_limitOfExcavationTool.setToolTip(_translate("m_arkPlanDockWidget", "Limit of Excavation", None))
        self.m_limitOfExcavationTool.setText(_translate("m_arkPlanDockWidget", "loe", None))
        self.m_verticalTruncationTool.setToolTip(_translate("m_arkPlanDockWidget", "Vertical Truncation", None))
        self.m_verticalTruncationTool.setText(_translate("m_arkPlanDockWidget", "vtr", None))
        self.m_truncationTool.setToolTip(_translate("m_arkPlanDockWidget", "Truncation", None))
        self.m_truncationTool.setText(_translate("m_arkPlanDockWidget", "trn", None))
        self.m_breakOfSlopeTool.setToolTip(_translate("m_arkPlanDockWidget", "Break of Slope", None))
        self.m_breakOfSlopeTool.setText(_translate("m_arkPlanDockWidget", "bos", None))
        self.m_verticalBreakOfSlopeTool.setToolTip(_translate("m_arkPlanDockWidget", "Vertical Break of Slope", None))
        self.m_verticalBreakOfSlopeTool.setText(_translate("m_arkPlanDockWidget", "vbs", None))
        self.m_hachureTool.setToolTip(_translate("m_arkPlanDockWidget", "Hachure", None))
        self.m_hachureTool.setText(_translate("m_arkPlanDockWidget", "hch", None))
        self.m_undercutTool.setToolTip(_translate("m_arkPlanDockWidget", "Undercut", None))
        self.m_undercutTool.setText(_translate("m_arkPlanDockWidget", "unc", None))
        self.m_returnOfSlopeTool.setToolTip(_translate("m_arkPlanDockWidget", "Return of Slope", None))
        self.m_returnOfSlopeTool.setText(_translate("m_arkPlanDockWidget", "ros", None))
        self.m_cbmTool.setToolTip(_translate("m_arkPlanDockWidget", "CBM", None))
        self.m_cbmTool.setText(_translate("m_arkPlanDockWidget", "cbm", None))
        self.m_brickTool.setToolTip(_translate("m_arkPlanDockWidget", "Brick", None))
        self.m_brickTool.setText(_translate("m_arkPlanDockWidget", "brk", None))
        self.m_tileTool.setToolTip(_translate("m_arkPlanDockWidget", "Tile", None))
        self.m_tileTool.setText(_translate("m_arkPlanDockWidget", "til", None))
        self.m_mortarTool.setToolTip(_translate("m_arkPlanDockWidget", "Mortar", None))
        self.m_mortarTool.setText(_translate("m_arkPlanDockWidget", "mtr", None))
        self.m_charcoalTool.setToolTip(_translate("m_arkPlanDockWidget", "Charcoal", None))
        self.m_charcoalTool.setText(_translate("m_arkPlanDockWidget", "cha", None))
        self.m_stoneTool.setToolTip(_translate("m_arkPlanDockWidget", "Stone", None))
        self.m_stoneTool.setText(_translate("m_arkPlanDockWidget", "sto", None))
        self.m_potTool.setToolTip(_translate("m_arkPlanDockWidget", "Pot", None))
        self.m_potTool.setText(_translate("m_arkPlanDockWidget", "pot", None))
        self.m_flintTool.setToolTip(_translate("m_arkPlanDockWidget", "Flint", None))
        self.m_flintTool.setText(_translate("m_arkPlanDockWidget", "fli", None))
        self.m_levelTool.setToolTip(_translate("m_arkPlanDockWidget", "Level", None))
        self.m_levelTool.setText(_translate("m_arkPlanDockWidget", "lvl", None))
        self.m_schematicTool.setToolTip(_translate("m_arkPlanDockWidget", "Schematic", None))
        self.m_schematicTool.setText(_translate("m_arkPlanDockWidget", "sch", None))
        self.groupBox.setTitle(_translate("m_arkPlanDockWidget", "Editing:", None))
        self.m_topologicalLabel.setText(_translate("m_arkPlanDockWidget", "Topological:", None))
        self.m_topologicalTool.setText(_translate("m_arkPlanDockWidget", "topo", None))
        self.label_2.setText(_translate("m_arkPlanDockWidget", "Snap Layers:", None))
        self.label_11.setText(_translate("m_arkPlanDockWidget", "Lines", None))
        self.label_4.setText(_translate("m_arkPlanDockWidget", "Layers Visible:", None))
        self.label_12.setText(_translate("m_arkPlanDockWidget", "Polys", None))
        self.label.setText(_translate("m_arkPlanDockWidget", "Snap Buffers:", None))
        self.m_snapPolygonsLayerTool.setText(_translate("m_arkPlanDockWidget", "...", None))
        self.m_snapPolygonsBufferTool.setText(_translate("m_arkPlanDockWidget", "...", None))
        self.m_showPolygonsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing polygons", None))
        self.m_showLevelsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing levels", None))
        self.label_8.setText(_translate("m_arkPlanDockWidget", "Levels", None))
        self.m_showLinesCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing lines", None))
        self.m_snapLinesBufferTool.setText(_translate("m_arkPlanDockWidget", "...", None))
        self.m_snapSchematicsLayerTool.setText(_translate("m_arkPlanDockWidget", "...", None))
        self.m_snapSchematicsBufferTool.setText(_translate("m_arkPlanDockWidget", "...", None))
        self.label_13.setText(_translate("m_arkPlanDockWidget", "Schms", None))
        self.m_snapLinesLayerTool.setText(_translate("m_arkPlanDockWidget", "...", None))
        self.m_showSchematicsCheck.setToolTip(_translate("m_arkPlanDockWidget", "Show existing schematics", None))
        self.m_existingContextsGroup.setTitle(_translate("m_arkPlanDockWidget", "Filter:", None))
        self.m_contextFilterButton.setText(_translate("m_arkPlanDockWidget", "Apply", None))
        self.m_clearButton.setToolTip(_translate("m_arkPlanDockWidget", "Clear unsaved changes from work layers", None))
        self.m_clearButton.setText(_translate("m_arkPlanDockWidget", "Clear", None))
        self.m_mergeButton.setToolTip(_translate("m_arkPlanDockWidget", "Move new context to main layers", None))
        self.m_mergeButton.setText(_translate("m_arkPlanDockWidget", "Merge", None))

from snapping_widgets import SnappingToolButton, TopoEditToolButton
