# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ark/georef/georef_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GeorefDialogBase(object):
    def setupUi(self, GeorefDialogBase):
        GeorefDialogBase.setObjectName(_fromUtf8("GeorefDialogBase"))
        GeorefDialogBase.resize(1300, 1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeorefDialogBase.sizePolicy().hasHeightForWidth())
        GeorefDialogBase.setSizePolicy(sizePolicy)
        GeorefDialogBase.setMinimumSize(QtCore.QSize(1300, 1000))
        GeorefDialogBase.setMaximumSize(QtCore.QSize(1300, 1000))
        self.verticalLayout = QtGui.QVBoxLayout(GeorefDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(GeorefDialogBase)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.planView = OverviewGraphicsView(self.layoutWidget)
        self.planView.setMinimumSize(QtCore.QSize(300, 320))
        self.planView.setMaximumSize(QtCore.QSize(300, 320))
        self.planView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.planView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.planView.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.planView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.planView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.planView.setObjectName(_fromUtf8("planView"))
        self.verticalLayout_4.addWidget(self.planView, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.inputFileLabel = QtGui.QLabel(self.layoutWidget)
        self.inputFileLabel.setObjectName(_fromUtf8("inputFileLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.inputFileLabel)
        self.siteLabel = QtGui.QLabel(self.layoutWidget)
        self.siteLabel.setObjectName(_fromUtf8("siteLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.siteLabel)
        self.siteEdit = QtGui.QLineEdit(self.layoutWidget)
        self.siteEdit.setReadOnly(False)
        self.siteEdit.setObjectName(_fromUtf8("siteEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.siteEdit)
        self.typeLabel = QtGui.QLabel(self.layoutWidget)
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.typeLabel)
        self.typeCombo = QtGui.QComboBox(self.layoutWidget)
        self.typeCombo.setEditable(False)
        self.typeCombo.setObjectName(_fromUtf8("typeCombo"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.typeCombo)
        self.contextLabel = QtGui.QLabel(self.layoutWidget)
        self.contextLabel.setObjectName(_fromUtf8("contextLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.contextLabel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.numberSpin = QtGui.QSpinBox(self.layoutWidget)
        self.numberSpin.setReadOnly(False)
        self.numberSpin.setMaximum(9999)
        self.numberSpin.setObjectName(_fromUtf8("numberSpin"))
        self.horizontalLayout_4.addWidget(self.numberSpin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.gridLabel = QtGui.QLabel(self.layoutWidget)
        self.gridLabel.setObjectName(_fromUtf8("gridLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.gridLabel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.eastSpin = QtGui.QSpinBox(self.layoutWidget)
        self.eastSpin.setReadOnly(False)
        self.eastSpin.setMaximum(9999)
        self.eastSpin.setSingleStep(5)
        self.eastSpin.setObjectName(_fromUtf8("eastSpin"))
        self.horizontalLayout_6.addWidget(self.eastSpin)
        self.northSpin = QtGui.QSpinBox(self.layoutWidget)
        self.northSpin.setReadOnly(False)
        self.northSpin.setMaximum(9999)
        self.northSpin.setSingleStep(5)
        self.northSpin.setObjectName(_fromUtf8("northSpin"))
        self.horizontalLayout_6.addWidget(self.northSpin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.suffixLabel = QtGui.QLabel(self.layoutWidget)
        self.suffixLabel.setObjectName(_fromUtf8("suffixLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.suffixLabel)
        self.suffixEdit = QtGui.QLineEdit(self.layoutWidget)
        self.suffixEdit.setMaxLength(1)
        self.suffixEdit.setObjectName(_fromUtf8("suffixEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.suffixEdit)
        self.scaleLabel = QtGui.QLabel(self.layoutWidget)
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.scaleLabel)
        self.scaleCombo = QtGui.QComboBox(self.layoutWidget)
        self.scaleCombo.setObjectName(_fromUtf8("scaleCombo"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.scaleCombo)
        self.addToMapCheck = QtGui.QCheckBox(self.layoutWidget)
        self.addToMapCheck.setText(_fromUtf8(""))
        self.addToMapCheck.setChecked(True)
        self.addToMapCheck.setObjectName(_fromUtf8("addToMapCheck"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.addToMapCheck)
        self.cropCheck = QtGui.QCheckBox(self.layoutWidget)
        self.cropCheck.setText(_fromUtf8(""))
        self.cropCheck.setChecked(True)
        self.cropCheck.setObjectName(_fromUtf8("cropCheck"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.cropCheck)
        self.cropLabel = QtGui.QLabel(self.layoutWidget)
        self.cropLabel.setObjectName(_fromUtf8("cropLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.cropLabel)
        self.addToMapLabel = QtGui.QLabel(self.layoutWidget)
        self.addToMapLabel.setObjectName(_fromUtf8("addToMapLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.addToMapLabel)
        self.rawFileLabel = QtGui.QLabel(self.layoutWidget)
        self.rawFileLabel.setObjectName(_fromUtf8("rawFileLabel"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.rawFileLabel)
        self.geoFileLabel = QtGui.QLabel(self.layoutWidget)
        self.geoFileLabel.setObjectName(_fromUtf8("geoFileLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.geoFileLabel)
        self.inputFileName = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFileName.sizePolicy().hasHeightForWidth())
        self.inputFileName.setSizePolicy(sizePolicy)
        self.inputFileName.setMinimumSize(QtCore.QSize(0, 21))
        self.inputFileName.setFrameShape(QtGui.QFrame.Panel)
        self.inputFileName.setFrameShadow(QtGui.QFrame.Sunken)
        self.inputFileName.setText(_fromUtf8(""))
        self.inputFileName.setObjectName(_fromUtf8("inputFileName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.inputFileName)
        self.rawFileName = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawFileName.sizePolicy().hasHeightForWidth())
        self.rawFileName.setSizePolicy(sizePolicy)
        self.rawFileName.setMinimumSize(QtCore.QSize(0, 21))
        self.rawFileName.setFrameShape(QtGui.QFrame.Panel)
        self.rawFileName.setFrameShadow(QtGui.QFrame.Sunken)
        self.rawFileName.setText(_fromUtf8(""))
        self.rawFileName.setObjectName(_fromUtf8("rawFileName"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.rawFileName)
        self.geoFileName = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geoFileName.sizePolicy().hasHeightForWidth())
        self.geoFileName.setSizePolicy(sizePolicy)
        self.geoFileName.setMinimumSize(QtCore.QSize(0, 21))
        self.geoFileName.setFrameShape(QtGui.QFrame.Panel)
        self.geoFileName.setFrameShadow(QtGui.QFrame.Sunken)
        self.geoFileName.setText(_fromUtf8(""))
        self.geoFileName.setObjectName(_fromUtf8("geoFileName"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.geoFileName)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.processButton = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.processButton.setFont(font)
        self.processButton.setDefault(True)
        self.processButton.setObjectName(_fromUtf8("processButton"))
        self.gridLayout_2.addWidget(self.processButton, 0, 0, 1, 3)
        self.saveButton = QtGui.QPushButton(self.layoutWidget)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout_2.addWidget(self.saveButton, 1, 0, 1, 1)
        self.closeButton = QtGui.QPushButton(self.layoutWidget)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.gridLayout_2.addWidget(self.closeButton, 1, 2, 1, 1)
        self.runButton = QtGui.QPushButton(self.layoutWidget)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.gridLayout_2.addWidget(self.runButton, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 1, 1, 1)
        self.translateStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.translateStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.translateStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.translateStatusLabel.setText(_fromUtf8(""))
        self.translateStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.translateStatusLabel.setObjectName(_fromUtf8("translateStatusLabel"))
        self.gridLayout_3.addWidget(self.translateStatusLabel, 2, 0, 1, 1)
        self.cropStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.cropStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.cropStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.cropStatusLabel.setText(_fromUtf8(""))
        self.cropStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.cropStatusLabel.setObjectName(_fromUtf8("cropStatusLabel"))
        self.gridLayout_3.addWidget(self.cropStatusLabel, 1, 0, 1, 1)
        self.warpStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.warpStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.warpStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.warpStatusLabel.setText(_fromUtf8(""))
        self.warpStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.warpStatusLabel.setObjectName(_fromUtf8("warpStatusLabel"))
        self.gridLayout_3.addWidget(self.warpStatusLabel, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1)
        self.loadStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.loadStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.loadStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.loadStatusLabel.setText(_fromUtf8(""))
        self.loadStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.loadStatusLabel.setObjectName(_fromUtf8("loadStatusLabel"))
        self.gridLayout_3.addWidget(self.loadStatusLabel, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 4, 1, 1, 1)
        self.overviewStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.overviewStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.overviewStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.overviewStatusLabel.setText(_fromUtf8(""))
        self.overviewStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.overviewStatusLabel.setObjectName(_fromUtf8("overviewStatusLabel"))
        self.gridLayout_3.addWidget(self.overviewStatusLabel, 4, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.statusBar = QtGui.QStatusBar(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout_4.addWidget(self.statusBar)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.headerView = FixedGraphicsView(self.layoutWidget1)
        self.headerView.setMinimumSize(QtCore.QSize(900, 50))
        self.headerView.setMaximumSize(QtCore.QSize(16777215, 50))
        self.headerView.setAcceptDrops(False)
        self.headerView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.headerView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.headerView.setInteractive(False)
        self.headerView.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.headerView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.headerView.setObjectName(_fromUtf8("headerView"))
        self.gridLayout.addWidget(self.headerView, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gcpWidget1 = GcpWidget(self.layoutWidget1)
        self.gcpWidget1.setObjectName(_fromUtf8("gcpWidget1"))
        self.gridLayout.addWidget(self.gcpWidget1, 1, 0, 1, 1)
        self.gcpWidget4 = GcpWidget(self.layoutWidget1)
        self.gcpWidget4.setObjectName(_fromUtf8("gcpWidget4"))
        self.gridLayout.addWidget(self.gcpWidget4, 1, 1, 1, 1)
        self.gcpWidget2 = GcpWidget(self.layoutWidget1)
        self.gcpWidget2.setObjectName(_fromUtf8("gcpWidget2"))
        self.gridLayout.addWidget(self.gcpWidget2, 2, 0, 1, 1)
        self.gcpWidget3 = GcpWidget(self.layoutWidget1)
        self.gcpWidget3.setObjectName(_fromUtf8("gcpWidget3"))
        self.gridLayout.addWidget(self.gcpWidget3, 2, 1, 1, 1)
        self.footerView = FixedGraphicsView(self.layoutWidget1)
        self.footerView.setMinimumSize(QtCore.QSize(900, 150))
        self.footerView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.footerView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.footerView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.footerView.setInteractive(False)
        self.footerView.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.footerView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.footerView.setObjectName(_fromUtf8("footerView"))
        self.gridLayout.addWidget(self.footerView, 3, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.splitter)
        self.siteLabel.setBuddy(self.siteEdit)
        self.typeLabel.setBuddy(self.typeCombo)
        self.contextLabel.setBuddy(self.numberSpin)
        self.gridLabel.setBuddy(self.eastSpin)
        self.suffixLabel.setBuddy(self.suffixEdit)
        self.scaleLabel.setBuddy(self.scaleCombo)

        self.retranslateUi(GeorefDialogBase)
        QtCore.QMetaObject.connectSlotsByName(GeorefDialogBase)
        GeorefDialogBase.setTabOrder(self.planView, self.siteEdit)
        GeorefDialogBase.setTabOrder(self.siteEdit, self.typeCombo)
        GeorefDialogBase.setTabOrder(self.typeCombo, self.scaleCombo)
        GeorefDialogBase.setTabOrder(self.scaleCombo, self.numberSpin)
        GeorefDialogBase.setTabOrder(self.numberSpin, self.eastSpin)
        GeorefDialogBase.setTabOrder(self.eastSpin, self.northSpin)
        GeorefDialogBase.setTabOrder(self.northSpin, self.suffixEdit)
        GeorefDialogBase.setTabOrder(self.suffixEdit, self.cropCheck)
        GeorefDialogBase.setTabOrder(self.cropCheck, self.addToMapCheck)
        GeorefDialogBase.setTabOrder(self.addToMapCheck, self.processButton)
        GeorefDialogBase.setTabOrder(self.processButton, self.saveButton)
        GeorefDialogBase.setTabOrder(self.saveButton, self.runButton)
        GeorefDialogBase.setTabOrder(self.runButton, self.closeButton)
        GeorefDialogBase.setTabOrder(self.closeButton, self.headerView)
        GeorefDialogBase.setTabOrder(self.headerView, self.footerView)

    def retranslateUi(self, GeorefDialogBase):
        GeorefDialogBase.setWindowTitle(_translate("GeorefDialogBase", "Grid Georeferencer", None))
        self.inputFileLabel.setText(_translate("GeorefDialogBase", "Input File:", None))
        self.siteLabel.setText(_translate("GeorefDialogBase", "Site:", None))
        self.typeLabel.setText(_translate("GeorefDialogBase", "Type:", None))
        self.contextLabel.setText(_translate("GeorefDialogBase", "Number:", None))
        self.numberSpin.setToolTip(_translate("GeorefDialogBase", "Context Number", None))
        self.gridLabel.setText(_translate("GeorefDialogBase", "Grid:", None))
        self.suffixLabel.setText(_translate("GeorefDialogBase", "Suffix:", None))
        self.scaleLabel.setText(_translate("GeorefDialogBase", "Scale:", None))
        self.cropLabel.setText(_translate("GeorefDialogBase", "Crop:", None))
        self.addToMapLabel.setText(_translate("GeorefDialogBase", "Add to Map:", None))
        self.rawFileLabel.setText(_translate("GeorefDialogBase", "Raw File:", None))
        self.geoFileLabel.setText(_translate("GeorefDialogBase", "Geo File:", None))
        self.processButton.setText(_translate("GeorefDialogBase", "Process", None))
        self.saveButton.setText(_translate("GeorefDialogBase", "Save", None))
        self.closeButton.setText(_translate("GeorefDialogBase", "Close", None))
        self.runButton.setText(_translate("GeorefDialogBase", "Run", None))
        self.label_5.setText(_translate("GeorefDialogBase", "Warp Image", None))
        self.label_2.setText(_translate("GeorefDialogBase", "Crop Raw Image", None))
        self.label_4.setText(_translate("GeorefDialogBase", "Translate Raw Image", None))
        self.label_3.setText(_translate("GeorefDialogBase", "Load Raw Image", None))
        self.label_6.setText(_translate("GeorefDialogBase", "Generate Image Overviews", None))

from ArkSpatial.ark.lib.gui.fixed_graphics_view import FixedGraphicsView
from ArkSpatial.ark.lib.gui.overview_graphics_view import OverviewGraphicsView
from gcp_widget import GcpWidget
import resources_rc
