# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/settings_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogBase(object):
    def setupUi(self, SettingsDialogBase):
        SettingsDialogBase.setObjectName(_fromUtf8("SettingsDialogBase"))
        SettingsDialogBase.resize(536, 427)
        self.verticalLayout = QtGui.QVBoxLayout(SettingsDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.multiSiteLabel = QtGui.QLabel(self.projectTab)
        self.multiSiteLabel.setObjectName(_fromUtf8("multiSiteLabel"))
        self.gridLayout_5.addWidget(self.multiSiteLabel, 1, 0, 1, 1)
        self.prependSiteCodeCheck = QtGui.QCheckBox(self.projectTab)
        self.prependSiteCodeCheck.setText(_fromUtf8(""))
        self.prependSiteCodeCheck.setChecked(True)
        self.prependSiteCodeCheck.setObjectName(_fromUtf8("prependSiteCodeCheck"))
        self.gridLayout_5.addWidget(self.prependSiteCodeCheck, 3, 2, 1, 1)
        self.projectFolderLabel = QtGui.QLabel(self.projectTab)
        self.projectFolderLabel.setObjectName(_fromUtf8("projectFolderLabel"))
        self.gridLayout_5.addWidget(self.projectFolderLabel, 0, 0, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(self.projectTab)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.gridLayout_5.addWidget(self.siteCodeLabel, 2, 0, 1, 1)
        self.defaultStylesCheck = QtGui.QCheckBox(self.projectTab)
        self.defaultStylesCheck.setText(_fromUtf8(""))
        self.defaultStylesCheck.setChecked(True)
        self.defaultStylesCheck.setObjectName(_fromUtf8("defaultStylesCheck"))
        self.gridLayout_5.addWidget(self.defaultStylesCheck, 4, 2, 1, 1)
        self.styleFolderLayout = QtGui.QHBoxLayout()
        self.styleFolderLayout.setObjectName(_fromUtf8("styleFolderLayout"))
        self.styleFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.styleFolderEdit.setEnabled(False)
        self.styleFolderEdit.setObjectName(_fromUtf8("styleFolderEdit"))
        self.styleFolderLayout.addWidget(self.styleFolderEdit)
        self.styleFolderButton = QtGui.QPushButton(self.projectTab)
        self.styleFolderButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleFolderButton.sizePolicy().hasHeightForWidth())
        self.styleFolderButton.setSizePolicy(sizePolicy)
        self.styleFolderButton.setObjectName(_fromUtf8("styleFolderButton"))
        self.styleFolderLayout.addWidget(self.styleFolderButton)
        self.gridLayout_5.addLayout(self.styleFolderLayout, 5, 2, 1, 1)
        self.siteCodeEdit = QtGui.QLineEdit(self.projectTab)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.gridLayout_5.addWidget(self.siteCodeEdit, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 7, 2, 1, 1)
        self.customStylesLabel = QtGui.QLabel(self.projectTab)
        self.customStylesLabel.setObjectName(_fromUtf8("customStylesLabel"))
        self.gridLayout_5.addWidget(self.customStylesLabel, 5, 0, 1, 2)
        self.defaultStylesLabel = QtGui.QLabel(self.projectTab)
        self.defaultStylesLabel.setObjectName(_fromUtf8("defaultStylesLabel"))
        self.gridLayout_5.addWidget(self.defaultStylesLabel, 4, 0, 1, 2)
        self.prependSiteCodeLabel = QtGui.QLabel(self.projectTab)
        self.prependSiteCodeLabel.setObjectName(_fromUtf8("prependSiteCodeLabel"))
        self.gridLayout_5.addWidget(self.prependSiteCodeLabel, 3, 0, 1, 1)
        self.projectFolderLayout = QtGui.QHBoxLayout()
        self.projectFolderLayout.setObjectName(_fromUtf8("projectFolderLayout"))
        self.projectFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.projectFolderEdit.setObjectName(_fromUtf8("projectFolderEdit"))
        self.projectFolderLayout.addWidget(self.projectFolderEdit)
        self.projectFolderButton = QtGui.QPushButton(self.projectTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectFolderButton.sizePolicy().hasHeightForWidth())
        self.projectFolderButton.setSizePolicy(sizePolicy)
        self.projectFolderButton.setObjectName(_fromUtf8("projectFolderButton"))
        self.projectFolderLayout.addWidget(self.projectFolderButton)
        self.gridLayout_5.addLayout(self.projectFolderLayout, 0, 2, 1, 1)
        self.multiSiteCheck = QtGui.QCheckBox(self.projectTab)
        self.multiSiteCheck.setText(_fromUtf8(""))
        self.multiSiteCheck.setObjectName(_fromUtf8("multiSiteCheck"))
        self.gridLayout_5.addWidget(self.multiSiteCheck, 1, 2, 1, 1)
        self.useArkLabel = QtGui.QLabel(self.projectTab)
        self.useArkLabel.setObjectName(_fromUtf8("useArkLabel"))
        self.gridLayout_5.addWidget(self.useArkLabel, 6, 0, 1, 1)
        self.useArkCheck = QtGui.QCheckBox(self.projectTab)
        self.useArkCheck.setText(_fromUtf8(""))
        self.useArkCheck.setObjectName(_fromUtf8("useArkCheck"))
        self.gridLayout_5.addWidget(self.useArkCheck, 6, 2, 1, 1)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.gridTab = QtGui.QWidget()
        self.gridTab.setObjectName(_fromUtf8("gridTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridFolderLayout = QtGui.QHBoxLayout()
        self.gridFolderLayout.setObjectName(_fromUtf8("gridFolderLayout"))
        self.gridFolderEdit = QtGui.QLineEdit(self.gridTab)
        self.gridFolderEdit.setObjectName(_fromUtf8("gridFolderEdit"))
        self.gridFolderLayout.addWidget(self.gridFolderEdit)
        self.gridFolderButton = QtGui.QPushButton(self.gridTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFolderButton.sizePolicy().hasHeightForWidth())
        self.gridFolderButton.setSizePolicy(sizePolicy)
        self.gridFolderButton.setObjectName(_fromUtf8("gridFolderButton"))
        self.gridFolderLayout.addWidget(self.gridFolderButton)
        self.gridLayout_4.addLayout(self.gridFolderLayout, 0, 1, 1, 1)
        self.gridFolderLabel = QtGui.QLabel(self.gridTab)
        self.gridFolderLabel.setObjectName(_fromUtf8("gridFolderLabel"))
        self.gridLayout_4.addWidget(self.gridFolderLabel, 0, 0, 1, 1)
        self.gridPolygonsNameLabel = QtGui.QLabel(self.gridTab)
        self.gridPolygonsNameLabel.setObjectName(_fromUtf8("gridPolygonsNameLabel"))
        self.gridLayout_4.addWidget(self.gridPolygonsNameLabel, 4, 0, 1, 1)
        self.gridPointsNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridPointsNameEdit.setObjectName(_fromUtf8("gridPointsNameEdit"))
        self.gridLayout_4.addWidget(self.gridPointsNameEdit, 2, 1, 1, 1)
        self.gridLinesNameLabel = QtGui.QLabel(self.gridTab)
        self.gridLinesNameLabel.setObjectName(_fromUtf8("gridLinesNameLabel"))
        self.gridLayout_4.addWidget(self.gridLinesNameLabel, 3, 0, 1, 1)
        self.gridPolygonsNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridPolygonsNameEdit.setObjectName(_fromUtf8("gridPolygonsNameEdit"))
        self.gridLayout_4.addWidget(self.gridPolygonsNameEdit, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 5, 1, 1, 1)
        self.gridLinesNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridLinesNameEdit.setObjectName(_fromUtf8("gridLinesNameEdit"))
        self.gridLayout_4.addWidget(self.gridLinesNameEdit, 3, 1, 1, 1)
        self.gridPointNameLabel = QtGui.QLabel(self.gridTab)
        self.gridPointNameLabel.setObjectName(_fromUtf8("gridPointNameLabel"))
        self.gridLayout_4.addWidget(self.gridPointNameLabel, 2, 0, 1, 1)
        self.gridGroupNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridGroupNameEdit.setObjectName(_fromUtf8("gridGroupNameEdit"))
        self.gridLayout_4.addWidget(self.gridGroupNameEdit, 1, 1, 1, 1)
        self.gridGroupNameLabel = QtGui.QLabel(self.gridTab)
        self.gridGroupNameLabel.setObjectName(_fromUtf8("gridGroupNameLabel"))
        self.gridLayout_4.addWidget(self.gridGroupNameLabel, 1, 0, 1, 1)
        self.tabWidget.addTab(self.gridTab, _fromUtf8(""))
        self.baseTab = QtGui.QWidget()
        self.baseTab.setObjectName(_fromUtf8("baseTab"))
        self.gridLayout = QtGui.QGridLayout(self.baseTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.baseGroupNameEdit = QtGui.QLineEdit(self.baseTab)
        self.baseGroupNameEdit.setObjectName(_fromUtf8("baseGroupNameEdit"))
        self.gridLayout.addWidget(self.baseGroupNameEdit, 1, 1, 1, 2)
        self.baseFolderLabel = QtGui.QLabel(self.baseTab)
        self.baseFolderLabel.setObjectName(_fromUtf8("baseFolderLabel"))
        self.gridLayout.addWidget(self.baseFolderLabel, 0, 0, 1, 1)
        self.basePointsNameEdit = QtGui.QLineEdit(self.baseTab)
        self.basePointsNameEdit.setObjectName(_fromUtf8("basePointsNameEdit"))
        self.gridLayout.addWidget(self.basePointsNameEdit, 2, 1, 1, 2)
        self.baseFolderLayout = QtGui.QHBoxLayout()
        self.baseFolderLayout.setObjectName(_fromUtf8("baseFolderLayout"))
        self.baseFolderEdit = QtGui.QLineEdit(self.baseTab)
        self.baseFolderEdit.setObjectName(_fromUtf8("baseFolderEdit"))
        self.baseFolderLayout.addWidget(self.baseFolderEdit)
        self.baseFolderButton = QtGui.QPushButton(self.baseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseFolderButton.sizePolicy().hasHeightForWidth())
        self.baseFolderButton.setSizePolicy(sizePolicy)
        self.baseFolderButton.setObjectName(_fromUtf8("baseFolderButton"))
        self.baseFolderLayout.addWidget(self.baseFolderButton)
        self.gridLayout.addLayout(self.baseFolderLayout, 0, 1, 1, 2)
        self.basePointsNameLabel = QtGui.QLabel(self.baseTab)
        self.basePointsNameLabel.setObjectName(_fromUtf8("basePointsNameLabel"))
        self.gridLayout.addWidget(self.basePointsNameLabel, 2, 0, 1, 1)
        self.baseGroupNameLabel = QtGui.QLabel(self.baseTab)
        self.baseGroupNameLabel.setObjectName(_fromUtf8("baseGroupNameLabel"))
        self.gridLayout.addWidget(self.baseGroupNameLabel, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 99, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.baseLinesNameEdit = QtGui.QLineEdit(self.baseTab)
        self.baseLinesNameEdit.setObjectName(_fromUtf8("baseLinesNameEdit"))
        self.gridLayout.addWidget(self.baseLinesNameEdit, 3, 1, 1, 2)
        self.baseLinesNameLabel = QtGui.QLabel(self.baseTab)
        self.baseLinesNameLabel.setObjectName(_fromUtf8("baseLinesNameLabel"))
        self.gridLayout.addWidget(self.baseLinesNameLabel, 3, 0, 1, 1)
        self.basePolygonsNameLabel = QtGui.QLabel(self.baseTab)
        self.basePolygonsNameLabel.setObjectName(_fromUtf8("basePolygonsNameLabel"))
        self.gridLayout.addWidget(self.basePolygonsNameLabel, 4, 0, 1, 1)
        self.basePolygonsNameEdit = QtGui.QLineEdit(self.baseTab)
        self.basePolygonsNameEdit.setObjectName(_fromUtf8("basePolygonsNameEdit"))
        self.gridLayout.addWidget(self.basePolygonsNameEdit, 4, 1, 1, 2)
        self.tabWidget.addTab(self.baseTab, _fromUtf8(""))
        self.planTab = QtGui.QWidget()
        self.planTab.setObjectName(_fromUtf8("planTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.planTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 15, 1, 1, 1)
        self.planLinesNameEdit = QtGui.QLineEdit(self.planTab)
        self.planLinesNameEdit.setObjectName(_fromUtf8("planLinesNameEdit"))
        self.gridLayout_6.addWidget(self.planLinesNameEdit, 5, 1, 1, 1)
        self.planPointNameLabel = QtGui.QLabel(self.planTab)
        self.planPointNameLabel.setObjectName(_fromUtf8("planPointNameLabel"))
        self.gridLayout_6.addWidget(self.planPointNameLabel, 4, 0, 1, 1)
        self.planTransparencyLabel = QtGui.QLabel(self.planTab)
        self.planTransparencyLabel.setObjectName(_fromUtf8("planTransparencyLabel"))
        self.gridLayout_6.addWidget(self.planTransparencyLabel, 9, 0, 1, 1)
        self.planVectorFolderLabel = QtGui.QLabel(self.planTab)
        self.planVectorFolderLabel.setObjectName(_fromUtf8("planVectorFolderLabel"))
        self.gridLayout_6.addWidget(self.planVectorFolderLabel, 0, 0, 1, 1)
        self.planBufferGroupNameLabel = QtGui.QLabel(self.planTab)
        self.planBufferGroupNameLabel.setObjectName(_fromUtf8("planBufferGroupNameLabel"))
        self.gridLayout_6.addWidget(self.planBufferGroupNameLabel, 3, 0, 1, 1)
        self.planRasterFolderLabel = QtGui.QLabel(self.planTab)
        self.planRasterFolderLabel.setObjectName(_fromUtf8("planRasterFolderLabel"))
        self.gridLayout_6.addWidget(self.planRasterFolderLabel, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.planRasterFolderEdit = QtGui.QLineEdit(self.planTab)
        self.planRasterFolderEdit.setObjectName(_fromUtf8("planRasterFolderEdit"))
        self.horizontalLayout_2.addWidget(self.planRasterFolderEdit)
        self.planRasterFolderButton = QtGui.QPushButton(self.planTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.planRasterFolderButton.sizePolicy().hasHeightForWidth())
        self.planRasterFolderButton.setSizePolicy(sizePolicy)
        self.planRasterFolderButton.setObjectName(_fromUtf8("planRasterFolderButton"))
        self.horizontalLayout_2.addWidget(self.planRasterFolderButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 7, 1, 1, 1)
        self.planPolygonsNameLabel = QtGui.QLabel(self.planTab)
        self.planPolygonsNameLabel.setObjectName(_fromUtf8("planPolygonsNameLabel"))
        self.gridLayout_6.addWidget(self.planPolygonsNameLabel, 6, 0, 1, 1)
        self.planPointsNameEdit = QtGui.QLineEdit(self.planTab)
        self.planPointsNameEdit.setObjectName(_fromUtf8("planPointsNameEdit"))
        self.gridLayout_6.addWidget(self.planPointsNameEdit, 4, 1, 1, 1)
        self.planBufferGroupNameEdit = QtGui.QLineEdit(self.planTab)
        self.planBufferGroupNameEdit.setObjectName(_fromUtf8("planBufferGroupNameEdit"))
        self.gridLayout_6.addWidget(self.planBufferGroupNameEdit, 3, 1, 1, 1)
        self.planPolygonsNameEdit = QtGui.QLineEdit(self.planTab)
        self.planPolygonsNameEdit.setObjectName(_fromUtf8("planPolygonsNameEdit"))
        self.gridLayout_6.addWidget(self.planPolygonsNameEdit, 6, 1, 1, 1)
        self.planLinesNameLabel = QtGui.QLabel(self.planTab)
        self.planLinesNameLabel.setObjectName(_fromUtf8("planLinesNameLabel"))
        self.gridLayout_6.addWidget(self.planLinesNameLabel, 5, 0, 1, 1)
        self.planGroupNameEdit = QtGui.QLineEdit(self.planTab)
        self.planGroupNameEdit.setObjectName(_fromUtf8("planGroupNameEdit"))
        self.gridLayout_6.addWidget(self.planGroupNameEdit, 1, 1, 1, 1)
        self.planVectorFolderLayout = QtGui.QHBoxLayout()
        self.planVectorFolderLayout.setObjectName(_fromUtf8("planVectorFolderLayout"))
        self.planVectorFolderEdit = QtGui.QLineEdit(self.planTab)
        self.planVectorFolderEdit.setObjectName(_fromUtf8("planVectorFolderEdit"))
        self.planVectorFolderLayout.addWidget(self.planVectorFolderEdit)
        self.planVectorFolderButton = QtGui.QPushButton(self.planTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.planVectorFolderButton.sizePolicy().hasHeightForWidth())
        self.planVectorFolderButton.setSizePolicy(sizePolicy)
        self.planVectorFolderButton.setObjectName(_fromUtf8("planVectorFolderButton"))
        self.planVectorFolderLayout.addWidget(self.planVectorFolderButton)
        self.gridLayout_6.addLayout(self.planVectorFolderLayout, 0, 1, 1, 1)
        self.planGroupNameLabel = QtGui.QLabel(self.planTab)
        self.planGroupNameLabel.setObjectName(_fromUtf8("planGroupNameLabel"))
        self.gridLayout_6.addWidget(self.planGroupNameLabel, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.planTransparencySpin = QtGui.QSpinBox(self.planTab)
        self.planTransparencySpin.setMaximum(100)
        self.planTransparencySpin.setProperty("value", 50)
        self.planTransparencySpin.setObjectName(_fromUtf8("planTransparencySpin"))
        self.horizontalLayout_4.addWidget(self.planTransparencySpin)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 9, 1, 1, 1)
        self.separateGeorefFolderLabel = QtGui.QLabel(self.planTab)
        self.separateGeorefFolderLabel.setObjectName(_fromUtf8("separateGeorefFolderLabel"))
        self.gridLayout_6.addWidget(self.separateGeorefFolderLabel, 8, 0, 1, 1)
        self.separateGeorefFolderCheck = QtGui.QCheckBox(self.planTab)
        self.separateGeorefFolderCheck.setText(_fromUtf8(""))
        self.separateGeorefFolderCheck.setChecked(True)
        self.separateGeorefFolderCheck.setObjectName(_fromUtf8("separateGeorefFolderCheck"))
        self.gridLayout_6.addWidget(self.separateGeorefFolderCheck, 8, 1, 1, 1)
        self.tabWidget.addTab(self.planTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.multiSiteLabel.setBuddy(self.multiSiteCheck)
        self.projectFolderLabel.setBuddy(self.projectFolderEdit)
        self.siteCodeLabel.setBuddy(self.siteCodeEdit)
        self.customStylesLabel.setBuddy(self.styleFolderEdit)
        self.defaultStylesLabel.setBuddy(self.defaultStylesCheck)
        self.prependSiteCodeLabel.setBuddy(self.prependSiteCodeCheck)
        self.useArkLabel.setBuddy(self.useArkCheck)
        self.gridFolderLabel.setBuddy(self.gridFolderEdit)
        self.gridPolygonsNameLabel.setBuddy(self.gridPolygonsNameEdit)
        self.gridLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.gridPointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.gridGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.baseFolderLabel.setBuddy(self.gridFolderEdit)
        self.basePointsNameLabel.setBuddy(self.gridPointsNameEdit)
        self.baseGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.baseLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.planPointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.planVectorFolderLabel.setBuddy(self.gridFolderEdit)
        self.planPolygonsNameLabel.setBuddy(self.gridPolygonsNameEdit)
        self.planLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.planGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.separateGeorefFolderLabel.setBuddy(self.separateGeorefFolderCheck)

        self.retranslateUi(SettingsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogBase)
        SettingsDialogBase.setTabOrder(self.projectFolderEdit, self.projectFolderButton)
        SettingsDialogBase.setTabOrder(self.projectFolderButton, self.multiSiteCheck)
        SettingsDialogBase.setTabOrder(self.multiSiteCheck, self.siteCodeEdit)
        SettingsDialogBase.setTabOrder(self.siteCodeEdit, self.prependSiteCodeCheck)
        SettingsDialogBase.setTabOrder(self.prependSiteCodeCheck, self.defaultStylesCheck)
        SettingsDialogBase.setTabOrder(self.defaultStylesCheck, self.styleFolderEdit)
        SettingsDialogBase.setTabOrder(self.styleFolderEdit, self.styleFolderButton)
        SettingsDialogBase.setTabOrder(self.styleFolderButton, self.gridFolderEdit)
        SettingsDialogBase.setTabOrder(self.gridFolderEdit, self.gridFolderButton)
        SettingsDialogBase.setTabOrder(self.gridFolderButton, self.gridGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.gridGroupNameEdit, self.gridPointsNameEdit)
        SettingsDialogBase.setTabOrder(self.gridPointsNameEdit, self.gridLinesNameEdit)
        SettingsDialogBase.setTabOrder(self.gridLinesNameEdit, self.gridPolygonsNameEdit)
        SettingsDialogBase.setTabOrder(self.gridPolygonsNameEdit, self.buttonBox)

    def retranslateUi(self, SettingsDialogBase):
        SettingsDialogBase.setWindowTitle(_translate("SettingsDialogBase", "Settings", None))
        self.multiSiteLabel.setText(_translate("SettingsDialogBase", "Multi-site Project", None))
        self.projectFolderLabel.setText(_translate("SettingsDialogBase", "Project Folder:", None))
        self.siteCodeLabel.setText(_translate("SettingsDialogBase", "Default Site Code:", None))
        self.styleFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.customStylesLabel.setText(_translate("SettingsDialogBase", "Custom Styles Folder:", None))
        self.defaultStylesLabel.setText(_translate("SettingsDialogBase", "Use Default Styles:", None))
        self.prependSiteCodeLabel.setText(_translate("SettingsDialogBase", "Prepend site code:", None))
        self.projectFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.useArkLabel.setText(_translate("SettingsDialogBase", "Use ARK DB mode:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("SettingsDialogBase", "Project", None))
        self.gridFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.gridFolderLabel.setText(_translate("SettingsDialogBase", "Data Folder:", None))
        self.gridPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.gridLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.gridPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.gridGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gridTab), _translate("SettingsDialogBase", "Grid", None))
        self.baseFolderLabel.setText(_translate("SettingsDialogBase", "Data Folder:", None))
        self.baseFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.basePointsNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.baseGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.baseLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.basePolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.baseTab), _translate("SettingsDialogBase", "Base", None))
        self.planPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.planTransparencyLabel.setText(_translate("SettingsDialogBase", "Image tranparency:", None))
        self.planVectorFolderLabel.setText(_translate("SettingsDialogBase", "Data Folder:", None))
        self.planBufferGroupNameLabel.setText(_translate("SettingsDialogBase", "Buffer Group Name:", None))
        self.planRasterFolderLabel.setText(_translate("SettingsDialogBase", "Image Folder:", None))
        self.planRasterFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.planPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.planLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.planVectorFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.planGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.planTransparencySpin.setSuffix(_translate("SettingsDialogBase", "%", None))
        self.separateGeorefFolderLabel.setText(_translate("SettingsDialogBase", "Separate georef folder:", None))
        self.separateGeorefFolderCheck.setToolTip(_translate("SettingsDialogBase", "Select if the raw and processed plans should be stored in separate folders.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.planTab), _translate("SettingsDialogBase", "Plan", None))

