# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/settings_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogBase(object):
    def setupUi(self, SettingsDialogBase):
        SettingsDialogBase.setObjectName(_fromUtf8("SettingsDialogBase"))
        SettingsDialogBase.resize(526, 351)
        self.verticalLayout = QtGui.QVBoxLayout(SettingsDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.multiSiteLabel = QtGui.QLabel(self.projectTab)
        self.multiSiteLabel.setObjectName(_fromUtf8("multiSiteLabel"))
        self.gridLayout_5.addWidget(self.multiSiteLabel, 1, 0, 1, 1)
        self.prependSiteCodeCheck = QtGui.QCheckBox(self.projectTab)
        self.prependSiteCodeCheck.setText(_fromUtf8(""))
        self.prependSiteCodeCheck.setChecked(True)
        self.prependSiteCodeCheck.setObjectName(_fromUtf8("prependSiteCodeCheck"))
        self.gridLayout_5.addWidget(self.prependSiteCodeCheck, 3, 2, 1, 1)
        self.projectFolderLabel = QtGui.QLabel(self.projectTab)
        self.projectFolderLabel.setObjectName(_fromUtf8("projectFolderLabel"))
        self.gridLayout_5.addWidget(self.projectFolderLabel, 0, 0, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(self.projectTab)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.gridLayout_5.addWidget(self.siteCodeLabel, 2, 0, 1, 1)
        self.defaultStylesCheck = QtGui.QCheckBox(self.projectTab)
        self.defaultStylesCheck.setText(_fromUtf8(""))
        self.defaultStylesCheck.setChecked(True)
        self.defaultStylesCheck.setObjectName(_fromUtf8("defaultStylesCheck"))
        self.gridLayout_5.addWidget(self.defaultStylesCheck, 4, 2, 1, 1)
        self.styleFolderLayout = QtGui.QHBoxLayout()
        self.styleFolderLayout.setObjectName(_fromUtf8("styleFolderLayout"))
        self.styleFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.styleFolderEdit.setEnabled(False)
        self.styleFolderEdit.setObjectName(_fromUtf8("styleFolderEdit"))
        self.styleFolderLayout.addWidget(self.styleFolderEdit)
        self.styleFolderButton = QtGui.QPushButton(self.projectTab)
        self.styleFolderButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.styleFolderButton.sizePolicy().hasHeightForWidth())
        self.styleFolderButton.setSizePolicy(sizePolicy)
        self.styleFolderButton.setObjectName(_fromUtf8("styleFolderButton"))
        self.styleFolderLayout.addWidget(self.styleFolderButton)
        self.gridLayout_5.addLayout(self.styleFolderLayout, 5, 2, 1, 1)
        self.siteCodeEdit = QtGui.QLineEdit(self.projectTab)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.gridLayout_5.addWidget(self.siteCodeEdit, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 7, 2, 1, 1)
        self.customStylesLabel = QtGui.QLabel(self.projectTab)
        self.customStylesLabel.setObjectName(_fromUtf8("customStylesLabel"))
        self.gridLayout_5.addWidget(self.customStylesLabel, 5, 0, 1, 2)
        self.defaultStylesLabel = QtGui.QLabel(self.projectTab)
        self.defaultStylesLabel.setObjectName(_fromUtf8("defaultStylesLabel"))
        self.gridLayout_5.addWidget(self.defaultStylesLabel, 4, 0, 1, 2)
        self.prependSiteCodeLabel = QtGui.QLabel(self.projectTab)
        self.prependSiteCodeLabel.setObjectName(_fromUtf8("prependSiteCodeLabel"))
        self.gridLayout_5.addWidget(self.prependSiteCodeLabel, 3, 0, 1, 1)
        self.projectFolderLayout = QtGui.QHBoxLayout()
        self.projectFolderLayout.setObjectName(_fromUtf8("projectFolderLayout"))
        self.projectFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.projectFolderEdit.setObjectName(_fromUtf8("projectFolderEdit"))
        self.projectFolderLayout.addWidget(self.projectFolderEdit)
        self.projectFolderButton = QtGui.QPushButton(self.projectTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectFolderButton.sizePolicy().hasHeightForWidth())
        self.projectFolderButton.setSizePolicy(sizePolicy)
        self.projectFolderButton.setObjectName(_fromUtf8("projectFolderButton"))
        self.projectFolderLayout.addWidget(self.projectFolderButton)
        self.gridLayout_5.addLayout(self.projectFolderLayout, 0, 2, 1, 1)
        self.multiSiteCheck = QtGui.QCheckBox(self.projectTab)
        self.multiSiteCheck.setText(_fromUtf8(""))
        self.multiSiteCheck.setObjectName(_fromUtf8("multiSiteCheck"))
        self.gridLayout_5.addWidget(self.multiSiteCheck, 1, 2, 1, 1)
        self.useArkLabel = QtGui.QLabel(self.projectTab)
        self.useArkLabel.setObjectName(_fromUtf8("useArkLabel"))
        self.gridLayout_5.addWidget(self.useArkLabel, 6, 0, 1, 1)
        self.useArkCheck = QtGui.QCheckBox(self.projectTab)
        self.useArkCheck.setText(_fromUtf8(""))
        self.useArkCheck.setObjectName(_fromUtf8("useArkCheck"))
        self.gridLayout_5.addWidget(self.useArkCheck, 6, 2, 1, 1)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.gridTab = QtGui.QWidget()
        self.gridTab.setObjectName(_fromUtf8("gridTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridFolderLayout = QtGui.QHBoxLayout()
        self.gridFolderLayout.setObjectName(_fromUtf8("gridFolderLayout"))
        self.gridFolderEdit = QtGui.QLineEdit(self.gridTab)
        self.gridFolderEdit.setObjectName(_fromUtf8("gridFolderEdit"))
        self.gridFolderLayout.addWidget(self.gridFolderEdit)
        self.gridFolderButton = QtGui.QPushButton(self.gridTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFolderButton.sizePolicy().hasHeightForWidth())
        self.gridFolderButton.setSizePolicy(sizePolicy)
        self.gridFolderButton.setObjectName(_fromUtf8("gridFolderButton"))
        self.gridFolderLayout.addWidget(self.gridFolderButton)
        self.gridLayout_4.addLayout(self.gridFolderLayout, 0, 1, 1, 1)
        self.gridFolderLabel = QtGui.QLabel(self.gridTab)
        self.gridFolderLabel.setObjectName(_fromUtf8("gridFolderLabel"))
        self.gridLayout_4.addWidget(self.gridFolderLabel, 0, 0, 1, 1)
        self.gridPolygonsNameLabel = QtGui.QLabel(self.gridTab)
        self.gridPolygonsNameLabel.setObjectName(_fromUtf8("gridPolygonsNameLabel"))
        self.gridLayout_4.addWidget(self.gridPolygonsNameLabel, 4, 0, 1, 1)
        self.gridPointsNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridPointsNameEdit.setObjectName(_fromUtf8("gridPointsNameEdit"))
        self.gridLayout_4.addWidget(self.gridPointsNameEdit, 2, 1, 1, 1)
        self.gridLinesNameLabel = QtGui.QLabel(self.gridTab)
        self.gridLinesNameLabel.setObjectName(_fromUtf8("gridLinesNameLabel"))
        self.gridLayout_4.addWidget(self.gridLinesNameLabel, 3, 0, 1, 1)
        self.gridPolygonsNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridPolygonsNameEdit.setObjectName(_fromUtf8("gridPolygonsNameEdit"))
        self.gridLayout_4.addWidget(self.gridPolygonsNameEdit, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 5, 1, 1, 1)
        self.gridLinesNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridLinesNameEdit.setObjectName(_fromUtf8("gridLinesNameEdit"))
        self.gridLayout_4.addWidget(self.gridLinesNameEdit, 3, 1, 1, 1)
        self.gridPointNameLabel = QtGui.QLabel(self.gridTab)
        self.gridPointNameLabel.setObjectName(_fromUtf8("gridPointNameLabel"))
        self.gridLayout_4.addWidget(self.gridPointNameLabel, 2, 0, 1, 1)
        self.gridGroupNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridGroupNameEdit.setObjectName(_fromUtf8("gridGroupNameEdit"))
        self.gridLayout_4.addWidget(self.gridGroupNameEdit, 1, 1, 1, 1)
        self.gridGroupNameLabel = QtGui.QLabel(self.gridTab)
        self.gridGroupNameLabel.setObjectName(_fromUtf8("gridGroupNameLabel"))
        self.gridLayout_4.addWidget(self.gridGroupNameLabel, 1, 0, 1, 1)
        self.tabWidget.addTab(self.gridTab, _fromUtf8(""))
        self.baseTab = QtGui.QWidget()
        self.baseTab.setObjectName(_fromUtf8("baseTab"))
        self.gridLayout = QtGui.QGridLayout(self.baseTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.basePointsNameEdit = QtGui.QLineEdit(self.baseTab)
        self.basePointsNameEdit.setObjectName(_fromUtf8("basePointsNameEdit"))
        self.gridLayout.addWidget(self.basePointsNameEdit, 2, 1, 1, 2)
        self.baseFolderLabel = QtGui.QLabel(self.baseTab)
        self.baseFolderLabel.setObjectName(_fromUtf8("baseFolderLabel"))
        self.gridLayout.addWidget(self.baseFolderLabel, 0, 0, 1, 1)
        self.baseLinesNameLabel = QtGui.QLabel(self.baseTab)
        self.baseLinesNameLabel.setObjectName(_fromUtf8("baseLinesNameLabel"))
        self.gridLayout.addWidget(self.baseLinesNameLabel, 3, 0, 1, 1)
        self.basePointNameLabel = QtGui.QLabel(self.baseTab)
        self.basePointNameLabel.setObjectName(_fromUtf8("basePointNameLabel"))
        self.gridLayout.addWidget(self.basePointNameLabel, 2, 0, 1, 1)
        self.baseGroupNameEdit = QtGui.QLineEdit(self.baseTab)
        self.baseGroupNameEdit.setObjectName(_fromUtf8("baseGroupNameEdit"))
        self.gridLayout.addWidget(self.baseGroupNameEdit, 1, 1, 1, 2)
        self.baseGroupNameLabel = QtGui.QLabel(self.baseTab)
        self.baseGroupNameLabel.setObjectName(_fromUtf8("baseGroupNameLabel"))
        self.gridLayout.addWidget(self.baseGroupNameLabel, 1, 0, 1, 1)
        self.baseLinesNameEdit = QtGui.QLineEdit(self.baseTab)
        self.baseLinesNameEdit.setObjectName(_fromUtf8("baseLinesNameEdit"))
        self.gridLayout.addWidget(self.baseLinesNameEdit, 3, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 99, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.baseFolderLayout = QtGui.QHBoxLayout()
        self.baseFolderLayout.setObjectName(_fromUtf8("baseFolderLayout"))
        self.baseFolderEdit = QtGui.QLineEdit(self.baseTab)
        self.baseFolderEdit.setObjectName(_fromUtf8("baseFolderEdit"))
        self.baseFolderLayout.addWidget(self.baseFolderEdit)
        self.baseFolderButton = QtGui.QPushButton(self.baseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baseFolderButton.sizePolicy().hasHeightForWidth())
        self.baseFolderButton.setSizePolicy(sizePolicy)
        self.baseFolderButton.setObjectName(_fromUtf8("baseFolderButton"))
        self.baseFolderLayout.addWidget(self.baseFolderButton)
        self.gridLayout.addLayout(self.baseFolderLayout, 0, 1, 1, 2)
        self.tabWidget.addTab(self.baseTab, _fromUtf8(""))
        self.featuresTab = QtGui.QWidget()
        self.featuresTab.setObjectName(_fromUtf8("featuresTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.featuresTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.featuresPointsNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featuresPointsNameEdit.setObjectName(_fromUtf8("featuresPointsNameEdit"))
        self.gridLayout_6.addWidget(self.featuresPointsNameEdit, 4, 1, 1, 1)
        self.featuresLinesNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featuresLinesNameEdit.setObjectName(_fromUtf8("featuresLinesNameEdit"))
        self.gridLayout_6.addWidget(self.featuresLinesNameEdit, 5, 1, 1, 1)
        self.featuresFolderLayout = QtGui.QHBoxLayout()
        self.featuresFolderLayout.setObjectName(_fromUtf8("featuresFolderLayout"))
        self.featuresFolderEdit = QtGui.QLineEdit(self.featuresTab)
        self.featuresFolderEdit.setObjectName(_fromUtf8("featuresFolderEdit"))
        self.featuresFolderLayout.addWidget(self.featuresFolderEdit)
        self.featuresFolderButton = QtGui.QPushButton(self.featuresTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.featuresFolderButton.sizePolicy().hasHeightForWidth())
        self.featuresFolderButton.setSizePolicy(sizePolicy)
        self.featuresFolderButton.setObjectName(_fromUtf8("featuresFolderButton"))
        self.featuresFolderLayout.addWidget(self.featuresFolderButton)
        self.gridLayout_6.addLayout(self.featuresFolderLayout, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 8, 1, 1, 1)
        self.featuresGroupNameLabel = QtGui.QLabel(self.featuresTab)
        self.featuresGroupNameLabel.setObjectName(_fromUtf8("featuresGroupNameLabel"))
        self.gridLayout_6.addWidget(self.featuresGroupNameLabel, 1, 0, 1, 1)
        self.featuresFolderLabel = QtGui.QLabel(self.featuresTab)
        self.featuresFolderLabel.setObjectName(_fromUtf8("featuresFolderLabel"))
        self.gridLayout_6.addWidget(self.featuresFolderLabel, 0, 0, 1, 1)
        self.featuresLinesNameLabel = QtGui.QLabel(self.featuresTab)
        self.featuresLinesNameLabel.setObjectName(_fromUtf8("featuresLinesNameLabel"))
        self.gridLayout_6.addWidget(self.featuresLinesNameLabel, 5, 0, 1, 1)
        self.featuresPointNameLabel = QtGui.QLabel(self.featuresTab)
        self.featuresPointNameLabel.setObjectName(_fromUtf8("featuresPointNameLabel"))
        self.gridLayout_6.addWidget(self.featuresPointNameLabel, 4, 0, 1, 1)
        self.featuresGroupNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featuresGroupNameEdit.setObjectName(_fromUtf8("featuresGroupNameEdit"))
        self.gridLayout_6.addWidget(self.featuresGroupNameEdit, 1, 1, 1, 1)
        self.featuresPolygonsNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featuresPolygonsNameEdit.setObjectName(_fromUtf8("featuresPolygonsNameEdit"))
        self.gridLayout_6.addWidget(self.featuresPolygonsNameEdit, 6, 1, 1, 1)
        self.featuresPolygonsNameLabel = QtGui.QLabel(self.featuresTab)
        self.featuresPolygonsNameLabel.setObjectName(_fromUtf8("featuresPolygonsNameLabel"))
        self.gridLayout_6.addWidget(self.featuresPolygonsNameLabel, 6, 0, 1, 1)
        self.featuresBufferGroupNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featuresBufferGroupNameEdit.setObjectName(_fromUtf8("featuresBufferGroupNameEdit"))
        self.gridLayout_6.addWidget(self.featuresBufferGroupNameEdit, 3, 1, 1, 1)
        self.featuresBufferGroupNameLabel = QtGui.QLabel(self.featuresTab)
        self.featuresBufferGroupNameLabel.setObjectName(_fromUtf8("featuresBufferGroupNameLabel"))
        self.gridLayout_6.addWidget(self.featuresBufferGroupNameLabel, 3, 0, 1, 1)
        self.tabWidget.addTab(self.featuresTab, _fromUtf8(""))
        self.contextsTab = QtGui.QWidget()
        self.contextsTab.setObjectName(_fromUtf8("contextsTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.contextsTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.contextsFolderLayout = QtGui.QHBoxLayout()
        self.contextsFolderLayout.setObjectName(_fromUtf8("contextsFolderLayout"))
        self.contextsFolderEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsFolderEdit.setObjectName(_fromUtf8("contextsFolderEdit"))
        self.contextsFolderLayout.addWidget(self.contextsFolderEdit)
        self.contextsFolderButton = QtGui.QPushButton(self.contextsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextsFolderButton.sizePolicy().hasHeightForWidth())
        self.contextsFolderButton.setSizePolicy(sizePolicy)
        self.contextsFolderButton.setObjectName(_fromUtf8("contextsFolderButton"))
        self.contextsFolderLayout.addWidget(self.contextsFolderButton)
        self.gridLayout_3.addLayout(self.contextsFolderLayout, 0, 1, 1, 1)
        self.contextsFolderLabel = QtGui.QLabel(self.contextsTab)
        self.contextsFolderLabel.setObjectName(_fromUtf8("contextsFolderLabel"))
        self.gridLayout_3.addWidget(self.contextsFolderLabel, 0, 0, 1, 1)
        self.contextsSchemaNameLabel = QtGui.QLabel(self.contextsTab)
        self.contextsSchemaNameLabel.setObjectName(_fromUtf8("contextsSchemaNameLabel"))
        self.gridLayout_3.addWidget(self.contextsSchemaNameLabel, 9, 0, 1, 1)
        self.contextsPointsNameEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsPointsNameEdit.setObjectName(_fromUtf8("contextsPointsNameEdit"))
        self.gridLayout_3.addWidget(self.contextsPointsNameEdit, 4, 1, 1, 1)
        self.contextsGroupNameLabel = QtGui.QLabel(self.contextsTab)
        self.contextsGroupNameLabel.setObjectName(_fromUtf8("contextsGroupNameLabel"))
        self.gridLayout_3.addWidget(self.contextsGroupNameLabel, 2, 0, 1, 1)
        self.contextsGroupNameEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsGroupNameEdit.setObjectName(_fromUtf8("contextsGroupNameEdit"))
        self.gridLayout_3.addWidget(self.contextsGroupNameEdit, 2, 1, 1, 1)
        self.contextsPolygonsNameEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsPolygonsNameEdit.setObjectName(_fromUtf8("contextsPolygonsNameEdit"))
        self.gridLayout_3.addWidget(self.contextsPolygonsNameEdit, 8, 1, 1, 1)
        self.contextsLinesNameLabel = QtGui.QLabel(self.contextsTab)
        self.contextsLinesNameLabel.setObjectName(_fromUtf8("contextsLinesNameLabel"))
        self.gridLayout_3.addWidget(self.contextsLinesNameLabel, 6, 0, 1, 1)
        self.contextsSchemaNameEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsSchemaNameEdit.setObjectName(_fromUtf8("contextsSchemaNameEdit"))
        self.gridLayout_3.addWidget(self.contextsSchemaNameEdit, 9, 1, 1, 1)
        self.contextsLinesNameEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsLinesNameEdit.setObjectName(_fromUtf8("contextsLinesNameEdit"))
        self.gridLayout_3.addWidget(self.contextsLinesNameEdit, 6, 1, 1, 1)
        self.contextsPointNameLabel = QtGui.QLabel(self.contextsTab)
        self.contextsPointNameLabel.setObjectName(_fromUtf8("contextsPointNameLabel"))
        self.gridLayout_3.addWidget(self.contextsPointNameLabel, 4, 0, 1, 1)
        self.contextsPolygonsNameLabel = QtGui.QLabel(self.contextsTab)
        self.contextsPolygonsNameLabel.setObjectName(_fromUtf8("contextsPolygonsNameLabel"))
        self.gridLayout_3.addWidget(self.contextsPolygonsNameLabel, 8, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 10, 1, 1, 1)
        self.contextsBufferGroupNameEdit = QtGui.QLineEdit(self.contextsTab)
        self.contextsBufferGroupNameEdit.setObjectName(_fromUtf8("contextsBufferGroupNameEdit"))
        self.gridLayout_3.addWidget(self.contextsBufferGroupNameEdit, 3, 1, 1, 1)
        self.contextsBufferGroupNameLabel = QtGui.QLabel(self.contextsTab)
        self.contextsBufferGroupNameLabel.setObjectName(_fromUtf8("contextsBufferGroupNameLabel"))
        self.gridLayout_3.addWidget(self.contextsBufferGroupNameLabel, 3, 0, 1, 1)
        self.tabWidget.addTab(self.contextsTab, _fromUtf8(""))
        self.plansTab = QtGui.QWidget()
        self.plansTab.setObjectName(_fromUtf8("plansTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.plansTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.separatePlansCheck = QtGui.QCheckBox(self.plansTab)
        self.separatePlansCheck.setText(_fromUtf8(""))
        self.separatePlansCheck.setChecked(True)
        self.separatePlansCheck.setObjectName(_fromUtf8("separatePlansCheck"))
        self.gridLayout_2.addWidget(self.separatePlansCheck, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.planFolderEdit = QtGui.QLineEdit(self.plansTab)
        self.planFolderEdit.setObjectName(_fromUtf8("planFolderEdit"))
        self.horizontalLayout_2.addWidget(self.planFolderEdit)
        self.planFolderButton = QtGui.QPushButton(self.plansTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.planFolderButton.sizePolicy().hasHeightForWidth())
        self.planFolderButton.setSizePolicy(sizePolicy)
        self.planFolderButton.setObjectName(_fromUtf8("planFolderButton"))
        self.horizontalLayout_2.addWidget(self.planFolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.planTransparencyLabel = QtGui.QLabel(self.plansTab)
        self.planTransparencyLabel.setObjectName(_fromUtf8("planTransparencyLabel"))
        self.gridLayout_2.addWidget(self.planTransparencyLabel, 2, 0, 1, 1)
        self.separatePlansLabel = QtGui.QLabel(self.plansTab)
        self.separatePlansLabel.setObjectName(_fromUtf8("separatePlansLabel"))
        self.gridLayout_2.addWidget(self.separatePlansLabel, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.planTransparencySpin = QtGui.QSpinBox(self.plansTab)
        self.planTransparencySpin.setMaximum(100)
        self.planTransparencySpin.setProperty("value", 50)
        self.planTransparencySpin.setObjectName(_fromUtf8("planTransparencySpin"))
        self.horizontalLayout_4.addWidget(self.planTransparencySpin)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.planFolderLabel = QtGui.QLabel(self.plansTab)
        self.planFolderLabel.setObjectName(_fromUtf8("planFolderLabel"))
        self.gridLayout_2.addWidget(self.planFolderLabel, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 3, 1, 1, 1)
        self.tabWidget.addTab(self.plansTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.multiSiteLabel.setBuddy(self.multiSiteCheck)
        self.projectFolderLabel.setBuddy(self.projectFolderEdit)
        self.siteCodeLabel.setBuddy(self.siteCodeEdit)
        self.customStylesLabel.setBuddy(self.styleFolderEdit)
        self.defaultStylesLabel.setBuddy(self.defaultStylesCheck)
        self.prependSiteCodeLabel.setBuddy(self.prependSiteCodeCheck)
        self.useArkLabel.setBuddy(self.useArkCheck)
        self.gridFolderLabel.setBuddy(self.gridFolderEdit)
        self.gridPolygonsNameLabel.setBuddy(self.gridPolygonsNameEdit)
        self.gridLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.gridPointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.gridGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.baseFolderLabel.setBuddy(self.gridFolderEdit)
        self.baseLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.basePointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.baseGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.featuresGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.featuresFolderLabel.setBuddy(self.gridFolderEdit)
        self.featuresLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.featuresPointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.featuresPolygonsNameLabel.setBuddy(self.gridPolygonsNameEdit)
        self.contextsFolderLabel.setBuddy(self.contextsFolderEdit)
        self.contextsSchemaNameLabel.setBuddy(self.contextsSchemaNameEdit)
        self.contextsGroupNameLabel.setBuddy(self.contextsGroupNameEdit)
        self.contextsLinesNameLabel.setBuddy(self.contextsLinesNameEdit)
        self.contextsPointNameLabel.setBuddy(self.contextsPointsNameEdit)
        self.contextsPolygonsNameLabel.setBuddy(self.contextsPolygonsNameEdit)
        self.contextsBufferGroupNameLabel.setBuddy(self.contextsBufferGroupNameEdit)
        self.planTransparencyLabel.setBuddy(self.planTransparencySpin)
        self.separatePlansLabel.setBuddy(self.separatePlansCheck)
        self.planFolderLabel.setBuddy(self.planFolderEdit)

        self.retranslateUi(SettingsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogBase)
        SettingsDialogBase.setTabOrder(self.projectFolderEdit, self.projectFolderButton)
        SettingsDialogBase.setTabOrder(self.projectFolderButton, self.multiSiteCheck)
        SettingsDialogBase.setTabOrder(self.multiSiteCheck, self.siteCodeEdit)
        SettingsDialogBase.setTabOrder(self.siteCodeEdit, self.prependSiteCodeCheck)
        SettingsDialogBase.setTabOrder(self.prependSiteCodeCheck, self.defaultStylesCheck)
        SettingsDialogBase.setTabOrder(self.defaultStylesCheck, self.styleFolderEdit)
        SettingsDialogBase.setTabOrder(self.styleFolderEdit, self.styleFolderButton)
        SettingsDialogBase.setTabOrder(self.styleFolderButton, self.gridFolderEdit)
        SettingsDialogBase.setTabOrder(self.gridFolderEdit, self.gridFolderButton)
        SettingsDialogBase.setTabOrder(self.gridFolderButton, self.gridGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.gridGroupNameEdit, self.gridPointsNameEdit)
        SettingsDialogBase.setTabOrder(self.gridPointsNameEdit, self.gridLinesNameEdit)
        SettingsDialogBase.setTabOrder(self.gridLinesNameEdit, self.gridPolygonsNameEdit)
        SettingsDialogBase.setTabOrder(self.gridPolygonsNameEdit, self.contextsFolderEdit)
        SettingsDialogBase.setTabOrder(self.contextsFolderEdit, self.contextsFolderButton)
        SettingsDialogBase.setTabOrder(self.contextsFolderButton, self.contextsGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.contextsGroupNameEdit, self.contextsBufferGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.contextsBufferGroupNameEdit, self.contextsPointsNameEdit)
        SettingsDialogBase.setTabOrder(self.contextsPointsNameEdit, self.contextsLinesNameEdit)
        SettingsDialogBase.setTabOrder(self.contextsLinesNameEdit, self.contextsPolygonsNameEdit)
        SettingsDialogBase.setTabOrder(self.contextsPolygonsNameEdit, self.contextsSchemaNameEdit)
        SettingsDialogBase.setTabOrder(self.contextsSchemaNameEdit, self.planFolderEdit)
        SettingsDialogBase.setTabOrder(self.planFolderEdit, self.planFolderButton)
        SettingsDialogBase.setTabOrder(self.planFolderButton, self.separatePlansCheck)
        SettingsDialogBase.setTabOrder(self.separatePlansCheck, self.planTransparencySpin)
        SettingsDialogBase.setTabOrder(self.planTransparencySpin, self.buttonBox)

    def retranslateUi(self, SettingsDialogBase):
        SettingsDialogBase.setWindowTitle(_translate("SettingsDialogBase", "Settings", None))
        self.multiSiteLabel.setText(_translate("SettingsDialogBase", "Multi-site Project", None))
        self.projectFolderLabel.setText(_translate("SettingsDialogBase", "Project Folder:", None))
        self.siteCodeLabel.setText(_translate("SettingsDialogBase", "Default Site Code:", None))
        self.styleFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.customStylesLabel.setText(_translate("SettingsDialogBase", "Custom Styles Folder:", None))
        self.defaultStylesLabel.setText(_translate("SettingsDialogBase", "Use Default Styles:", None))
        self.prependSiteCodeLabel.setText(_translate("SettingsDialogBase", "Prepend site code:", None))
        self.projectFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.useArkLabel.setText(_translate("SettingsDialogBase", "Use ARK DB mode:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("SettingsDialogBase", "Project", None))
        self.gridFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.gridFolderLabel.setText(_translate("SettingsDialogBase", "Folder:", None))
        self.gridPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.gridLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.gridPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.gridGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gridTab), _translate("SettingsDialogBase", "Grid", None))
        self.baseFolderLabel.setText(_translate("SettingsDialogBase", "Folder:", None))
        self.baseLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.basePointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.baseGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.baseFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.baseTab), _translate("SettingsDialogBase", "Base", None))
        self.featuresFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.featuresGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.featuresFolderLabel.setText(_translate("SettingsDialogBase", "Folder:", None))
        self.featuresLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.featuresPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.featuresPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.featuresBufferGroupNameLabel.setText(_translate("SettingsDialogBase", "Buffer Group Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.featuresTab), _translate("SettingsDialogBase", "Features", None))
        self.contextsFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.contextsFolderLabel.setText(_translate("SettingsDialogBase", "Contexts Folder:", None))
        self.contextsSchemaNameLabel.setText(_translate("SettingsDialogBase", "Schema Base Name:", None))
        self.contextsGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.contextsLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.contextsPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.contextsPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.contextsBufferGroupNameLabel.setText(_translate("SettingsDialogBase", "Buffer Group Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contextsTab), _translate("SettingsDialogBase", "Contexts", None))
        self.separatePlansCheck.setToolTip(_translate("SettingsDialogBase", "Select if the raw and processed plans should be stored in separate folders.", None))
        self.planFolderButton.setText(_translate("SettingsDialogBase", "...", None))
        self.planTransparencyLabel.setText(_translate("SettingsDialogBase", "Plan tranparency:", None))
        self.separatePlansLabel.setText(_translate("SettingsDialogBase", "Separate plan folders:", None))
        self.planTransparencySpin.setSuffix(_translate("SettingsDialogBase", "%", None))
        self.planFolderLabel.setText(_translate("SettingsDialogBase", "Plan Folder:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plansTab), _translate("SettingsDialogBase", "Plans", None))

