# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grid/create_grid_dialog_base.ui'
#
# Created: Mon Apr 13 22:10:15 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateGridDialog(object):
    def setupUi(self, CreateGridDialog):
        CreateGridDialog.setObjectName(_fromUtf8("CreateGridDialog"))
        CreateGridDialog.resize(475, 239)
        CreateGridDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(CreateGridDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.crsOriginLabel = QtGui.QLabel(CreateGridDialog)
        self.crsOriginLabel.setObjectName(_fromUtf8("crsOriginLabel"))
        self.gridLayout.addWidget(self.crsOriginLabel, 0, 0, 1, 1)
        self.crsTerminusFromMapButton = QtGui.QPushButton(CreateGridDialog)
        self.crsTerminusFromMapButton.setObjectName(_fromUtf8("crsTerminusFromMapButton"))
        self.gridLayout.addWidget(self.crsTerminusFromMapButton, 1, 3, 1, 1)
        self.crsTerminusEastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsTerminusEastingSpin.setDecimals(3)
        self.crsTerminusEastingSpin.setMaximum(999999.999)
        self.crsTerminusEastingSpin.setObjectName(_fromUtf8("crsTerminusEastingSpin"))
        self.gridLayout.addWidget(self.crsTerminusEastingSpin, 1, 1, 1, 1)
        self.crsTerminusNorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsTerminusNorthingSpin.setDecimals(3)
        self.crsTerminusNorthingSpin.setMaximum(999999.999)
        self.crsTerminusNorthingSpin.setObjectName(_fromUtf8("crsTerminusNorthingSpin"))
        self.gridLayout.addWidget(self.crsTerminusNorthingSpin, 1, 2, 1, 1)
        self.localOriginNorthingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localOriginNorthingSpin.setMaximum(9999)
        self.localOriginNorthingSpin.setSingleStep(5)
        self.localOriginNorthingSpin.setProperty("value", 200)
        self.localOriginNorthingSpin.setObjectName(_fromUtf8("localOriginNorthingSpin"))
        self.gridLayout.addWidget(self.localOriginNorthingSpin, 2, 2, 1, 1)
        self.crsTerminusLabel = QtGui.QLabel(CreateGridDialog)
        self.crsTerminusLabel.setObjectName(_fromUtf8("crsTerminusLabel"))
        self.gridLayout.addWidget(self.crsTerminusLabel, 1, 0, 1, 1)
        self.localOriginEastingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localOriginEastingSpin.setMaximum(9999)
        self.localOriginEastingSpin.setSingleStep(5)
        self.localOriginEastingSpin.setProperty("value", 100)
        self.localOriginEastingSpin.setObjectName(_fromUtf8("localOriginEastingSpin"))
        self.gridLayout.addWidget(self.localOriginEastingSpin, 2, 1, 1, 1)
        self.localOriginLabel = QtGui.QLabel(CreateGridDialog)
        self.localOriginLabel.setObjectName(_fromUtf8("localOriginLabel"))
        self.gridLayout.addWidget(self.localOriginLabel, 2, 0, 1, 1)
        self.crsOriginFromMapButton = QtGui.QPushButton(CreateGridDialog)
        self.crsOriginFromMapButton.setObjectName(_fromUtf8("crsOriginFromMapButton"))
        self.gridLayout.addWidget(self.crsOriginFromMapButton, 0, 3, 1, 1)
        self.crsOriginEastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsOriginEastingSpin.setDecimals(3)
        self.crsOriginEastingSpin.setMaximum(999999.999)
        self.crsOriginEastingSpin.setObjectName(_fromUtf8("crsOriginEastingSpin"))
        self.gridLayout.addWidget(self.crsOriginEastingSpin, 0, 1, 1, 1)
        self.crsOriginNorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsOriginNorthingSpin.setDecimals(3)
        self.crsOriginNorthingSpin.setMaximum(999999.999)
        self.crsOriginNorthingSpin.setObjectName(_fromUtf8("crsOriginNorthingSpin"))
        self.gridLayout.addWidget(self.crsOriginNorthingSpin, 0, 2, 1, 1)
        self.localTerminusEastingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localTerminusEastingSpin.setMaximum(9999)
        self.localTerminusEastingSpin.setSingleStep(5)
        self.localTerminusEastingSpin.setProperty("value", 200)
        self.localTerminusEastingSpin.setObjectName(_fromUtf8("localTerminusEastingSpin"))
        self.gridLayout.addWidget(self.localTerminusEastingSpin, 3, 1, 1, 1)
        self.localTerminusNorthingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localTerminusNorthingSpin.setMaximum(9999)
        self.localTerminusNorthingSpin.setSingleStep(5)
        self.localTerminusNorthingSpin.setProperty("value", 300)
        self.localTerminusNorthingSpin.setObjectName(_fromUtf8("localTerminusNorthingSpin"))
        self.gridLayout.addWidget(self.localTerminusNorthingSpin, 3, 2, 1, 1)
        self.localTerminusLabel = QtGui.QLabel(CreateGridDialog)
        self.localTerminusLabel.setObjectName(_fromUtf8("localTerminusLabel"))
        self.gridLayout.addWidget(self.localTerminusLabel, 3, 0, 1, 1)
        self.localIntervalSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localIntervalSpin.setMaximum(100)
        self.localIntervalSpin.setSingleStep(5)
        self.localIntervalSpin.setProperty("value", 5)
        self.localIntervalSpin.setObjectName(_fromUtf8("localIntervalSpin"))
        self.gridLayout.addWidget(self.localIntervalSpin, 4, 1, 1, 1)
        self.localIntervalLabel = QtGui.QLabel(CreateGridDialog)
        self.localIntervalLabel.setObjectName(_fromUtf8("localIntervalLabel"))
        self.gridLayout.addWidget(self.localIntervalLabel, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtGui.QPushButton(CreateGridDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        self.createGridButton = QtGui.QPushButton(CreateGridDialog)
        self.createGridButton.setDefault(True)
        self.createGridButton.setObjectName(_fromUtf8("createGridButton"))
        self.horizontalLayout.addWidget(self.createGridButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.crsOriginLabel.setBuddy(self.crsOriginEastingSpin)
        self.crsTerminusLabel.setBuddy(self.crsTerminusEastingSpin)
        self.localOriginLabel.setBuddy(self.localOriginEastingSpin)
        self.localTerminusLabel.setBuddy(self.localTerminusEastingSpin)
        self.localIntervalLabel.setBuddy(self.localIntervalSpin)

        self.retranslateUi(CreateGridDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateGridDialog)
        CreateGridDialog.setTabOrder(self.crsOriginEastingSpin, self.crsOriginNorthingSpin)
        CreateGridDialog.setTabOrder(self.crsOriginNorthingSpin, self.crsOriginFromMapButton)
        CreateGridDialog.setTabOrder(self.crsOriginFromMapButton, self.crsTerminusEastingSpin)
        CreateGridDialog.setTabOrder(self.crsTerminusEastingSpin, self.crsTerminusNorthingSpin)
        CreateGridDialog.setTabOrder(self.crsTerminusNorthingSpin, self.crsTerminusFromMapButton)
        CreateGridDialog.setTabOrder(self.crsTerminusFromMapButton, self.localOriginEastingSpin)
        CreateGridDialog.setTabOrder(self.localOriginEastingSpin, self.localOriginNorthingSpin)
        CreateGridDialog.setTabOrder(self.localOriginNorthingSpin, self.localTerminusEastingSpin)
        CreateGridDialog.setTabOrder(self.localTerminusEastingSpin, self.localTerminusNorthingSpin)
        CreateGridDialog.setTabOrder(self.localTerminusNorthingSpin, self.localIntervalSpin)
        CreateGridDialog.setTabOrder(self.localIntervalSpin, self.cancelButton)
        CreateGridDialog.setTabOrder(self.cancelButton, self.createGridButton)

    def retranslateUi(self, CreateGridDialog):
        CreateGridDialog.setWindowTitle(_translate("CreateGridDialog", "Create Grid", None))
        self.crsOriginLabel.setText(_translate("CreateGridDialog", "Origin Coordinates:", None))
        self.crsTerminusFromMapButton.setText(_translate("CreateGridDialog", "From Map", None))
        self.crsTerminusLabel.setText(_translate("CreateGridDialog", "Terminus Coordinates:", None))
        self.localOriginLabel.setText(_translate("CreateGridDialog", "Local Origin:", None))
        self.crsOriginFromMapButton.setText(_translate("CreateGridDialog", "From Map", None))
        self.localTerminusLabel.setText(_translate("CreateGridDialog", "Local Terminus:", None))
        self.localIntervalLabel.setText(_translate("CreateGridDialog", "Grid Interval:", None))
        self.cancelButton.setText(_translate("CreateGridDialog", "Cancel", None))
        self.createGridButton.setText(_translate("CreateGridDialog", "Create", None))

