# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grid/create_grid_dialog_base.ui'
#
# Created: Thu Aug  6 12:06:47 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateGridDialog(object):
    def setupUi(self, CreateGridDialog):
        CreateGridDialog.setObjectName(_fromUtf8("CreateGridDialog"))
        CreateGridDialog.resize(438, 473)
        CreateGridDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(CreateGridDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.localNorthingLabel = QtGui.QLabel(CreateGridDialog)
        self.localNorthingLabel.setObjectName(_fromUtf8("localNorthingLabel"))
        self.gridLayout.addWidget(self.localNorthingLabel, 10, 2, 1, 1)
        self.localPoint2Label = QtGui.QLabel(CreateGridDialog)
        self.localPoint2Label.setObjectName(_fromUtf8("localPoint2Label"))
        self.gridLayout.addWidget(self.localPoint2Label, 8, 0, 1, 1)
        self.localEastingIntervalSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localEastingIntervalSpin.setMaximum(100)
        self.localEastingIntervalSpin.setSingleStep(5)
        self.localEastingIntervalSpin.setProperty("value", 5)
        self.localEastingIntervalSpin.setObjectName(_fromUtf8("localEastingIntervalSpin"))
        self.gridLayout.addWidget(self.localEastingIntervalSpin, 13, 1, 1, 1)
        self.siteCodeEdit = QtGui.QLineEdit(CreateGridDialog)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.gridLayout.addWidget(self.siteCodeEdit, 0, 1, 1, 3)
        self.mapPoint1Label = QtGui.QLabel(CreateGridDialog)
        self.mapPoint1Label.setObjectName(_fromUtf8("mapPoint1Label"))
        self.gridLayout.addWidget(self.mapPoint1Label, 5, 0, 1, 1)
        self.localTerminusLabel = QtGui.QLabel(CreateGridDialog)
        self.localTerminusLabel.setObjectName(_fromUtf8("localTerminusLabel"))
        self.gridLayout.addWidget(self.localTerminusLabel, 12, 0, 1, 1)
        self.localTerminusEastingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localTerminusEastingSpin.setMaximum(9999)
        self.localTerminusEastingSpin.setSingleStep(5)
        self.localTerminusEastingSpin.setProperty("value", 200)
        self.localTerminusEastingSpin.setObjectName(_fromUtf8("localTerminusEastingSpin"))
        self.gridLayout.addWidget(self.localTerminusEastingSpin, 12, 1, 1, 1)
        self.localNorthingIntervalSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localNorthingIntervalSpin.setMaximum(100)
        self.localNorthingIntervalSpin.setSingleStep(5)
        self.localNorthingIntervalSpin.setProperty("value", 5)
        self.localNorthingIntervalSpin.setObjectName(_fromUtf8("localNorthingIntervalSpin"))
        self.gridLayout.addWidget(self.localNorthingIntervalSpin, 13, 2, 1, 1)
        self.localIntervalLabel = QtGui.QLabel(CreateGridDialog)
        self.localIntervalLabel.setObjectName(_fromUtf8("localIntervalLabel"))
        self.gridLayout.addWidget(self.localIntervalLabel, 13, 0, 1, 1)
        self.localEastingLabel = QtGui.QLabel(CreateGridDialog)
        self.localEastingLabel.setObjectName(_fromUtf8("localEastingLabel"))
        self.gridLayout.addWidget(self.localEastingLabel, 10, 1, 1, 1)
        self.mapPoint1FromMapButton = QtGui.QPushButton(CreateGridDialog)
        self.mapPoint1FromMapButton.setObjectName(_fromUtf8("mapPoint1FromMapButton"))
        self.gridLayout.addWidget(self.mapPoint1FromMapButton, 5, 3, 1, 1)
        self.mapPoint2Label = QtGui.QLabel(CreateGridDialog)
        self.mapPoint2Label.setObjectName(_fromUtf8("mapPoint2Label"))
        self.gridLayout.addWidget(self.mapPoint2Label, 7, 0, 1, 1)
        self.localOriginEastingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localOriginEastingSpin.setMaximum(9999)
        self.localOriginEastingSpin.setSingleStep(5)
        self.localOriginEastingSpin.setProperty("value", 100)
        self.localOriginEastingSpin.setObjectName(_fromUtf8("localOriginEastingSpin"))
        self.gridLayout.addWidget(self.localOriginEastingSpin, 11, 1, 1, 1)
        self.localOriginLabel = QtGui.QLabel(CreateGridDialog)
        self.localOriginLabel.setObjectName(_fromUtf8("localOriginLabel"))
        self.gridLayout.addWidget(self.localOriginLabel, 11, 0, 1, 1)
        self.localOriginNorthingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localOriginNorthingSpin.setMaximum(9999)
        self.localOriginNorthingSpin.setSingleStep(5)
        self.localOriginNorthingSpin.setProperty("value", 200)
        self.localOriginNorthingSpin.setObjectName(_fromUtf8("localOriginNorthingSpin"))
        self.gridLayout.addWidget(self.localOriginNorthingSpin, 11, 2, 1, 1)
        self.mapPoint2FromMapButton = QtGui.QPushButton(CreateGridDialog)
        self.mapPoint2FromMapButton.setObjectName(_fromUtf8("mapPoint2FromMapButton"))
        self.gridLayout.addWidget(self.mapPoint2FromMapButton, 7, 3, 1, 1)
        self.spacerLabel2 = QtGui.QLabel(CreateGridDialog)
        self.spacerLabel2.setText(_fromUtf8(""))
        self.spacerLabel2.setObjectName(_fromUtf8("spacerLabel2"))
        self.gridLayout.addWidget(self.spacerLabel2, 9, 0, 1, 1)
        self.mapPoint2EastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.mapPoint2EastingSpin.setDecimals(3)
        self.mapPoint2EastingSpin.setMaximum(999999.999)
        self.mapPoint2EastingSpin.setObjectName(_fromUtf8("mapPoint2EastingSpin"))
        self.gridLayout.addWidget(self.mapPoint2EastingSpin, 7, 1, 1, 1)
        self.mapPoint2NorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.mapPoint2NorthingSpin.setDecimals(3)
        self.mapPoint2NorthingSpin.setMaximum(999999.999)
        self.mapPoint2NorthingSpin.setObjectName(_fromUtf8("mapPoint2NorthingSpin"))
        self.gridLayout.addWidget(self.mapPoint2NorthingSpin, 7, 2, 1, 1)
        self.mapPoint1NorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.mapPoint1NorthingSpin.setDecimals(3)
        self.mapPoint1NorthingSpin.setMaximum(999999.999)
        self.mapPoint1NorthingSpin.setObjectName(_fromUtf8("mapPoint1NorthingSpin"))
        self.gridLayout.addWidget(self.mapPoint1NorthingSpin, 5, 2, 1, 1)
        self.mapPoint1EastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.mapPoint1EastingSpin.setDecimals(3)
        self.mapPoint1EastingSpin.setMaximum(999999.999)
        self.mapPoint1EastingSpin.setObjectName(_fromUtf8("mapPoint1EastingSpin"))
        self.gridLayout.addWidget(self.mapPoint1EastingSpin, 5, 1, 1, 1)
        self.localTerminusNorthingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localTerminusNorthingSpin.setMaximum(9999)
        self.localTerminusNorthingSpin.setSingleStep(5)
        self.localTerminusNorthingSpin.setProperty("value", 300)
        self.localTerminusNorthingSpin.setObjectName(_fromUtf8("localTerminusNorthingSpin"))
        self.gridLayout.addWidget(self.localTerminusNorthingSpin, 12, 2, 1, 1)
        self.methodLabel = QtGui.QLabel(CreateGridDialog)
        self.methodLabel.setObjectName(_fromUtf8("methodLabel"))
        self.gridLayout.addWidget(self.methodLabel, 2, 0, 1, 1)
        self.methodCombo = QtGui.QComboBox(CreateGridDialog)
        self.methodCombo.setObjectName(_fromUtf8("methodCombo"))
        self.methodCombo.addItem(_fromUtf8(""))
        self.methodCombo.addItem(_fromUtf8(""))
        self.methodCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.methodCombo, 2, 1, 1, 3)
        self.localPoint1NorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.localPoint1NorthingSpin.setDecimals(3)
        self.localPoint1NorthingSpin.setMaximum(999999.999)
        self.localPoint1NorthingSpin.setObjectName(_fromUtf8("localPoint1NorthingSpin"))
        self.gridLayout.addWidget(self.localPoint1NorthingSpin, 6, 2, 1, 1)
        self.mapNorthingLabel = QtGui.QLabel(CreateGridDialog)
        self.mapNorthingLabel.setObjectName(_fromUtf8("mapNorthingLabel"))
        self.gridLayout.addWidget(self.mapNorthingLabel, 4, 2, 1, 1)
        self.localPoint2NorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.localPoint2NorthingSpin.setDecimals(3)
        self.localPoint2NorthingSpin.setMaximum(999999.999)
        self.localPoint2NorthingSpin.setObjectName(_fromUtf8("localPoint2NorthingSpin"))
        self.gridLayout.addWidget(self.localPoint2NorthingSpin, 8, 2, 1, 1)
        self.localPoint1EastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.localPoint1EastingSpin.setDecimals(3)
        self.localPoint1EastingSpin.setMaximum(999999.999)
        self.localPoint1EastingSpin.setObjectName(_fromUtf8("localPoint1EastingSpin"))
        self.gridLayout.addWidget(self.localPoint1EastingSpin, 6, 1, 1, 1)
        self.localPoint2EastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.localPoint2EastingSpin.setDecimals(3)
        self.localPoint2EastingSpin.setMaximum(999999.999)
        self.localPoint2EastingSpin.setObjectName(_fromUtf8("localPoint2EastingSpin"))
        self.gridLayout.addWidget(self.localPoint2EastingSpin, 8, 1, 1, 1)
        self.gridNameLabel = QtGui.QLabel(CreateGridDialog)
        self.gridNameLabel.setObjectName(_fromUtf8("gridNameLabel"))
        self.gridLayout.addWidget(self.gridNameLabel, 1, 0, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(CreateGridDialog)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.gridLayout.addWidget(self.siteCodeLabel, 0, 0, 1, 1)
        self.mapEastingLabel = QtGui.QLabel(CreateGridDialog)
        self.mapEastingLabel.setObjectName(_fromUtf8("mapEastingLabel"))
        self.gridLayout.addWidget(self.mapEastingLabel, 4, 1, 1, 1)
        self.localPoint1Label = QtGui.QLabel(CreateGridDialog)
        self.localPoint1Label.setObjectName(_fromUtf8("localPoint1Label"))
        self.gridLayout.addWidget(self.localPoint1Label, 6, 0, 1, 1)
        self.gridNameEdit = QtGui.QLineEdit(CreateGridDialog)
        self.gridNameEdit.setObjectName(_fromUtf8("gridNameEdit"))
        self.gridLayout.addWidget(self.gridNameEdit, 1, 1, 1, 3)
        self.spacerLabel1 = QtGui.QLabel(CreateGridDialog)
        self.spacerLabel1.setText(_fromUtf8(""))
        self.spacerLabel1.setObjectName(_fromUtf8("spacerLabel1"))
        self.gridLayout.addWidget(self.spacerLabel1, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtGui.QPushButton(CreateGridDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        self.createGridButton = QtGui.QPushButton(CreateGridDialog)
        self.createGridButton.setDefault(True)
        self.createGridButton.setObjectName(_fromUtf8("createGridButton"))
        self.horizontalLayout.addWidget(self.createGridButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.localPoint2Label.setBuddy(self.localPoint2EastingSpin)
        self.mapPoint1Label.setBuddy(self.mapPoint1EastingSpin)
        self.localTerminusLabel.setBuddy(self.localTerminusEastingSpin)
        self.localIntervalLabel.setBuddy(self.localEastingIntervalSpin)
        self.mapPoint2Label.setBuddy(self.mapPoint2EastingSpin)
        self.localOriginLabel.setBuddy(self.localOriginEastingSpin)
        self.methodLabel.setBuddy(self.methodCombo)
        self.gridNameLabel.setBuddy(self.gridNameEdit)
        self.siteCodeLabel.setBuddy(self.siteCodeEdit)
        self.localPoint1Label.setBuddy(self.localPoint1EastingSpin)

        self.retranslateUi(CreateGridDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateGridDialog)
        CreateGridDialog.setTabOrder(self.siteCodeEdit, self.gridNameEdit)
        CreateGridDialog.setTabOrder(self.gridNameEdit, self.methodCombo)
        CreateGridDialog.setTabOrder(self.methodCombo, self.mapPoint1EastingSpin)
        CreateGridDialog.setTabOrder(self.mapPoint1EastingSpin, self.mapPoint1NorthingSpin)
        CreateGridDialog.setTabOrder(self.mapPoint1NorthingSpin, self.mapPoint1FromMapButton)
        CreateGridDialog.setTabOrder(self.mapPoint1FromMapButton, self.localPoint1EastingSpin)
        CreateGridDialog.setTabOrder(self.localPoint1EastingSpin, self.localPoint1NorthingSpin)
        CreateGridDialog.setTabOrder(self.localPoint1NorthingSpin, self.mapPoint2EastingSpin)
        CreateGridDialog.setTabOrder(self.mapPoint2EastingSpin, self.mapPoint2NorthingSpin)
        CreateGridDialog.setTabOrder(self.mapPoint2NorthingSpin, self.mapPoint2FromMapButton)
        CreateGridDialog.setTabOrder(self.mapPoint2FromMapButton, self.localPoint2EastingSpin)
        CreateGridDialog.setTabOrder(self.localPoint2EastingSpin, self.localPoint2NorthingSpin)
        CreateGridDialog.setTabOrder(self.localPoint2NorthingSpin, self.localOriginEastingSpin)
        CreateGridDialog.setTabOrder(self.localOriginEastingSpin, self.localOriginNorthingSpin)
        CreateGridDialog.setTabOrder(self.localOriginNorthingSpin, self.localTerminusEastingSpin)
        CreateGridDialog.setTabOrder(self.localTerminusEastingSpin, self.localTerminusNorthingSpin)
        CreateGridDialog.setTabOrder(self.localTerminusNorthingSpin, self.localEastingIntervalSpin)
        CreateGridDialog.setTabOrder(self.localEastingIntervalSpin, self.localNorthingIntervalSpin)
        CreateGridDialog.setTabOrder(self.localNorthingIntervalSpin, self.cancelButton)
        CreateGridDialog.setTabOrder(self.cancelButton, self.createGridButton)

    def retranslateUi(self, CreateGridDialog):
        CreateGridDialog.setWindowTitle(_translate("CreateGridDialog", "Create Grid", None))
        self.localNorthingLabel.setText(_translate("CreateGridDialog", "Local Northing", None))
        self.localPoint2Label.setText(_translate("CreateGridDialog", "Local Point 2:", None))
        self.localEastingIntervalSpin.setSuffix(_translate("CreateGridDialog", " m", None))
        self.mapPoint1Label.setText(_translate("CreateGridDialog", "Map Point 1:", None))
        self.localTerminusLabel.setText(_translate("CreateGridDialog", "Local Terminus:", None))
        self.localNorthingIntervalSpin.setSuffix(_translate("CreateGridDialog", " m", None))
        self.localIntervalLabel.setText(_translate("CreateGridDialog", "Grid Interval:", None))
        self.localEastingLabel.setText(_translate("CreateGridDialog", "Local Easting", None))
        self.mapPoint1FromMapButton.setText(_translate("CreateGridDialog", "From Map", None))
        self.mapPoint2Label.setText(_translate("CreateGridDialog", "Map Point 2:", None))
        self.localOriginLabel.setText(_translate("CreateGridDialog", "Local Origin:", None))
        self.mapPoint2FromMapButton.setText(_translate("CreateGridDialog", "From Map", None))
        self.methodLabel.setText(_translate("CreateGridDialog", "Method:", None))
        self.methodCombo.setItemText(0, _translate("CreateGridDialog", "Create from two known points", None))
        self.methodCombo.setItemText(1, _translate("CreateGridDialog", "Create from X axis baseline", None))
        self.methodCombo.setItemText(2, _translate("CreateGridDialog", "Create from Y axis baseline", None))
        self.mapNorthingLabel.setText(_translate("CreateGridDialog", "Northing", None))
        self.gridNameLabel.setText(_translate("CreateGridDialog", "Grid Name:", None))
        self.siteCodeLabel.setText(_translate("CreateGridDialog", "Site Code:", None))
        self.mapEastingLabel.setText(_translate("CreateGridDialog", "Easting", None))
        self.localPoint1Label.setText(_translate("CreateGridDialog", "Local Point 1:", None))
        self.cancelButton.setText(_translate("CreateGridDialog", "Cancel", None))
        self.createGridButton.setText(_translate("CreateGridDialog", "Create", None))

