# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grid/create_grid_dialog_base.ui'
#
# Created: Fri May 22 11:14:33 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreateGridDialog(object):
    def setupUi(self, CreateGridDialog):
        CreateGridDialog.setObjectName(_fromUtf8("CreateGridDialog"))
        CreateGridDialog.resize(461, 367)
        CreateGridDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtGui.QVBoxLayout(CreateGridDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.crsNorthingLabel = QtGui.QLabel(CreateGridDialog)
        self.crsNorthingLabel.setObjectName(_fromUtf8("crsNorthingLabel"))
        self.gridLayout.addWidget(self.crsNorthingLabel, 0, 2, 1, 1)
        self.localNorthingLabel = QtGui.QLabel(CreateGridDialog)
        self.localNorthingLabel.setObjectName(_fromUtf8("localNorthingLabel"))
        self.gridLayout.addWidget(self.localNorthingLabel, 5, 2, 1, 1)
        self.localEastingIntervalSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localEastingIntervalSpin.setMaximum(100)
        self.localEastingIntervalSpin.setSingleStep(5)
        self.localEastingIntervalSpin.setProperty("value", 5)
        self.localEastingIntervalSpin.setObjectName(_fromUtf8("localEastingIntervalSpin"))
        self.gridLayout.addWidget(self.localEastingIntervalSpin, 8, 1, 1, 1)
        self.localIntervalLabel = QtGui.QLabel(CreateGridDialog)
        self.localIntervalLabel.setObjectName(_fromUtf8("localIntervalLabel"))
        self.gridLayout.addWidget(self.localIntervalLabel, 8, 0, 1, 1)
        self.crsOnAxisLabel = QtGui.QLabel(CreateGridDialog)
        self.crsOnAxisLabel.setObjectName(_fromUtf8("crsOnAxisLabel"))
        self.gridLayout.addWidget(self.crsOnAxisLabel, 2, 0, 1, 1)
        self.localEastingLabel = QtGui.QLabel(CreateGridDialog)
        self.localEastingLabel.setObjectName(_fromUtf8("localEastingLabel"))
        self.gridLayout.addWidget(self.localEastingLabel, 5, 1, 1, 1)
        self.localTerminusEastingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localTerminusEastingSpin.setMaximum(9999)
        self.localTerminusEastingSpin.setSingleStep(5)
        self.localTerminusEastingSpin.setProperty("value", 200)
        self.localTerminusEastingSpin.setObjectName(_fromUtf8("localTerminusEastingSpin"))
        self.gridLayout.addWidget(self.localTerminusEastingSpin, 7, 1, 1, 1)
        self.crsOriginFromMapButton = QtGui.QPushButton(CreateGridDialog)
        self.crsOriginFromMapButton.setObjectName(_fromUtf8("crsOriginFromMapButton"))
        self.gridLayout.addWidget(self.crsOriginFromMapButton, 1, 3, 1, 1)
        self.crsAxisLabel = QtGui.QLabel(CreateGridDialog)
        self.crsAxisLabel.setObjectName(_fromUtf8("crsAxisLabel"))
        self.gridLayout.addWidget(self.crsAxisLabel, 3, 0, 1, 1)
        self.localOriginEastingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localOriginEastingSpin.setMaximum(9999)
        self.localOriginEastingSpin.setSingleStep(5)
        self.localOriginEastingSpin.setProperty("value", 100)
        self.localOriginEastingSpin.setObjectName(_fromUtf8("localOriginEastingSpin"))
        self.gridLayout.addWidget(self.localOriginEastingSpin, 6, 1, 1, 1)
        self.crsAxisNorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsAxisNorthingSpin.setDecimals(3)
        self.crsAxisNorthingSpin.setMaximum(999999.999)
        self.crsAxisNorthingSpin.setObjectName(_fromUtf8("crsAxisNorthingSpin"))
        self.gridLayout.addWidget(self.crsAxisNorthingSpin, 3, 2, 1, 1)
        self.crsOriginNorthingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsOriginNorthingSpin.setDecimals(3)
        self.crsOriginNorthingSpin.setMaximum(999999.999)
        self.crsOriginNorthingSpin.setObjectName(_fromUtf8("crsOriginNorthingSpin"))
        self.gridLayout.addWidget(self.crsOriginNorthingSpin, 1, 2, 1, 1)
        self.crsOriginEastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsOriginEastingSpin.setDecimals(3)
        self.crsOriginEastingSpin.setMaximum(999999.999)
        self.crsOriginEastingSpin.setObjectName(_fromUtf8("crsOriginEastingSpin"))
        self.gridLayout.addWidget(self.crsOriginEastingSpin, 1, 1, 1, 1)
        self.localTerminusNorthingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localTerminusNorthingSpin.setMaximum(9999)
        self.localTerminusNorthingSpin.setSingleStep(5)
        self.localTerminusNorthingSpin.setProperty("value", 300)
        self.localTerminusNorthingSpin.setObjectName(_fromUtf8("localTerminusNorthingSpin"))
        self.gridLayout.addWidget(self.localTerminusNorthingSpin, 7, 2, 1, 1)
        self.crsAxisEastingSpin = QtGui.QDoubleSpinBox(CreateGridDialog)
        self.crsAxisEastingSpin.setDecimals(3)
        self.crsAxisEastingSpin.setMaximum(999999.999)
        self.crsAxisEastingSpin.setObjectName(_fromUtf8("crsAxisEastingSpin"))
        self.gridLayout.addWidget(self.crsAxisEastingSpin, 3, 1, 1, 1)
        self.localOriginLabel = QtGui.QLabel(CreateGridDialog)
        self.localOriginLabel.setObjectName(_fromUtf8("localOriginLabel"))
        self.gridLayout.addWidget(self.localOriginLabel, 6, 0, 1, 1)
        self.crsAxisFromMapButton = QtGui.QPushButton(CreateGridDialog)
        self.crsAxisFromMapButton.setObjectName(_fromUtf8("crsAxisFromMapButton"))
        self.gridLayout.addWidget(self.crsAxisFromMapButton, 3, 3, 1, 1)
        self.localTerminusLabel = QtGui.QLabel(CreateGridDialog)
        self.localTerminusLabel.setObjectName(_fromUtf8("localTerminusLabel"))
        self.gridLayout.addWidget(self.localTerminusLabel, 7, 0, 1, 1)
        self.localOriginNorthingSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localOriginNorthingSpin.setMaximum(9999)
        self.localOriginNorthingSpin.setSingleStep(5)
        self.localOriginNorthingSpin.setProperty("value", 200)
        self.localOriginNorthingSpin.setObjectName(_fromUtf8("localOriginNorthingSpin"))
        self.gridLayout.addWidget(self.localOriginNorthingSpin, 6, 2, 1, 1)
        self.crsOriginLabel = QtGui.QLabel(CreateGridDialog)
        self.crsOriginLabel.setObjectName(_fromUtf8("crsOriginLabel"))
        self.gridLayout.addWidget(self.crsOriginLabel, 1, 0, 1, 1)
        self.crsOnAxisYButton = QtGui.QRadioButton(CreateGridDialog)
        self.crsOnAxisYButton.setObjectName(_fromUtf8("crsOnAxisYButton"))
        self.gridLayout.addWidget(self.crsOnAxisYButton, 2, 2, 1, 1)
        self.crsOnAxisXButton = QtGui.QRadioButton(CreateGridDialog)
        self.crsOnAxisXButton.setChecked(True)
        self.crsOnAxisXButton.setObjectName(_fromUtf8("crsOnAxisXButton"))
        self.gridLayout.addWidget(self.crsOnAxisXButton, 2, 1, 1, 1)
        self.crsEastingLabel = QtGui.QLabel(CreateGridDialog)
        self.crsEastingLabel.setObjectName(_fromUtf8("crsEastingLabel"))
        self.gridLayout.addWidget(self.crsEastingLabel, 0, 1, 1, 1)
        self.spacerLabel = QtGui.QLabel(CreateGridDialog)
        self.spacerLabel.setText(_fromUtf8(""))
        self.spacerLabel.setObjectName(_fromUtf8("spacerLabel"))
        self.gridLayout.addWidget(self.spacerLabel, 4, 0, 1, 1)
        self.localNorthingIntervalSpin = QtGui.QSpinBox(CreateGridDialog)
        self.localNorthingIntervalSpin.setMaximum(100)
        self.localNorthingIntervalSpin.setSingleStep(5)
        self.localNorthingIntervalSpin.setProperty("value", 5)
        self.localNorthingIntervalSpin.setObjectName(_fromUtf8("localNorthingIntervalSpin"))
        self.gridLayout.addWidget(self.localNorthingIntervalSpin, 8, 2, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(CreateGridDialog)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.gridLayout.addWidget(self.siteCodeLabel, 9, 0, 1, 1)
        self.siteCodeEdit = QtGui.QLineEdit(CreateGridDialog)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.gridLayout.addWidget(self.siteCodeEdit, 9, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtGui.QPushButton(CreateGridDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout.addWidget(self.cancelButton)
        self.createGridButton = QtGui.QPushButton(CreateGridDialog)
        self.createGridButton.setDefault(True)
        self.createGridButton.setObjectName(_fromUtf8("createGridButton"))
        self.horizontalLayout.addWidget(self.createGridButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.localIntervalLabel.setBuddy(self.localEastingIntervalSpin)
        self.crsOnAxisLabel.setBuddy(self.crsOnAxisXButton)
        self.crsAxisLabel.setBuddy(self.crsAxisEastingSpin)
        self.localOriginLabel.setBuddy(self.localOriginEastingSpin)
        self.localTerminusLabel.setBuddy(self.localTerminusEastingSpin)
        self.crsOriginLabel.setBuddy(self.crsOriginEastingSpin)

        self.retranslateUi(CreateGridDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateGridDialog)
        CreateGridDialog.setTabOrder(self.crsOriginEastingSpin, self.crsOriginNorthingSpin)
        CreateGridDialog.setTabOrder(self.crsOriginNorthingSpin, self.crsOriginFromMapButton)
        CreateGridDialog.setTabOrder(self.crsOriginFromMapButton, self.crsOnAxisXButton)
        CreateGridDialog.setTabOrder(self.crsOnAxisXButton, self.crsOnAxisYButton)
        CreateGridDialog.setTabOrder(self.crsOnAxisYButton, self.crsAxisEastingSpin)
        CreateGridDialog.setTabOrder(self.crsAxisEastingSpin, self.crsAxisNorthingSpin)
        CreateGridDialog.setTabOrder(self.crsAxisNorthingSpin, self.crsAxisFromMapButton)
        CreateGridDialog.setTabOrder(self.crsAxisFromMapButton, self.localOriginEastingSpin)
        CreateGridDialog.setTabOrder(self.localOriginEastingSpin, self.localOriginNorthingSpin)
        CreateGridDialog.setTabOrder(self.localOriginNorthingSpin, self.localTerminusEastingSpin)
        CreateGridDialog.setTabOrder(self.localTerminusEastingSpin, self.localTerminusNorthingSpin)
        CreateGridDialog.setTabOrder(self.localTerminusNorthingSpin, self.localEastingIntervalSpin)
        CreateGridDialog.setTabOrder(self.localEastingIntervalSpin, self.localNorthingIntervalSpin)
        CreateGridDialog.setTabOrder(self.localNorthingIntervalSpin, self.cancelButton)
        CreateGridDialog.setTabOrder(self.cancelButton, self.createGridButton)

    def retranslateUi(self, CreateGridDialog):
        CreateGridDialog.setWindowTitle(_translate("CreateGridDialog", "Create Grid", None))
        self.crsNorthingLabel.setText(_translate("CreateGridDialog", "CRS Northing", None))
        self.localNorthingLabel.setText(_translate("CreateGridDialog", "Local Northing", None))
        self.localEastingIntervalSpin.setSuffix(_translate("CreateGridDialog", " m", None))
        self.localIntervalLabel.setText(_translate("CreateGridDialog", "Grid Interval:", None))
        self.crsOnAxisLabel.setText(_translate("CreateGridDialog", "On Axis:", None))
        self.localEastingLabel.setText(_translate("CreateGridDialog", "Local Easting", None))
        self.crsOriginFromMapButton.setText(_translate("CreateGridDialog", "From Map", None))
        self.crsAxisLabel.setText(_translate("CreateGridDialog", "Axis Coordinates:", None))
        self.localOriginLabel.setText(_translate("CreateGridDialog", "Local Origin:", None))
        self.crsAxisFromMapButton.setText(_translate("CreateGridDialog", "From Map", None))
        self.localTerminusLabel.setText(_translate("CreateGridDialog", "Local Terminus:", None))
        self.crsOriginLabel.setText(_translate("CreateGridDialog", "Origin Coordinates:", None))
        self.crsOnAxisYButton.setText(_translate("CreateGridDialog", "Y", None))
        self.crsOnAxisXButton.setText(_translate("CreateGridDialog", "X", None))
        self.crsEastingLabel.setText(_translate("CreateGridDialog", "CRS Easting", None))
        self.localNorthingIntervalSpin.setSuffix(_translate("CreateGridDialog", " m", None))
        self.siteCodeLabel.setText(_translate("CreateGridDialog", "Site Code:", None))
        self.cancelButton.setText(_translate("CreateGridDialog", "Cancel", None))
        self.createGridButton.setText(_translate("CreateGridDialog", "Create", None))

