# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grid/grid_dock_base.ui'
#
# Created: Thu Jul 16 15:52:39 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GridDock(object):
    def setupUi(self, GridDock):
        GridDock.setObjectName(_fromUtf8("GridDock"))
        GridDock.resize(329, 174)
        self.GridDockContents = QtGui.QWidget()
        self.GridDockContents.setObjectName(_fromUtf8("GridDockContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.GridDockContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.createGridTool = QtGui.QToolButton(self.GridDockContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/get-hot-new-stuff.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createGridTool.setIcon(icon)
        self.createGridTool.setObjectName(_fromUtf8("createGridTool"))
        self.horizontalLayout.addWidget(self.createGridTool)
        self.identifyGridTool = QtGui.QToolButton(self.GridDockContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/snap-orthogonal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.identifyGridTool.setIcon(icon1)
        self.identifyGridTool.setObjectName(_fromUtf8("identifyGridTool"))
        self.horizontalLayout.addWidget(self.identifyGridTool)
        self.pasteMapPointTool = QtGui.QToolButton(self.GridDockContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/mActionEditPaste.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasteMapPointTool.setIcon(icon2)
        self.pasteMapPointTool.setObjectName(_fromUtf8("pasteMapPointTool"))
        self.horizontalLayout.addWidget(self.pasteMapPointTool)
        self.panToTool = QtGui.QToolButton(self.GridDockContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/mActionPanToSelected.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panToTool.setIcon(icon3)
        self.panToTool.setObjectName(_fromUtf8("panToTool"))
        self.horizontalLayout.addWidget(self.panToTool)
        self.addMapPointTool = QtGui.QToolButton(self.GridDockContents)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/mActionCapturePoint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addMapPointTool.setIcon(icon4)
        self.addMapPointTool.setObjectName(_fromUtf8("addMapPointTool"))
        self.horizontalLayout.addWidget(self.addMapPointTool)
        self.updateLayerTool = QtGui.QToolButton(self.GridDockContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/mActionNewAttribute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateLayerTool.setIcon(icon5)
        self.updateLayerTool.setObjectName(_fromUtf8("updateLayerTool"))
        self.horizontalLayout.addWidget(self.updateLayerTool)
        self.translateFeaturesTool = QtGui.QToolButton(self.GridDockContents)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/mActionMoveFeature.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.translateFeaturesTool.setIcon(icon6)
        self.translateFeaturesTool.setObjectName(_fromUtf8("translateFeaturesTool"))
        self.horizontalLayout.addWidget(self.translateFeaturesTool)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mapLabel = QtGui.QLabel(self.GridDockContents)
        self.mapLabel.setObjectName(_fromUtf8("mapLabel"))
        self.gridLayout.addWidget(self.mapLabel, 0, 0, 1, 1)
        self.mapEastingSpin = QtGui.QDoubleSpinBox(self.GridDockContents)
        self.mapEastingSpin.setReadOnly(True)
        self.mapEastingSpin.setPrefix(_fromUtf8(""))
        self.mapEastingSpin.setSuffix(_fromUtf8(""))
        self.mapEastingSpin.setDecimals(3)
        self.mapEastingSpin.setMaximum(999999.999)
        self.mapEastingSpin.setObjectName(_fromUtf8("mapEastingSpin"))
        self.gridLayout.addWidget(self.mapEastingSpin, 0, 1, 1, 1)
        self.mapNorthingSpin = QtGui.QDoubleSpinBox(self.GridDockContents)
        self.mapNorthingSpin.setReadOnly(True)
        self.mapNorthingSpin.setDecimals(3)
        self.mapNorthingSpin.setMaximum(999999.999)
        self.mapNorthingSpin.setObjectName(_fromUtf8("mapNorthingSpin"))
        self.gridLayout.addWidget(self.mapNorthingSpin, 0, 2, 1, 1)
        self.localLabel = QtGui.QLabel(self.GridDockContents)
        self.localLabel.setObjectName(_fromUtf8("localLabel"))
        self.gridLayout.addWidget(self.localLabel, 1, 0, 1, 1)
        self.localEastingSpin = QtGui.QDoubleSpinBox(self.GridDockContents)
        self.localEastingSpin.setReadOnly(True)
        self.localEastingSpin.setDecimals(3)
        self.localEastingSpin.setMaximum(9999.99)
        self.localEastingSpin.setObjectName(_fromUtf8("localEastingSpin"))
        self.gridLayout.addWidget(self.localEastingSpin, 1, 1, 1, 1)
        self.localNorthingSpin = QtGui.QDoubleSpinBox(self.GridDockContents)
        self.localNorthingSpin.setReadOnly(True)
        self.localNorthingSpin.setDecimals(3)
        self.localNorthingSpin.setMaximum(9999.99)
        self.localNorthingSpin.setObjectName(_fromUtf8("localNorthingSpin"))
        self.gridLayout.addWidget(self.localNorthingSpin, 1, 2, 1, 1)
        self.copyLocalPointTool = QtGui.QToolButton(self.GridDockContents)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkGrid/mActionEditCopy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyLocalPointTool.setIcon(icon7)
        self.copyLocalPointTool.setObjectName(_fromUtf8("copyLocalPointTool"))
        self.gridLayout.addWidget(self.copyLocalPointTool, 1, 3, 1, 1)
        self.copyMapPointTool = QtGui.QToolButton(self.GridDockContents)
        self.copyMapPointTool.setIcon(icon7)
        self.copyMapPointTool.setObjectName(_fromUtf8("copyMapPointTool"))
        self.gridLayout.addWidget(self.copyMapPointTool, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 4, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        GridDock.setWidget(self.GridDockContents)
        self.createGridAction = QtGui.QAction(GridDock)
        self.createGridAction.setIcon(icon)
        self.createGridAction.setObjectName(_fromUtf8("createGridAction"))
        self.identifyGridAction = QtGui.QAction(GridDock)
        self.identifyGridAction.setCheckable(True)
        self.identifyGridAction.setIcon(icon1)
        self.identifyGridAction.setObjectName(_fromUtf8("identifyGridAction"))
        self.updateLayerAction = QtGui.QAction(GridDock)
        self.updateLayerAction.setIcon(icon5)
        self.updateLayerAction.setObjectName(_fromUtf8("updateLayerAction"))
        self.copyMapPointAction = QtGui.QAction(GridDock)
        self.copyMapPointAction.setIcon(icon7)
        self.copyMapPointAction.setObjectName(_fromUtf8("copyMapPointAction"))
        self.pasteMapPointAction = QtGui.QAction(GridDock)
        self.pasteMapPointAction.setIcon(icon2)
        self.pasteMapPointAction.setObjectName(_fromUtf8("pasteMapPointAction"))
        self.copyLocalPointAction = QtGui.QAction(GridDock)
        self.copyLocalPointAction.setIcon(icon7)
        self.copyLocalPointAction.setObjectName(_fromUtf8("copyLocalPointAction"))
        self.pasteLocalPointAction = QtGui.QAction(GridDock)
        self.pasteLocalPointAction.setIcon(icon2)
        self.pasteLocalPointAction.setObjectName(_fromUtf8("pasteLocalPointAction"))
        self.addMapPointAction = QtGui.QAction(GridDock)
        self.addMapPointAction.setIcon(icon4)
        self.addMapPointAction.setObjectName(_fromUtf8("addMapPointAction"))
        self.panToAction = QtGui.QAction(GridDock)
        self.panToAction.setIcon(icon4)
        self.panToAction.setObjectName(_fromUtf8("panToAction"))
        self.translateFeaturesAction = QtGui.QAction(GridDock)
        self.translateFeaturesAction.setIcon(icon6)
        self.translateFeaturesAction.setObjectName(_fromUtf8("translateFeaturesAction"))
        self.mapLabel.setBuddy(self.mapEastingSpin)
        self.localLabel.setBuddy(self.localEastingSpin)

        self.retranslateUi(GridDock)
        QtCore.QMetaObject.connectSlotsByName(GridDock)

    def retranslateUi(self, GridDock):
        GridDock.setWindowTitle(_translate("GridDock", "Local Grid", None))
        self.createGridTool.setText(_translate("GridDock", "...", None))
        self.identifyGridTool.setText(_translate("GridDock", "...", None))
        self.pasteMapPointTool.setText(_translate("GridDock", "...", None))
        self.panToTool.setText(_translate("GridDock", "...", None))
        self.addMapPointTool.setText(_translate("GridDock", "...", None))
        self.updateLayerTool.setText(_translate("GridDock", "...", None))
        self.translateFeaturesTool.setText(_translate("GridDock", "...", None))
        self.mapLabel.setText(_translate("GridDock", "Map:", None))
        self.localLabel.setText(_translate("GridDock", "Local:", None))
        self.copyLocalPointTool.setText(_translate("GridDock", "...", None))
        self.copyMapPointTool.setText(_translate("GridDock", "...", None))
        self.createGridAction.setText(_translate("GridDock", "New", None))
        self.createGridAction.setToolTip(_translate("GridDock", "Create New Grid", None))
        self.identifyGridAction.setText(_translate("GridDock", "Identify", None))
        self.identifyGridAction.setToolTip(_translate("GridDock", "Identify Grid Coordinates", None))
        self.updateLayerAction.setText(_translate("GridDock", "Update", None))
        self.updateLayerAction.setToolTip(_translate("GridDock", "Update Layer Coordinates", None))
        self.copyMapPointAction.setText(_translate("GridDock", "Copy", None))
        self.copyMapPointAction.setToolTip(_translate("GridDock", "Copy Map Point", None))
        self.pasteMapPointAction.setText(_translate("GridDock", "Paste", None))
        self.pasteMapPointAction.setToolTip(_translate("GridDock", "Paste Map Point", None))
        self.copyLocalPointAction.setText(_translate("GridDock", "Copy", None))
        self.copyLocalPointAction.setToolTip(_translate("GridDock", "Copy Local Point", None))
        self.pasteLocalPointAction.setText(_translate("GridDock", "Paste", None))
        self.pasteLocalPointAction.setToolTip(_translate("GridDock", "Paste Local Point", None))
        self.addMapPointAction.setText(_translate("GridDock", "Add to Layer", None))
        self.addMapPointAction.setToolTip(_translate("GridDock", "Add point to current layer", None))
        self.panToAction.setText(_translate("GridDock", "Pan", None))
        self.panToAction.setToolTip(_translate("GridDock", "Pan to map point", None))
        self.translateFeaturesAction.setText(_translate("GridDock", "Translate", None))
        self.translateFeaturesAction.setToolTip(_translate("GridDock", "Translate features", None))

from ..arklib.dock import ArkDockWidget
import resources_rc
