# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'georef/georef_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GeorefDialogBase(object):
    def setupUi(self, GeorefDialogBase):
        GeorefDialogBase.setObjectName(_fromUtf8("GeorefDialogBase"))
        GeorefDialogBase.resize(1300, 1000)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeorefDialogBase.sizePolicy().hasHeightForWidth())
        GeorefDialogBase.setSizePolicy(sizePolicy)
        GeorefDialogBase.setMinimumSize(QtCore.QSize(1300, 1000))
        GeorefDialogBase.setMaximumSize(QtCore.QSize(1300, 1000))
        self.verticalLayout = QtGui.QVBoxLayout(GeorefDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(GeorefDialogBase)
        self.splitter.setEnabled(True)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.planView = QtGui.QGraphicsView(self.layoutWidget)
        self.planView.setMinimumSize(QtCore.QSize(300, 320))
        self.planView.setMaximumSize(QtCore.QSize(300, 320))
        self.planView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.planView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.planView.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.planView.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)
        self.planView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.planView.setObjectName(_fromUtf8("planView"))
        self.verticalLayout_4.addWidget(self.planView, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.m_fileLabel = QtGui.QLabel(self.layoutWidget)
        self.m_fileLabel.setObjectName(_fromUtf8("m_fileLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.m_fileLabel)
        self.m_fileEdit = QtGui.QLineEdit(self.layoutWidget)
        self.m_fileEdit.setReadOnly(True)
        self.m_fileEdit.setObjectName(_fromUtf8("m_fileEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.m_fileEdit)
        self.m_siteLabel = QtGui.QLabel(self.layoutWidget)
        self.m_siteLabel.setObjectName(_fromUtf8("m_siteLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.m_siteLabel)
        self.m_siteEdit = QtGui.QLineEdit(self.layoutWidget)
        self.m_siteEdit.setReadOnly(False)
        self.m_siteEdit.setObjectName(_fromUtf8("m_siteEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.m_siteEdit)
        self.m_typeLabel = QtGui.QLabel(self.layoutWidget)
        self.m_typeLabel.setObjectName(_fromUtf8("m_typeLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.m_typeLabel)
        self.m_typeCombo = QtGui.QComboBox(self.layoutWidget)
        self.m_typeCombo.setEditable(False)
        self.m_typeCombo.setObjectName(_fromUtf8("m_typeCombo"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.m_typeCombo)
        self.m_contextLabel = QtGui.QLabel(self.layoutWidget)
        self.m_contextLabel.setObjectName(_fromUtf8("m_contextLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.m_contextLabel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.m_numberSpin = QtGui.QSpinBox(self.layoutWidget)
        self.m_numberSpin.setReadOnly(False)
        self.m_numberSpin.setMaximum(9999)
        self.m_numberSpin.setObjectName(_fromUtf8("m_numberSpin"))
        self.horizontalLayout_4.addWidget(self.m_numberSpin)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.m_gridLabel = QtGui.QLabel(self.layoutWidget)
        self.m_gridLabel.setObjectName(_fromUtf8("m_gridLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.m_gridLabel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.m_eastSpin = QtGui.QSpinBox(self.layoutWidget)
        self.m_eastSpin.setReadOnly(False)
        self.m_eastSpin.setMaximum(9999)
        self.m_eastSpin.setSingleStep(5)
        self.m_eastSpin.setObjectName(_fromUtf8("m_eastSpin"))
        self.horizontalLayout_6.addWidget(self.m_eastSpin)
        self.m_northSpin = QtGui.QSpinBox(self.layoutWidget)
        self.m_northSpin.setReadOnly(False)
        self.m_northSpin.setMaximum(9999)
        self.m_northSpin.setSingleStep(5)
        self.m_northSpin.setObjectName(_fromUtf8("m_northSpin"))
        self.horizontalLayout_6.addWidget(self.m_northSpin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.m_suffixLabel = QtGui.QLabel(self.layoutWidget)
        self.m_suffixLabel.setObjectName(_fromUtf8("m_suffixLabel"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.m_suffixLabel)
        self.m_suffixEdit = QtGui.QLineEdit(self.layoutWidget)
        self.m_suffixEdit.setMaxLength(1)
        self.m_suffixEdit.setObjectName(_fromUtf8("m_suffixEdit"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.m_suffixEdit)
        self.scaleLabel = QtGui.QLabel(self.layoutWidget)
        self.scaleLabel.setObjectName(_fromUtf8("scaleLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.scaleLabel)
        self.scaleCombo = QtGui.QComboBox(self.layoutWidget)
        self.scaleCombo.setObjectName(_fromUtf8("scaleCombo"))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.scaleCombo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.scaleCombo)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.m_runButton = QtGui.QPushButton(self.layoutWidget)
        self.m_runButton.setObjectName(_fromUtf8("m_runButton"))
        self.horizontalLayout_5.addWidget(self.m_runButton)
        self.m_closeButton = QtGui.QPushButton(self.layoutWidget)
        self.m_closeButton.setObjectName(_fromUtf8("m_closeButton"))
        self.horizontalLayout_5.addWidget(self.m_closeButton)
        self.m_runCloseButton = QtGui.QPushButton(self.layoutWidget)
        self.m_runCloseButton.setDefault(True)
        self.m_runCloseButton.setObjectName(_fromUtf8("m_runCloseButton"))
        self.horizontalLayout_5.addWidget(self.m_runCloseButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 1, 1, 1)
        self.translateStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.translateStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.translateStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.translateStatusLabel.setText(_fromUtf8(""))
        self.translateStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.translateStatusLabel.setObjectName(_fromUtf8("translateStatusLabel"))
        self.gridLayout_3.addWidget(self.translateStatusLabel, 2, 0, 1, 1)
        self.cropStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.cropStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.cropStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.cropStatusLabel.setText(_fromUtf8(""))
        self.cropStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.cropStatusLabel.setObjectName(_fromUtf8("cropStatusLabel"))
        self.gridLayout_3.addWidget(self.cropStatusLabel, 1, 0, 1, 1)
        self.warpStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.warpStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.warpStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.warpStatusLabel.setText(_fromUtf8(""))
        self.warpStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.warpStatusLabel.setObjectName(_fromUtf8("warpStatusLabel"))
        self.gridLayout_3.addWidget(self.warpStatusLabel, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 1, 1, 1)
        self.loadStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.loadStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.loadStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.loadStatusLabel.setText(_fromUtf8(""))
        self.loadStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.loadStatusLabel.setObjectName(_fromUtf8("loadStatusLabel"))
        self.gridLayout_3.addWidget(self.loadStatusLabel, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 4, 1, 1, 1)
        self.overviewStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.overviewStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.overviewStatusLabel.setBaseSize(QtCore.QSize(16, 16))
        self.overviewStatusLabel.setText(_fromUtf8(""))
        self.overviewStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/georef/unknown.png")))
        self.overviewStatusLabel.setObjectName(_fromUtf8("overviewStatusLabel"))
        self.gridLayout_3.addWidget(self.overviewStatusLabel, 4, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.m_progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.m_progressBar.setProperty("value", 0)
        self.m_progressBar.setObjectName(_fromUtf8("m_progressBar"))
        self.verticalLayout_4.addWidget(self.m_progressBar)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.statusBar = QtGui.QStatusBar(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.verticalLayout_4.addWidget(self.statusBar)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.headerView = QtGui.QGraphicsView(self.layoutWidget1)
        self.headerView.setMinimumSize(QtCore.QSize(900, 50))
        self.headerView.setMaximumSize(QtCore.QSize(16777215, 50))
        self.headerView.setAcceptDrops(False)
        self.headerView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.headerView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.headerView.setInteractive(False)
        self.headerView.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.headerView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.headerView.setObjectName(_fromUtf8("headerView"))
        self.gridLayout.addWidget(self.headerView, 0, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gcpWidget1 = GcpWidget(self.layoutWidget1)
        self.gcpWidget1.setObjectName(_fromUtf8("gcpWidget1"))
        self.gridLayout.addWidget(self.gcpWidget1, 1, 0, 1, 1)
        self.gcpWidget4 = GcpWidget(self.layoutWidget1)
        self.gcpWidget4.setObjectName(_fromUtf8("gcpWidget4"))
        self.gridLayout.addWidget(self.gcpWidget4, 1, 1, 1, 1)
        self.gcpWidget2 = GcpWidget(self.layoutWidget1)
        self.gcpWidget2.setObjectName(_fromUtf8("gcpWidget2"))
        self.gridLayout.addWidget(self.gcpWidget2, 2, 0, 1, 1)
        self.gcpWidget3 = GcpWidget(self.layoutWidget1)
        self.gcpWidget3.setObjectName(_fromUtf8("gcpWidget3"))
        self.gridLayout.addWidget(self.gcpWidget3, 2, 1, 1, 1)
        self.footerView = QtGui.QGraphicsView(self.layoutWidget1)
        self.footerView.setMinimumSize(QtCore.QSize(900, 150))
        self.footerView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.footerView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.footerView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.footerView.setInteractive(False)
        self.footerView.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.footerView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.footerView.setObjectName(_fromUtf8("footerView"))
        self.gridLayout.addWidget(self.footerView, 3, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.splitter)
        self.m_fileLabel.setBuddy(self.m_fileEdit)
        self.m_siteLabel.setBuddy(self.m_siteEdit)
        self.m_typeLabel.setBuddy(self.m_typeCombo)
        self.m_contextLabel.setBuddy(self.m_numberSpin)
        self.m_gridLabel.setBuddy(self.m_eastSpin)
        self.m_suffixLabel.setBuddy(self.m_suffixEdit)
        self.scaleLabel.setBuddy(self.scaleCombo)

        self.retranslateUi(GeorefDialogBase)
        QtCore.QMetaObject.connectSlotsByName(GeorefDialogBase)
        GeorefDialogBase.setTabOrder(self.planView, self.m_fileEdit)
        GeorefDialogBase.setTabOrder(self.m_fileEdit, self.m_siteEdit)
        GeorefDialogBase.setTabOrder(self.m_siteEdit, self.m_typeCombo)
        GeorefDialogBase.setTabOrder(self.m_typeCombo, self.scaleCombo)
        GeorefDialogBase.setTabOrder(self.scaleCombo, self.m_numberSpin)
        GeorefDialogBase.setTabOrder(self.m_numberSpin, self.m_eastSpin)
        GeorefDialogBase.setTabOrder(self.m_eastSpin, self.m_northSpin)
        GeorefDialogBase.setTabOrder(self.m_northSpin, self.m_suffixEdit)
        GeorefDialogBase.setTabOrder(self.m_suffixEdit, self.m_runCloseButton)
        GeorefDialogBase.setTabOrder(self.m_runCloseButton, self.m_runButton)
        GeorefDialogBase.setTabOrder(self.m_runButton, self.m_closeButton)

    def retranslateUi(self, GeorefDialogBase):
        GeorefDialogBase.setWindowTitle(_translate("GeorefDialogBase", "Grid Georeferencer", None))
        self.m_fileLabel.setText(_translate("GeorefDialogBase", "Plan file:", None))
        self.m_siteLabel.setText(_translate("GeorefDialogBase", "Site:", None))
        self.m_typeLabel.setText(_translate("GeorefDialogBase", "Type:", None))
        self.m_contextLabel.setText(_translate("GeorefDialogBase", "Number:", None))
        self.m_numberSpin.setToolTip(_translate("GeorefDialogBase", "Context Number", None))
        self.m_gridLabel.setText(_translate("GeorefDialogBase", "Grid:", None))
        self.m_suffixLabel.setText(_translate("GeorefDialogBase", "Suffix:", None))
        self.scaleLabel.setText(_translate("GeorefDialogBase", "Scale:", None))
        self.scaleCombo.setItemText(0, _translate("GeorefDialogBase", "1:20 (5m)", None))
        self.scaleCombo.setItemText(1, _translate("GeorefDialogBase", "1:10 (2.5m)", None))
        self.m_runButton.setText(_translate("GeorefDialogBase", "Run", None))
        self.m_closeButton.setText(_translate("GeorefDialogBase", "Close", None))
        self.m_runCloseButton.setText(_translate("GeorefDialogBase", "Run and Close", None))
        self.label_5.setText(_translate("GeorefDialogBase", "Warp Image", None))
        self.label_2.setText(_translate("GeorefDialogBase", "Crop Image", None))
        self.label_4.setText(_translate("GeorefDialogBase", "Translate Image", None))
        self.label_3.setText(_translate("GeorefDialogBase", "Load Image", None))
        self.label_6.setText(_translate("GeorefDialogBase", "Generate Overviews", None))

from gcp_widget import GcpWidget
import resources_rc
