# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/plan_dock_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlanDockWidget(object):
    def setupUi(self, PlanDockWidget):
        PlanDockWidget.setObjectName(_fromUtf8("PlanDockWidget"))
        PlanDockWidget.resize(337, 434)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlanDockWidget.sizePolicy().hasHeightForWidth())
        PlanDockWidget.setSizePolicy(sizePolicy)
        self.PlanDockContents = QtGui.QWidget()
        self.PlanDockContents.setObjectName(_fromUtf8("PlanDockContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.PlanDockContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.PlanDockContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 313, 342))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.loadRawButton = QtGui.QPushButton(self.groupBox_2)
        self.loadRawButton.setObjectName(_fromUtf8("loadRawButton"))
        self.horizontalLayout_4.addWidget(self.loadRawButton)
        self.loadGeoButton = QtGui.QPushButton(self.groupBox_2)
        self.loadGeoButton.setObjectName(_fromUtf8("loadGeoButton"))
        self.horizontalLayout_4.addWidget(self.loadGeoButton)
        self.loadContextButton = QtGui.QPushButton(self.groupBox_2)
        self.loadContextButton.setObjectName(_fromUtf8("loadContextButton"))
        self.horizontalLayout_4.addWidget(self.loadContextButton)
        self.loadPlanButton = QtGui.QPushButton(self.groupBox_2)
        self.loadPlanButton.setObjectName(_fromUtf8("loadPlanButton"))
        self.horizontalLayout_4.addWidget(self.loadPlanButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.metadataWidget = MetadataWidget(self.scrollAreaWidgetContents)
        self.metadataWidget.setObjectName(_fromUtf8("metadataWidget"))
        self.gridLayout = QtGui.QGridLayout(self.metadataWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout.addWidget(self.metadataWidget)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.contextsTab = QtGui.QWidget()
        self.contextsTab.setObjectName(_fromUtf8("contextsTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.contextsTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.editPolygonsLabel = QtGui.QLabel(self.contextsTab)
        self.editPolygonsLabel.setObjectName(_fromUtf8("editPolygonsLabel"))
        self.gridLayout_4.addWidget(self.editPolygonsLabel, 4, 0, 1, 1)
        self.editLinesLabel = QtGui.QLabel(self.contextsTab)
        self.editLinesLabel.setObjectName(_fromUtf8("editLinesLabel"))
        self.gridLayout_4.addWidget(self.editLinesLabel, 3, 0, 1, 1)
        self.autoSchematicTool = QtGui.QToolButton(self.contextsTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/autoSchematic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoSchematicTool.setIcon(icon)
        self.autoSchematicTool.setObjectName(_fromUtf8("autoSchematicTool"))
        self.gridLayout_4.addWidget(self.autoSchematicTool, 1, 1, 1, 1)
        self.autoSchematiclLabel = QtGui.QLabel(self.contextsTab)
        self.autoSchematiclLabel.setObjectName(_fromUtf8("autoSchematiclLabel"))
        self.gridLayout_4.addWidget(self.autoSchematiclLabel, 1, 0, 1, 1)
        self.contextToolsLayout = QtGui.QGridLayout()
        self.contextToolsLayout.setObjectName(_fromUtf8("contextToolsLayout"))
        self.gridLayout_4.addLayout(self.contextToolsLayout, 0, 0, 1, 2)
        self.editPointsLabel = QtGui.QLabel(self.contextsTab)
        self.editPointsLabel.setObjectName(_fromUtf8("editPointsLabel"))
        self.gridLayout_4.addWidget(self.editPointsLabel, 2, 0, 1, 1)
        self.editPointsTool = QtGui.QToolButton(self.contextsTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/nodeTool.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPointsTool.setIcon(icon1)
        self.editPointsTool.setObjectName(_fromUtf8("editPointsTool"))
        self.gridLayout_4.addWidget(self.editPointsTool, 2, 1, 1, 1)
        self.editLinesTool = QtGui.QToolButton(self.contextsTab)
        self.editLinesTool.setIcon(icon1)
        self.editLinesTool.setObjectName(_fromUtf8("editLinesTool"))
        self.gridLayout_4.addWidget(self.editLinesTool, 3, 1, 1, 1)
        self.editPolygonsTool = QtGui.QToolButton(self.contextsTab)
        self.editPolygonsTool.setIcon(icon1)
        self.editPolygonsTool.setObjectName(_fromUtf8("editPolygonsTool"))
        self.gridLayout_4.addWidget(self.editPolygonsTool, 4, 1, 1, 1)
        self.tabWidget.addTab(self.contextsTab, _fromUtf8(""))
        self.featuresTab = QtGui.QWidget()
        self.featuresTab.setObjectName(_fromUtf8("featuresTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.featuresTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.featureNameEdit = QtGui.QLineEdit(self.featuresTab)
        self.featureNameEdit.setObjectName(_fromUtf8("featureNameEdit"))
        self.gridLayout_5.addWidget(self.featureNameEdit, 0, 1, 1, 1)
        self.featureToolsLayout = QtGui.QGridLayout()
        self.featureToolsLayout.setObjectName(_fromUtf8("featureToolsLayout"))
        self.gridLayout_5.addLayout(self.featureToolsLayout, 1, 0, 1, 2)
        self.featureNameLabel = QtGui.QLabel(self.featuresTab)
        self.featureNameLabel.setObjectName(_fromUtf8("featureNameLabel"))
        self.gridLayout_5.addWidget(self.featureNameLabel, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 1, 1, 1)
        self.tabWidget.addTab(self.featuresTab, _fromUtf8(""))
        self.sectionsTab = QtGui.QWidget()
        self.sectionsTab.setObjectName(_fromUtf8("sectionsTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.sectionsTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.sectionLabel = QtGui.QLabel(self.sectionsTab)
        self.sectionLabel.setObjectName(_fromUtf8("sectionLabel"))
        self.gridLayout_2.addWidget(self.sectionLabel, 0, 0, 1, 1)
        self.sectionToolsLayout = QtGui.QGridLayout()
        self.sectionToolsLayout.setObjectName(_fromUtf8("sectionToolsLayout"))
        self.gridLayout_2.addLayout(self.sectionToolsLayout, 1, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 103, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.sectionCombo = QtGui.QComboBox(self.sectionsTab)
        self.sectionCombo.setObjectName(_fromUtf8("sectionCombo"))
        self.gridLayout_2.addWidget(self.sectionCombo, 0, 2, 1, 2)
        self.tabWidget.addTab(self.sectionsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem2 = QtGui.QSpacerItem(17, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clearButton = QtGui.QPushButton(self.PlanDockContents)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout.addWidget(self.clearButton)
        self.mergeButton = QtGui.QPushButton(self.PlanDockContents)
        self.mergeButton.setObjectName(_fromUtf8("mergeButton"))
        self.horizontalLayout.addWidget(self.mergeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        PlanDockWidget.setWidget(self.PlanDockContents)
        self.featureNameLabel.setBuddy(self.featureNameEdit)

        self.retranslateUi(PlanDockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlanDockWidget)
        PlanDockWidget.setTabOrder(self.scrollArea, self.loadRawButton)
        PlanDockWidget.setTabOrder(self.loadRawButton, self.loadGeoButton)
        PlanDockWidget.setTabOrder(self.loadGeoButton, self.loadContextButton)
        PlanDockWidget.setTabOrder(self.loadContextButton, self.tabWidget)
        PlanDockWidget.setTabOrder(self.tabWidget, self.clearButton)
        PlanDockWidget.setTabOrder(self.clearButton, self.mergeButton)
        PlanDockWidget.setTabOrder(self.mergeButton, self.featureNameEdit)

    def retranslateUi(self, PlanDockWidget):
        PlanDockWidget.setWindowTitle(_translate("PlanDockWidget", "Draw Plans", None))
        self.groupBox_2.setTitle(_translate("PlanDockWidget", "Load Drawings", None))
        self.loadRawButton.setText(_translate("PlanDockWidget", "Raw", None))
        self.loadGeoButton.setText(_translate("PlanDockWidget", "Geo", None))
        self.loadContextButton.setText(_translate("PlanDockWidget", "Cxt", None))
        self.loadPlanButton.setText(_translate("PlanDockWidget", "Plan", None))
        self.editPolygonsLabel.setText(_translate("PlanDockWidget", "Edit Polygon Features:", None))
        self.editLinesLabel.setText(_translate("PlanDockWidget", "Edit Line Features:", None))
        self.autoSchematicTool.setToolTip(_translate("PlanDockWidget", "<html><head/><body><p>Auto Schematic</p></body></html>", None))
        self.autoSchematicTool.setText(_translate("PlanDockWidget", "...", None))
        self.autoSchematiclLabel.setText(_translate("PlanDockWidget", "Auto Schematic:", None))
        self.editPointsLabel.setText(_translate("PlanDockWidget", "Edit Point Features:", None))
        self.editPointsTool.setToolTip(_translate("PlanDockWidget", "<html><head/><body><p>Edit Point Features</p></body></html>", None))
        self.editPointsTool.setText(_translate("PlanDockWidget", "...", None))
        self.editLinesTool.setToolTip(_translate("PlanDockWidget", "<html><head/><body><p>Edit Line Features</p></body></html>", None))
        self.editLinesTool.setText(_translate("PlanDockWidget", "...", None))
        self.editPolygonsTool.setToolTip(_translate("PlanDockWidget", "<html><head/><body><p>Edit Polygon Features</p></body></html>", None))
        self.editPolygonsTool.setText(_translate("PlanDockWidget", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contextsTab), _translate("PlanDockWidget", "Contexts", None))
        self.featureNameLabel.setText(_translate("PlanDockWidget", "Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.featuresTab), _translate("PlanDockWidget", "Features", None))
        self.sectionLabel.setText(_translate("PlanDockWidget", "Section:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sectionsTab), _translate("PlanDockWidget", "Sections", None))
        self.clearButton.setToolTip(_translate("PlanDockWidget", "Clear unsaved changes from work layers", None))
        self.clearButton.setText(_translate("PlanDockWidget", "Clear", None))
        self.mergeButton.setToolTip(_translate("PlanDockWidget", "Move new context to main layers", None))
        self.mergeButton.setText(_translate("PlanDockWidget", "Merge", None))

from ..libarkqgis.dock import ArkDockWidget
from metadata_widget import MetadataWidget
import resources_rc
