# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/schematic_widget_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SchematicWidget(object):
    def setupUi(self, SchematicWidget):
        SchematicWidget.setObjectName(_fromUtf8("SchematicWidget"))
        SchematicWidget.resize(314, 711)
        self.gridLayout = QtGui.QGridLayout(SchematicWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(14, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.checkGroup = QtGui.QGroupBox(SchematicWidget)
        self.checkGroup.setObjectName(_fromUtf8("checkGroup"))
        self.gridLayout_6 = QtGui.QGridLayout(self.checkGroup)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.contextLabel = QtGui.QLabel(self.checkGroup)
        self.contextLabel.setObjectName(_fromUtf8("contextLabel"))
        self.gridLayout_6.addWidget(self.contextLabel, 0, 0, 1, 1)
        self.contextDataStatusLabel = QtGui.QLabel(self.checkGroup)
        self.contextDataStatusLabel.setText(_fromUtf8(""))
        self.contextDataStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/statusUnknown.png")))
        self.contextDataStatusLabel.setObjectName(_fromUtf8("contextDataStatusLabel"))
        self.gridLayout_6.addWidget(self.contextDataStatusLabel, 2, 6, 1, 2, QtCore.Qt.AlignHCenter)
        self.sectionSchematicLabel = QtGui.QLabel(self.checkGroup)
        self.sectionSchematicLabel.setObjectName(_fromUtf8("sectionSchematicLabel"))
        self.gridLayout_6.addWidget(self.sectionSchematicLabel, 4, 0, 1, 2)
        self.contextDataLabel = QtGui.QLabel(self.checkGroup)
        self.contextDataLabel.setObjectName(_fromUtf8("contextDataLabel"))
        self.gridLayout_6.addWidget(self.contextDataLabel, 2, 0, 1, 4)
        self.sectionSchematicStatusLabel = QtGui.QLabel(self.checkGroup)
        self.sectionSchematicStatusLabel.setText(_fromUtf8(""))
        self.sectionSchematicStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/statusUnknown.png")))
        self.sectionSchematicStatusLabel.setObjectName(_fromUtf8("sectionSchematicStatusLabel"))
        self.gridLayout_6.addWidget(self.sectionSchematicStatusLabel, 4, 6, 1, 2, QtCore.Qt.AlignHCenter)
        self.editContexLabel = QtGui.QLabel(self.checkGroup)
        self.editContexLabel.setObjectName(_fromUtf8("editContexLabel"))
        self.gridLayout_6.addWidget(self.editContexLabel, 5, 0, 1, 4)
        self.contextSchematicLabel = QtGui.QLabel(self.checkGroup)
        self.contextSchematicLabel.setObjectName(_fromUtf8("contextSchematicLabel"))
        self.gridLayout_6.addWidget(self.contextSchematicLabel, 3, 0, 1, 4)
        self.zoomContextTool = QtGui.QToolButton(self.checkGroup)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/zoomToItem.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomContextTool.setIcon(icon)
        self.zoomContextTool.setObjectName(_fromUtf8("zoomContextTool"))
        self.gridLayout_6.addWidget(self.zoomContextTool, 0, 7, 1, 1)
        self.contextSpin = QtGui.QSpinBox(self.checkGroup)
        self.contextSpin.setMaximum(99999)
        self.contextSpin.setObjectName(_fromUtf8("contextSpin"))
        self.gridLayout_6.addWidget(self.contextSpin, 0, 1, 1, 3)
        self.contextSchematicStatusLabel = QtGui.QLabel(self.checkGroup)
        self.contextSchematicStatusLabel.setText(_fromUtf8(""))
        self.contextSchematicStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/statusUnknown.png")))
        self.contextSchematicStatusLabel.setObjectName(_fromUtf8("contextSchematicStatusLabel"))
        self.gridLayout_6.addWidget(self.contextSchematicStatusLabel, 3, 6, 1, 2, QtCore.Qt.AlignHCenter)
        self.findContextTool = QtGui.QToolButton(self.checkGroup)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/search.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findContextTool.setIcon(icon1)
        self.findContextTool.setObjectName(_fromUtf8("findContextTool"))
        self.gridLayout_6.addWidget(self.findContextTool, 0, 6, 1, 1)
        self.editContextButton = QtGui.QPushButton(self.checkGroup)
        self.editContextButton.setObjectName(_fromUtf8("editContextButton"))
        self.gridLayout_6.addWidget(self.editContextButton, 5, 6, 1, 2)
        self.resetButton = QtGui.QPushButton(self.checkGroup)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout_6.addWidget(self.resetButton, 6, 6, 1, 2)
        self.gridLayout.addWidget(self.checkGroup, 0, 0, 1, 1)
        self.cloneGroup = QtGui.QGroupBox(SchematicWidget)
        self.cloneGroup.setObjectName(_fromUtf8("cloneGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.cloneGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.copySourceLabel = QtGui.QLabel(self.cloneGroup)
        self.copySourceLabel.setObjectName(_fromUtf8("copySourceLabel"))
        self.gridLayout_3.addWidget(self.copySourceLabel, 5, 0, 1, 3)
        self.sourceContextLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceContextLabel.setObjectName(_fromUtf8("sourceContextLabel"))
        self.gridLayout_3.addWidget(self.sourceContextLabel, 0, 0, 1, 1)
        self.copySourceButton = QtGui.QPushButton(self.cloneGroup)
        self.copySourceButton.setObjectName(_fromUtf8("copySourceButton"))
        self.gridLayout_3.addWidget(self.copySourceButton, 5, 3, 1, 2)
        self.sourceSchematicLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceSchematicLabel.setObjectName(_fromUtf8("sourceSchematicLabel"))
        self.gridLayout_3.addWidget(self.sourceSchematicLabel, 3, 0, 1, 3)
        self.cloneSourceLabel = QtGui.QLabel(self.cloneGroup)
        self.cloneSourceLabel.setObjectName(_fromUtf8("cloneSourceLabel"))
        self.gridLayout_3.addWidget(self.cloneSourceLabel, 4, 0, 1, 3)
        self.editSourceLabel = QtGui.QLabel(self.cloneGroup)
        self.editSourceLabel.setObjectName(_fromUtf8("editSourceLabel"))
        self.gridLayout_3.addWidget(self.editSourceLabel, 6, 0, 1, 3)
        self.findSourceTool = QtGui.QToolButton(self.cloneGroup)
        self.findSourceTool.setIcon(icon1)
        self.findSourceTool.setObjectName(_fromUtf8("findSourceTool"))
        self.gridLayout_3.addWidget(self.findSourceTool, 0, 3, 1, 1)
        self.zoomSourceTool = QtGui.QToolButton(self.cloneGroup)
        self.zoomSourceTool.setIcon(icon)
        self.zoomSourceTool.setObjectName(_fromUtf8("zoomSourceTool"))
        self.gridLayout_3.addWidget(self.zoomSourceTool, 0, 4, 1, 1)
        self.cloneSourceButton = QtGui.QPushButton(self.cloneGroup)
        self.cloneSourceButton.setObjectName(_fromUtf8("cloneSourceButton"))
        self.gridLayout_3.addWidget(self.cloneSourceButton, 4, 3, 1, 2)
        self.sourceContextSpin = QtGui.QSpinBox(self.cloneGroup)
        self.sourceContextSpin.setMaximum(99999)
        self.sourceContextSpin.setObjectName(_fromUtf8("sourceContextSpin"))
        self.gridLayout_3.addWidget(self.sourceContextSpin, 0, 1, 1, 2)
        self.editSourceButton = QtGui.QPushButton(self.cloneGroup)
        self.editSourceButton.setObjectName(_fromUtf8("editSourceButton"))
        self.gridLayout_3.addWidget(self.editSourceButton, 6, 3, 1, 2)
        self.sourceDataLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceDataLabel.setObjectName(_fromUtf8("sourceDataLabel"))
        self.gridLayout_3.addWidget(self.sourceDataLabel, 2, 0, 1, 3)
        self.sourceSchematicStatusLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceSchematicStatusLabel.setText(_fromUtf8(""))
        self.sourceSchematicStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/statusUnknown.png")))
        self.sourceSchematicStatusLabel.setObjectName(_fromUtf8("sourceSchematicStatusLabel"))
        self.gridLayout_3.addWidget(self.sourceSchematicStatusLabel, 3, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.sourceDataStatusLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceDataStatusLabel.setText(_fromUtf8(""))
        self.sourceDataStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/statusUnknown.png")))
        self.sourceDataStatusLabel.setObjectName(_fromUtf8("sourceDataStatusLabel"))
        self.gridLayout_3.addWidget(self.sourceDataStatusLabel, 2, 3, 1, 2, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.cloneGroup, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.contextLabel.setBuddy(self.contextSpin)
        self.sourceContextLabel.setBuddy(self.sourceContextSpin)

        self.retranslateUi(SchematicWidget)
        QtCore.QMetaObject.connectSlotsByName(SchematicWidget)

    def retranslateUi(self, SchematicWidget):
        SchematicWidget.setWindowTitle(_translate("SchematicWidget", "Form", None))
        self.checkGroup.setTitle(_translate("SchematicWidget", "Check", None))
        self.contextLabel.setText(_translate("SchematicWidget", "Check Context:", None))
        self.sectionSchematicLabel.setText(_translate("SchematicWidget", "Has Section Schematic:", None))
        self.contextDataLabel.setText(_translate("SchematicWidget", "Has Features:", None))
        self.editContexLabel.setText(_translate("SchematicWidget", "Edit Context:", None))
        self.contextSchematicLabel.setText(_translate("SchematicWidget", "Has Schematic:", None))
        self.zoomContextTool.setToolTip(_translate("SchematicWidget", "<html><head/><body><p>Zoom to Context</p></body></html>", None))
        self.zoomContextTool.setText(_translate("SchematicWidget", "...", None))
        self.contextSpin.setToolTip(_translate("SchematicWidget", "<html><head/><body><p>Enter Context to find</p></body></html>", None))
        self.findContextTool.setToolTip(_translate("SchematicWidget", "<html><head/><body><p>Pan to Context</p></body></html>", None))
        self.findContextTool.setText(_translate("SchematicWidget", "...", None))
        self.editContextButton.setText(_translate("SchematicWidget", "Edit", None))
        self.resetButton.setText(_translate("SchematicWidget", "Reset", None))
        self.cloneGroup.setTitle(_translate("SchematicWidget", "Clone", None))
        self.copySourceLabel.setText(_translate("SchematicWidget", "Copy and Edit Schematic:", None))
        self.sourceContextLabel.setText(_translate("SchematicWidget", "Source Context:", None))
        self.copySourceButton.setText(_translate("SchematicWidget", "Copy", None))
        self.sourceSchematicLabel.setText(_translate("SchematicWidget", "Has Schematic:", None))
        self.cloneSourceLabel.setText(_translate("SchematicWidget", "Clone and Save Schematic:", None))
        self.editSourceLabel.setText(_translate("SchematicWidget", "Edit Source Context:", None))
        self.findSourceTool.setToolTip(_translate("SchematicWidget", "<html><head/><body><p>Pan to Context</p></body></html>", None))
        self.findSourceTool.setText(_translate("SchematicWidget", "...", None))
        self.zoomSourceTool.setToolTip(_translate("SchematicWidget", "<html><head/><body><p>Zoom to Context</p></body></html>", None))
        self.zoomSourceTool.setText(_translate("SchematicWidget", "...", None))
        self.cloneSourceButton.setText(_translate("SchematicWidget", "Clone", None))
        self.sourceContextSpin.setToolTip(_translate("SchematicWidget", "<html><head/><body><p>Enter Source Context to find</p></body></html>", None))
        self.editSourceButton.setText(_translate("SchematicWidget", "Edit", None))
        self.sourceDataLabel.setText(_translate("SchematicWidget", "Has Features:", None))

import resources_rc
