# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/schematic_dock_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SchematicDockWidget(object):
    def setupUi(self, SchematicDockWidget):
        SchematicDockWidget.setObjectName(_fromUtf8("SchematicDockWidget"))
        SchematicDockWidget.resize(330, 524)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 304, 430))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.checkGroup.setObjectName(_fromUtf8("checkGroup"))
        self.gridLayout_5 = QtGui.QGridLayout(self.checkGroup)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.contextDataLabel = QtGui.QLabel(self.checkGroup)
        self.contextDataLabel.setObjectName(_fromUtf8("contextDataLabel"))
        self.gridLayout_5.addWidget(self.contextDataLabel, 1, 0, 1, 2)
        self.contextLabel = QtGui.QLabel(self.checkGroup)
        self.contextLabel.setObjectName(_fromUtf8("contextLabel"))
        self.gridLayout_5.addWidget(self.contextLabel, 0, 0, 1, 1)
        self.contextSpin = QtGui.QSpinBox(self.checkGroup)
        self.contextSpin.setMaximum(99999)
        self.contextSpin.setObjectName(_fromUtf8("contextSpin"))
        self.gridLayout_5.addWidget(self.contextSpin, 0, 1, 1, 1)
        self.findContextButton = QtGui.QPushButton(self.checkGroup)
        self.findContextButton.setObjectName(_fromUtf8("findContextButton"))
        self.gridLayout_5.addWidget(self.findContextButton, 0, 2, 1, 1)
        self.contextDataStatusLabel = QtGui.QLabel(self.checkGroup)
        self.contextDataStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.contextDataStatusLabel.setText(_fromUtf8(""))
        self.contextDataStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkPlan/plan/statusUnknown.png")))
        self.contextDataStatusLabel.setObjectName(_fromUtf8("contextDataStatusLabel"))
        self.gridLayout_5.addWidget(self.contextDataStatusLabel, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.contextSchematicStatusLabel = QtGui.QLabel(self.checkGroup)
        self.contextSchematicStatusLabel.setText(_fromUtf8(""))
        self.contextSchematicStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkPlan/plan/statusUnknown.png")))
        self.contextSchematicStatusLabel.setObjectName(_fromUtf8("contextSchematicStatusLabel"))
        self.gridLayout_5.addWidget(self.contextSchematicStatusLabel, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.contextSchematicLabel = QtGui.QLabel(self.checkGroup)
        self.contextSchematicLabel.setObjectName(_fromUtf8("contextSchematicLabel"))
        self.gridLayout_5.addWidget(self.contextSchematicLabel, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.checkGroup)
        self.cloneGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.cloneGroup.setObjectName(_fromUtf8("cloneGroup"))
        self.gridLayout_3 = QtGui.QGridLayout(self.cloneGroup)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sourceSchematicStatusLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceSchematicStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.sourceSchematicStatusLabel.setText(_fromUtf8(""))
        self.sourceSchematicStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkPlan/plan/statusUnknown.png")))
        self.sourceSchematicStatusLabel.setObjectName(_fromUtf8("sourceSchematicStatusLabel"))
        self.gridLayout_3.addWidget(self.sourceSchematicStatusLabel, 2, 2, 1, 1, QtCore.Qt.AlignRight)
        self.sourceContextLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceContextLabel.setObjectName(_fromUtf8("sourceContextLabel"))
        self.gridLayout_3.addWidget(self.sourceContextLabel, 0, 0, 1, 1)
        self.sourceSchematicLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceSchematicLabel.setObjectName(_fromUtf8("sourceSchematicLabel"))
        self.gridLayout_3.addWidget(self.sourceSchematicLabel, 2, 0, 1, 2)
        self.sourceDataLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceDataLabel.setObjectName(_fromUtf8("sourceDataLabel"))
        self.gridLayout_3.addWidget(self.sourceDataLabel, 1, 0, 1, 2)
        self.sourceDataStatusLabel = QtGui.QLabel(self.cloneGroup)
        self.sourceDataStatusLabel.setMaximumSize(QtCore.QSize(16, 16))
        self.sourceDataStatusLabel.setText(_fromUtf8(""))
        self.sourceDataStatusLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkPlan/plan/statusUnknown.png")))
        self.sourceDataStatusLabel.setObjectName(_fromUtf8("sourceDataStatusLabel"))
        self.gridLayout_3.addWidget(self.sourceDataStatusLabel, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.sourceContextSpin = QtGui.QSpinBox(self.cloneGroup)
        self.sourceContextSpin.setMaximum(99999)
        self.sourceContextSpin.setObjectName(_fromUtf8("sourceContextSpin"))
        self.gridLayout_3.addWidget(self.sourceContextSpin, 0, 1, 1, 1)
        self.copySourceButton = QtGui.QPushButton(self.cloneGroup)
        self.copySourceButton.setObjectName(_fromUtf8("copySourceButton"))
        self.gridLayout_3.addWidget(self.copySourceButton, 3, 1, 1, 1)
        self.findSourceButton = QtGui.QPushButton(self.cloneGroup)
        self.findSourceButton.setObjectName(_fromUtf8("findSourceButton"))
        self.gridLayout_3.addWidget(self.findSourceButton, 0, 2, 1, 1)
        self.cloneSourceButton = QtGui.QPushButton(self.cloneGroup)
        self.cloneSourceButton.setObjectName(_fromUtf8("cloneSourceButton"))
        self.gridLayout_3.addWidget(self.cloneSourceButton, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.cloneGroup)
        self.metadataWidget = MetadataWidget(self.scrollAreaWidgetContents)
        self.metadataWidget.setObjectName(_fromUtf8("metadataWidget"))
        self.verticalLayout.addWidget(self.metadataWidget)
        self.drawGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.drawGroup.setObjectName(_fromUtf8("drawGroup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.drawGroup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.contextToolsLayout = QtGui.QGridLayout()
        self.contextToolsLayout.setObjectName(_fromUtf8("contextToolsLayout"))
        self.gridLayout_4.addLayout(self.contextToolsLayout, 0, 0, 1, 2)
        self.autoSchematiclLabel = QtGui.QLabel(self.drawGroup)
        self.autoSchematiclLabel.setObjectName(_fromUtf8("autoSchematiclLabel"))
        self.gridLayout_4.addWidget(self.autoSchematiclLabel, 1, 0, 1, 1)
        self.autoSchematicTool = QtGui.QToolButton(self.drawGroup)
        self.autoSchematicTool.setObjectName(_fromUtf8("autoSchematicTool"))
        self.gridLayout_4.addWidget(self.autoSchematicTool, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.drawGroup)
        spacerItem = QtGui.QSpacerItem(17, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.buttonGroup = QtGui.QHBoxLayout()
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.resetButton = QtGui.QPushButton(self.dockWidgetContents)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.buttonGroup.addWidget(self.resetButton)
        self.clearButton = QtGui.QPushButton(self.dockWidgetContents)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.buttonGroup.addWidget(self.clearButton)
        self.mergeButton = QtGui.QPushButton(self.dockWidgetContents)
        self.mergeButton.setObjectName(_fromUtf8("mergeButton"))
        self.buttonGroup.addWidget(self.mergeButton)
        self.verticalLayout_2.addLayout(self.buttonGroup)
        SchematicDockWidget.setWidget(self.dockWidgetContents)
        self.contextLabel.setBuddy(self.contextSpin)
        self.sourceContextLabel.setBuddy(self.sourceContextSpin)

        self.retranslateUi(SchematicDockWidget)
        QtCore.QMetaObject.connectSlotsByName(SchematicDockWidget)

    def retranslateUi(self, SchematicDockWidget):
        SchematicDockWidget.setWindowTitle(_translate("SchematicDockWidget", "Context Schematic", None))
        self.checkGroup.setTitle(_translate("SchematicDockWidget", "Check", None))
        self.contextDataLabel.setText(_translate("SchematicDockWidget", "Has Features:", None))
        self.contextLabel.setText(_translate("SchematicDockWidget", "Context:", None))
        self.findContextButton.setText(_translate("SchematicDockWidget", "Find", None))
        self.contextSchematicLabel.setText(_translate("SchematicDockWidget", "Has Schematic:", None))
        self.cloneGroup.setTitle(_translate("SchematicDockWidget", "Clone", None))
        self.sourceContextLabel.setText(_translate("SchematicDockWidget", "Source Context:", None))
        self.sourceSchematicLabel.setText(_translate("SchematicDockWidget", "Has Schematic:", None))
        self.sourceDataLabel.setText(_translate("SchematicDockWidget", "Has Features:", None))
        self.copySourceButton.setText(_translate("SchematicDockWidget", "Copy", None))
        self.findSourceButton.setText(_translate("SchematicDockWidget", "Find", None))
        self.cloneSourceButton.setText(_translate("SchematicDockWidget", "Clone", None))
        self.drawGroup.setTitle(_translate("SchematicDockWidget", "Draw", None))
        self.autoSchematiclLabel.setText(_translate("SchematicDockWidget", "Auto Schematic:", None))
        self.autoSchematicTool.setText(_translate("SchematicDockWidget", "Auto", None))
        self.resetButton.setText(_translate("SchematicDockWidget", "Reset", None))
        self.clearButton.setToolTip(_translate("SchematicDockWidget", "Clear unsaved changes from work layers", None))
        self.clearButton.setText(_translate("SchematicDockWidget", "Clear", None))
        self.mergeButton.setToolTip(_translate("SchematicDockWidget", "Move new context to main layers", None))
        self.mergeButton.setText(_translate("SchematicDockWidget", "Merge", None))

from metadata_widget import MetadataWidget
import resources_rc
