# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/section_window_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SectionWindow(object):
    def setupUi(self, SectionWindow):
        SectionWindow.setObjectName(_fromUtf8("SectionWindow"))
        SectionWindow.resize(910, 762)
        self.centralwidget = QtGui.QWidget(SectionWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        SectionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SectionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSection = QtGui.QMenu(self.menubar)
        self.menuSection.setObjectName(_fromUtf8("menuSection"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        SectionWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SectionWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SectionWindow.setStatusBar(self.statusbar)
        self.mainToolbar = QtGui.QToolBar(SectionWindow)
        self.mainToolbar.setObjectName(_fromUtf8("mainToolbar"))
        SectionWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolbar)
        self.editDock = QtGui.QDockWidget(SectionWindow)
        self.editDock.setObjectName(_fromUtf8("editDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 235, 584))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.metadataWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.metadataWidget.setMinimumSize(QtCore.QSize(0, 10))
        self.metadataWidget.setObjectName(_fromUtf8("metadataWidget"))
        self.verticalLayout.addWidget(self.metadataWidget)
        self.drawingToolsLayout = QtGui.QGridLayout()
        self.drawingToolsLayout.setObjectName(_fromUtf8("drawingToolsLayout"))
        self.verticalLayout.addLayout(self.drawingToolsLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.autoSchematiclLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.autoSchematiclLabel.setObjectName(_fromUtf8("autoSchematiclLabel"))
        self.horizontalLayout_2.addWidget(self.autoSchematiclLabel)
        self.autoSchematicTool = QtGui.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/autoSchematic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoSchematicTool.setIcon(icon)
        self.autoSchematicTool.setObjectName(_fromUtf8("autoSchematicTool"))
        self.horizontalLayout_2.addWidget(self.autoSchematicTool)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 511, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.clearButton = QtGui.QPushButton(self.dockWidgetContents)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout.addWidget(self.clearButton)
        self.mergeButton = QtGui.QPushButton(self.dockWidgetContents)
        self.mergeButton.setObjectName(_fromUtf8("mergeButton"))
        self.horizontalLayout.addWidget(self.mergeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.editDock.setWidget(self.dockWidgetContents)
        SectionWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.editDock)
        self.actionClose = QtGui.QAction(SectionWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/close.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionClearEdits = QtGui.QAction(SectionWindow)
        self.actionClearEdits.setObjectName(_fromUtf8("actionClearEdits"))
        self.actionMergeEdits = QtGui.QAction(SectionWindow)
        self.actionMergeEdits.setObjectName(_fromUtf8("actionMergeEdits"))
        self.actionPanMap = QtGui.QAction(SectionWindow)
        self.actionPanMap.setCheckable(True)
        self.actionPanMap.setObjectName(_fromUtf8("actionPanMap"))
        self.actionZoomIn = QtGui.QAction(SectionWindow)
        self.actionZoomIn.setCheckable(True)
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoomOut = QtGui.QAction(SectionWindow)
        self.actionZoomOut.setCheckable(True)
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionZoomFull = QtGui.QAction(SectionWindow)
        self.actionZoomFull.setCheckable(True)
        self.actionZoomFull.setObjectName(_fromUtf8("actionZoomFull"))
        self.actionZoomLast = QtGui.QAction(SectionWindow)
        self.actionZoomLast.setCheckable(True)
        self.actionZoomLast.setEnabled(False)
        self.actionZoomLast.setObjectName(_fromUtf8("actionZoomLast"))
        self.actionZoomNext = QtGui.QAction(SectionWindow)
        self.actionZoomNext.setCheckable(True)
        self.actionZoomNext.setEnabled(False)
        self.actionZoomNext.setObjectName(_fromUtf8("actionZoomNext"))
        self.actionRefreshMap = QtGui.QAction(SectionWindow)
        self.actionRefreshMap.setObjectName(_fromUtf8("actionRefreshMap"))
        self.actionOpen = QtGui.QAction(SectionWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/section.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionEditMode = QtGui.QAction(SectionWindow)
        self.actionEditMode.setCheckable(True)
        self.actionEditMode.setObjectName(_fromUtf8("actionEditMode"))
        self.actionEditPoints = QtGui.QAction(SectionWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/editPoints.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditPoints.setIcon(icon3)
        self.actionEditPoints.setObjectName(_fromUtf8("actionEditPoints"))
        self.actionEditLines = QtGui.QAction(SectionWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/editLines.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditLines.setIcon(icon4)
        self.actionEditLines.setObjectName(_fromUtf8("actionEditLines"))
        self.actionEditPolygons = QtGui.QAction(SectionWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/editPolygons.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditPolygons.setIcon(icon5)
        self.actionEditPolygons.setObjectName(_fromUtf8("actionEditPolygons"))
        self.actionSelectPoints = QtGui.QAction(SectionWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/selectPoints.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectPoints.setIcon(icon6)
        self.actionSelectPoints.setObjectName(_fromUtf8("actionSelectPoints"))
        self.actionSelectLines = QtGui.QAction(SectionWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/selectLines.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectLines.setIcon(icon7)
        self.actionSelectLines.setObjectName(_fromUtf8("actionSelectLines"))
        self.actionSelectPolygons = QtGui.QAction(SectionWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/selectPolygons.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectPolygons.setIcon(icon8)
        self.actionSelectPolygons.setObjectName(_fromUtf8("actionSelectPolygons"))
        self.actionShowDrawings = QtGui.QAction(SectionWindow)
        self.actionShowDrawings.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/plan/loadDrawings.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowDrawings.setIcon(icon9)
        self.actionShowDrawings.setObjectName(_fromUtf8("actionShowDrawings"))
        self.menuSection.addAction(self.actionOpen)
        self.menuSection.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionEditMode)
        self.menuEdit.addAction(self.actionClearEdits)
        self.menuEdit.addAction(self.actionMergeEdits)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionEditPoints)
        self.menuEdit.addAction(self.actionEditLines)
        self.menuEdit.addAction(self.actionEditPolygons)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelectPoints)
        self.menuEdit.addAction(self.actionSelectLines)
        self.menuEdit.addAction(self.actionSelectPolygons)
        self.menuView.addAction(self.actionPanMap)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionZoomFull)
        self.menuView.addAction(self.actionZoomLast)
        self.menuView.addAction(self.actionZoomNext)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRefreshMap)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionShowDrawings)
        self.menubar.addAction(self.menuSection.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.mainToolbar.addAction(self.actionOpen)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionPanMap)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionZoomIn)
        self.mainToolbar.addAction(self.actionZoomOut)
        self.mainToolbar.addAction(self.actionZoomFull)
        self.mainToolbar.addAction(self.actionZoomLast)
        self.mainToolbar.addAction(self.actionZoomNext)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionRefreshMap)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionShowDrawings)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionEditMode)
        self.mainToolbar.addAction(self.actionClearEdits)
        self.mainToolbar.addAction(self.actionMergeEdits)
        self.mainToolbar.addAction(self.actionEditPoints)
        self.mainToolbar.addAction(self.actionEditLines)
        self.mainToolbar.addAction(self.actionEditPolygons)
        self.mainToolbar.addAction(self.actionSelectPoints)
        self.mainToolbar.addAction(self.actionSelectLines)
        self.mainToolbar.addAction(self.actionSelectPolygons)

        self.retranslateUi(SectionWindow)
        QtCore.QMetaObject.connectSlotsByName(SectionWindow)

    def retranslateUi(self, SectionWindow):
        SectionWindow.setWindowTitle(_translate("SectionWindow", "Section Window", None))
        self.menuSection.setTitle(_translate("SectionWindow", "Section", None))
        self.menuEdit.setTitle(_translate("SectionWindow", "Edit", None))
        self.menuView.setTitle(_translate("SectionWindow", "View", None))
        self.mainToolbar.setWindowTitle(_translate("SectionWindow", "toolBar", None))
        self.editDock.setWindowTitle(_translate("SectionWindow", "Edit Section", None))
        self.autoSchematiclLabel.setText(_translate("SectionWindow", "Auto Schematic:", None))
        self.autoSchematicTool.setToolTip(_translate("SectionWindow", "<html><head/><body><p>Auto Schematic</p></body></html>", None))
        self.autoSchematicTool.setText(_translate("SectionWindow", "...", None))
        self.clearButton.setToolTip(_translate("SectionWindow", "Clear unsaved changes from work layers", None))
        self.clearButton.setText(_translate("SectionWindow", "Clear", None))
        self.mergeButton.setToolTip(_translate("SectionWindow", "Move new context to main layers", None))
        self.mergeButton.setText(_translate("SectionWindow", "Merge", None))
        self.actionClose.setText(_translate("SectionWindow", "Close", None))
        self.actionClearEdits.setText(_translate("SectionWindow", "Clear Edits", None))
        self.actionMergeEdits.setText(_translate("SectionWindow", "Merge Edits", None))
        self.actionPanMap.setText(_translate("SectionWindow", "Pan Map", None))
        self.actionZoomIn.setText(_translate("SectionWindow", "Zoom In", None))
        self.actionZoomOut.setText(_translate("SectionWindow", "Zoom Out", None))
        self.actionZoomFull.setText(_translate("SectionWindow", "Zoom Full", None))
        self.actionZoomLast.setText(_translate("SectionWindow", "Zoom Last", None))
        self.actionZoomNext.setText(_translate("SectionWindow", "Zoom Next", None))
        self.actionRefreshMap.setText(_translate("SectionWindow", "Refresh", None))
        self.actionOpen.setText(_translate("SectionWindow", "Open", None))
        self.actionEditMode.setText(_translate("SectionWindow", "Edit Mode", None))
        self.actionEditMode.setToolTip(_translate("SectionWindow", "Edit Section", None))
        self.actionEditPoints.setText(_translate("SectionWindow", "Edit Points", None))
        self.actionEditLines.setText(_translate("SectionWindow", "Edit Lines", None))
        self.actionEditPolygons.setText(_translate("SectionWindow", "Edit Polygons", None))
        self.actionSelectPoints.setText(_translate("SectionWindow", "Select Points", None))
        self.actionSelectLines.setText(_translate("SectionWindow", "Select Lines", None))
        self.actionSelectPolygons.setText(_translate("SectionWindow", "Select Polygons", None))
        self.actionShowDrawings.setText(_translate("SectionWindow", "Show Drawings", None))

import resources_rc
