# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/settings_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogBase(object):
    def setupUi(self, SettingsDialogBase):
        SettingsDialogBase.setObjectName(_fromUtf8("SettingsDialogBase"))
        SettingsDialogBase.resize(474, 336)
        self.verticalLayout = QtGui.QVBoxLayout(SettingsDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.projectFolderLabel = QtGui.QLabel(self.projectTab)
        self.projectFolderLabel.setObjectName(_fromUtf8("projectFolderLabel"))
        self.gridLayout_5.addWidget(self.projectFolderLabel, 0, 0, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(self.projectTab)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.gridLayout_5.addWidget(self.siteCodeLabel, 2, 0, 1, 1)
        self.useArkLabel = QtGui.QLabel(self.projectTab)
        self.useArkLabel.setObjectName(_fromUtf8("useArkLabel"))
        self.gridLayout_5.addWidget(self.useArkLabel, 5, 0, 1, 1)
        self.projectFolderLayout = QtGui.QHBoxLayout()
        self.projectFolderLayout.setObjectName(_fromUtf8("projectFolderLayout"))
        self.projectFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.projectFolderEdit.setObjectName(_fromUtf8("projectFolderEdit"))
        self.projectFolderLayout.addWidget(self.projectFolderEdit)
        self.projectFolderButton = QtGui.QPushButton(self.projectTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ark/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.projectFolderButton.setIcon(icon)
        self.projectFolderButton.setIconSize(QtCore.QSize(12, 12))
        self.projectFolderButton.setObjectName(_fromUtf8("projectFolderButton"))
        self.projectFolderLayout.addWidget(self.projectFolderButton)
        self.gridLayout_5.addLayout(self.projectFolderLayout, 0, 2, 1, 1)
        self.customStylesLabel = QtGui.QLabel(self.projectTab)
        self.customStylesLabel.setObjectName(_fromUtf8("customStylesLabel"))
        self.gridLayout_5.addWidget(self.customStylesLabel, 4, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 7, 2, 1, 1)
        self.styleFolderLayout = QtGui.QHBoxLayout()
        self.styleFolderLayout.setObjectName(_fromUtf8("styleFolderLayout"))
        self.styleFolderCheck = QtGui.QCheckBox(self.projectTab)
        self.styleFolderCheck.setText(_fromUtf8(""))
        self.styleFolderCheck.setObjectName(_fromUtf8("styleFolderCheck"))
        self.styleFolderLayout.addWidget(self.styleFolderCheck)
        self.styleFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.styleFolderEdit.setEnabled(False)
        self.styleFolderEdit.setObjectName(_fromUtf8("styleFolderEdit"))
        self.styleFolderLayout.addWidget(self.styleFolderEdit)
        self.styleFolderButton = QtGui.QPushButton(self.projectTab)
        self.styleFolderButton.setEnabled(False)
        self.styleFolderButton.setIcon(icon)
        self.styleFolderButton.setIconSize(QtCore.QSize(12, 12))
        self.styleFolderButton.setObjectName(_fromUtf8("styleFolderButton"))
        self.styleFolderLayout.addWidget(self.styleFolderButton)
        self.gridLayout_5.addLayout(self.styleFolderLayout, 4, 2, 1, 1)
        self.siteCodeEdit = QtGui.QLineEdit(self.projectTab)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.gridLayout_5.addWidget(self.siteCodeEdit, 2, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.useArkCheck = QtGui.QCheckBox(self.projectTab)
        self.useArkCheck.setText(_fromUtf8(""))
        self.useArkCheck.setObjectName(_fromUtf8("useArkCheck"))
        self.horizontalLayout.addWidget(self.useArkCheck)
        self.arkUrlEdit = QtGui.QLineEdit(self.projectTab)
        self.arkUrlEdit.setEnabled(False)
        self.arkUrlEdit.setObjectName(_fromUtf8("arkUrlEdit"))
        self.horizontalLayout.addWidget(self.arkUrlEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.multiSiteCheck = QtGui.QCheckBox(self.projectTab)
        self.multiSiteCheck.setText(_fromUtf8(""))
        self.multiSiteCheck.setObjectName(_fromUtf8("multiSiteCheck"))
        self.horizontalLayout_6.addWidget(self.multiSiteCheck)
        self.multiSiteEdit = QtGui.QLineEdit(self.projectTab)
        self.multiSiteEdit.setEnabled(False)
        self.multiSiteEdit.setObjectName(_fromUtf8("multiSiteEdit"))
        self.horizontalLayout_6.addWidget(self.multiSiteEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 3, 2, 1, 1)
        self.multiSiteLabel = QtGui.QLabel(self.projectTab)
        self.multiSiteLabel.setObjectName(_fromUtf8("multiSiteLabel"))
        self.gridLayout_5.addWidget(self.multiSiteLabel, 3, 0, 1, 1)
        self.logUpdatesLabel = QtGui.QLabel(self.projectTab)
        self.logUpdatesLabel.setObjectName(_fromUtf8("logUpdatesLabel"))
        self.gridLayout_5.addWidget(self.logUpdatesLabel, 6, 0, 1, 1)
        self.logUpdatesCheck = QtGui.QCheckBox(self.projectTab)
        self.logUpdatesCheck.setText(_fromUtf8(""))
        self.logUpdatesCheck.setChecked(True)
        self.logUpdatesCheck.setObjectName(_fromUtf8("logUpdatesCheck"))
        self.gridLayout_5.addWidget(self.logUpdatesCheck, 6, 2, 1, 1)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.drawingsTab = QtGui.QWidget()
        self.drawingsTab.setObjectName(_fromUtf8("drawingsTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.drawingsTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.planDrawingFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.planDrawingFolderCheck.setText(_fromUtf8(""))
        self.planDrawingFolderCheck.setObjectName(_fromUtf8("planDrawingFolderCheck"))
        self.horizontalLayout_3.addWidget(self.planDrawingFolderCheck)
        self.planDrawingFolderEdit = QtGui.QLineEdit(self.drawingsTab)
        self.planDrawingFolderEdit.setEnabled(False)
        self.planDrawingFolderEdit.setObjectName(_fromUtf8("planDrawingFolderEdit"))
        self.horizontalLayout_3.addWidget(self.planDrawingFolderEdit)
        self.planDrawingFolderButton = QtGui.QPushButton(self.drawingsTab)
        self.planDrawingFolderButton.setEnabled(False)
        self.planDrawingFolderButton.setIcon(icon)
        self.planDrawingFolderButton.setObjectName(_fromUtf8("planDrawingFolderButton"))
        self.horizontalLayout_3.addWidget(self.planDrawingFolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.georefFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.georefFolderLabel.setObjectName(_fromUtf8("georefFolderLabel"))
        self.gridLayout_2.addWidget(self.georefFolderLabel, 1, 0, 1, 1)
        self.georefFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.georefFolderCheck.setText(_fromUtf8(""))
        self.georefFolderCheck.setChecked(True)
        self.georefFolderCheck.setObjectName(_fromUtf8("georefFolderCheck"))
        self.gridLayout_2.addWidget(self.georefFolderCheck, 1, 2, 1, 1)
        self.planDrawingFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.planDrawingFolderLabel.setObjectName(_fromUtf8("planDrawingFolderLabel"))
        self.gridLayout_2.addWidget(self.planDrawingFolderLabel, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.contextDrawingFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.contextDrawingFolderCheck.setText(_fromUtf8(""))
        self.contextDrawingFolderCheck.setObjectName(_fromUtf8("contextDrawingFolderCheck"))
        self.horizontalLayout_2.addWidget(self.contextDrawingFolderCheck)
        self.contextDrawingFolderEdit = QtGui.QLineEdit(self.drawingsTab)
        self.contextDrawingFolderEdit.setEnabled(False)
        self.contextDrawingFolderEdit.setObjectName(_fromUtf8("contextDrawingFolderEdit"))
        self.horizontalLayout_2.addWidget(self.contextDrawingFolderEdit)
        self.contextDrawingFolderButton = QtGui.QPushButton(self.drawingsTab)
        self.contextDrawingFolderButton.setEnabled(False)
        self.contextDrawingFolderButton.setIcon(icon)
        self.contextDrawingFolderButton.setObjectName(_fromUtf8("contextDrawingFolderButton"))
        self.horizontalLayout_2.addWidget(self.contextDrawingFolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.drawingTransparencySpin = QtGui.QSpinBox(self.drawingsTab)
        self.drawingTransparencySpin.setMaximum(100)
        self.drawingTransparencySpin.setProperty("value", 50)
        self.drawingTransparencySpin.setObjectName(_fromUtf8("drawingTransparencySpin"))
        self.horizontalLayout_4.addWidget(self.drawingTransparencySpin)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 2, 1, 1)
        self.drawingTransparencyLabel = QtGui.QLabel(self.drawingsTab)
        self.drawingTransparencyLabel.setObjectName(_fromUtf8("drawingTransparencyLabel"))
        self.gridLayout_2.addWidget(self.drawingTransparencyLabel, 0, 0, 1, 1)
        self.contextDrawingFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.contextDrawingFolderLabel.setObjectName(_fromUtf8("contextDrawingFolderLabel"))
        self.gridLayout_2.addWidget(self.contextDrawingFolderLabel, 2, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 46, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 5, 2, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sectionDrawingFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.sectionDrawingFolderCheck.setText(_fromUtf8(""))
        self.sectionDrawingFolderCheck.setObjectName(_fromUtf8("sectionDrawingFolderCheck"))
        self.horizontalLayout_5.addWidget(self.sectionDrawingFolderCheck)
        self.sectionDrawingFolderEdit = QtGui.QLineEdit(self.drawingsTab)
        self.sectionDrawingFolderEdit.setEnabled(False)
        self.sectionDrawingFolderEdit.setObjectName(_fromUtf8("sectionDrawingFolderEdit"))
        self.horizontalLayout_5.addWidget(self.sectionDrawingFolderEdit)
        self.sectionDrawingFolderButton = QtGui.QPushButton(self.drawingsTab)
        self.sectionDrawingFolderButton.setEnabled(False)
        self.sectionDrawingFolderButton.setIcon(icon)
        self.sectionDrawingFolderButton.setObjectName(_fromUtf8("sectionDrawingFolderButton"))
        self.horizontalLayout_5.addWidget(self.sectionDrawingFolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 2, 1, 1)
        self.sectionDrawingFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.sectionDrawingFolderLabel.setObjectName(_fromUtf8("sectionDrawingFolderLabel"))
        self.gridLayout_2.addWidget(self.sectionDrawingFolderLabel, 4, 0, 1, 1)
        self.tabWidget.addTab(self.drawingsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.projectFolderLabel.setBuddy(self.projectFolderEdit)
        self.siteCodeLabel.setBuddy(self.siteCodeEdit)
        self.useArkLabel.setBuddy(self.useArkCheck)
        self.customStylesLabel.setBuddy(self.styleFolderEdit)
        self.multiSiteLabel.setBuddy(self.multiSiteCheck)
        self.georefFolderLabel.setBuddy(self.georefFolderCheck)
        self.planDrawingFolderLabel.setBuddy(self.planDrawingFolderCheck)
        self.contextDrawingFolderLabel.setBuddy(self.contextDrawingFolderCheck)
        self.sectionDrawingFolderLabel.setBuddy(self.sectionDrawingFolderCheck)

        self.retranslateUi(SettingsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogBase.reject)
        QtCore.QObject.connect(self.styleFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.styleFolderButton.setEnabled)
        QtCore.QObject.connect(self.planDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.planDrawingFolderButton.setEnabled)
        QtCore.QObject.connect(self.useArkCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.arkUrlEdit.setEnabled)
        QtCore.QObject.connect(self.styleFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.styleFolderEdit.setEnabled)
        QtCore.QObject.connect(self.planDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.planDrawingFolderEdit.setEnabled)
        QtCore.QObject.connect(self.contextDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contextDrawingFolderEdit.setEnabled)
        QtCore.QObject.connect(self.contextDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contextDrawingFolderButton.setEnabled)
        QtCore.QObject.connect(self.multiSiteCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.multiSiteEdit.setEnabled)
        QtCore.QObject.connect(self.sectionDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sectionDrawingFolderEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogBase)
        SettingsDialogBase.setTabOrder(self.projectFolderEdit, self.projectFolderButton)
        SettingsDialogBase.setTabOrder(self.projectFolderButton, self.siteCodeEdit)
        SettingsDialogBase.setTabOrder(self.siteCodeEdit, self.multiSiteCheck)
        SettingsDialogBase.setTabOrder(self.multiSiteCheck, self.multiSiteEdit)
        SettingsDialogBase.setTabOrder(self.multiSiteEdit, self.styleFolderCheck)
        SettingsDialogBase.setTabOrder(self.styleFolderCheck, self.styleFolderEdit)
        SettingsDialogBase.setTabOrder(self.styleFolderEdit, self.styleFolderButton)
        SettingsDialogBase.setTabOrder(self.styleFolderButton, self.useArkCheck)
        SettingsDialogBase.setTabOrder(self.useArkCheck, self.arkUrlEdit)
        SettingsDialogBase.setTabOrder(self.arkUrlEdit, self.tabWidget)
        SettingsDialogBase.setTabOrder(self.tabWidget, self.drawingTransparencySpin)
        SettingsDialogBase.setTabOrder(self.drawingTransparencySpin, self.georefFolderCheck)
        SettingsDialogBase.setTabOrder(self.georefFolderCheck, self.contextDrawingFolderCheck)
        SettingsDialogBase.setTabOrder(self.contextDrawingFolderCheck, self.contextDrawingFolderEdit)
        SettingsDialogBase.setTabOrder(self.contextDrawingFolderEdit, self.contextDrawingFolderButton)
        SettingsDialogBase.setTabOrder(self.contextDrawingFolderButton, self.planDrawingFolderCheck)
        SettingsDialogBase.setTabOrder(self.planDrawingFolderCheck, self.planDrawingFolderEdit)
        SettingsDialogBase.setTabOrder(self.planDrawingFolderEdit, self.planDrawingFolderButton)
        SettingsDialogBase.setTabOrder(self.planDrawingFolderButton, self.sectionDrawingFolderCheck)
        SettingsDialogBase.setTabOrder(self.sectionDrawingFolderCheck, self.sectionDrawingFolderEdit)
        SettingsDialogBase.setTabOrder(self.sectionDrawingFolderEdit, self.sectionDrawingFolderButton)
        SettingsDialogBase.setTabOrder(self.sectionDrawingFolderButton, self.buttonBox)

    def retranslateUi(self, SettingsDialogBase):
        SettingsDialogBase.setWindowTitle(_translate("SettingsDialogBase", "Settings", None))
        self.projectFolderLabel.setText(_translate("SettingsDialogBase", "Project Folder:", None))
        self.siteCodeLabel.setText(_translate("SettingsDialogBase", "Default Site Code:", None))
        self.useArkLabel.setText(_translate("SettingsDialogBase", "Use ARK DB:", None))
        self.customStylesLabel.setText(_translate("SettingsDialogBase", "Custom Styles Folder:", None))
        self.multiSiteLabel.setText(_translate("SettingsDialogBase", "Multi-site Project", None))
        self.logUpdatesLabel.setText(_translate("SettingsDialogBase", "Log Updates:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("SettingsDialogBase", "Project", None))
        self.georefFolderLabel.setText(_translate("SettingsDialogBase", "Separate georef folder:", None))
        self.georefFolderCheck.setToolTip(_translate("SettingsDialogBase", "Select if the raw and processed plans should be stored in separate folders.", None))
        self.planDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Plan Drawings:", None))
        self.drawingTransparencySpin.setSuffix(_translate("SettingsDialogBase", "%", None))
        self.drawingTransparencyLabel.setText(_translate("SettingsDialogBase", "Image tranparency:", None))
        self.contextDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Context Drawings:", None))
        self.sectionDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Section Drawings:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.drawingsTab), _translate("SettingsDialogBase", "Drawings", None))

import resources_rc
