# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/settings_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialogBase(object):
    def setupUi(self, SettingsDialogBase):
        SettingsDialogBase.setObjectName(_fromUtf8("SettingsDialogBase"))
        SettingsDialogBase.resize(540, 338)
        self.verticalLayout = QtGui.QVBoxLayout(SettingsDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(SettingsDialogBase)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.projectTab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.useArkLabel = QtGui.QLabel(self.projectTab)
        self.useArkLabel.setObjectName(_fromUtf8("useArkLabel"))
        self.gridLayout_5.addWidget(self.useArkLabel, 4, 0, 1, 1)
        self.projectFolderLayout = QtGui.QHBoxLayout()
        self.projectFolderLayout.setObjectName(_fromUtf8("projectFolderLayout"))
        self.projectFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.projectFolderEdit.setObjectName(_fromUtf8("projectFolderEdit"))
        self.projectFolderLayout.addWidget(self.projectFolderEdit)
        self.projectFolderButton = QtGui.QPushButton(self.projectTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/ArkPlan/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.projectFolderButton.setIcon(icon)
        self.projectFolderButton.setObjectName(_fromUtf8("projectFolderButton"))
        self.projectFolderLayout.addWidget(self.projectFolderButton)
        self.gridLayout_5.addLayout(self.projectFolderLayout, 0, 2, 1, 1)
        self.multiSiteCheck = QtGui.QCheckBox(self.projectTab)
        self.multiSiteCheck.setText(_fromUtf8(""))
        self.multiSiteCheck.setObjectName(_fromUtf8("multiSiteCheck"))
        self.gridLayout_5.addWidget(self.multiSiteCheck, 1, 2, 1, 1)
        self.projectFolderLabel = QtGui.QLabel(self.projectTab)
        self.projectFolderLabel.setObjectName(_fromUtf8("projectFolderLabel"))
        self.gridLayout_5.addWidget(self.projectFolderLabel, 0, 0, 1, 1)
        self.siteCodeLabel = QtGui.QLabel(self.projectTab)
        self.siteCodeLabel.setObjectName(_fromUtf8("siteCodeLabel"))
        self.gridLayout_5.addWidget(self.siteCodeLabel, 2, 0, 1, 1)
        self.multiSiteLabel = QtGui.QLabel(self.projectTab)
        self.multiSiteLabel.setObjectName(_fromUtf8("multiSiteLabel"))
        self.gridLayout_5.addWidget(self.multiSiteLabel, 1, 0, 1, 1)
        self.styleFolderLayout = QtGui.QHBoxLayout()
        self.styleFolderLayout.setObjectName(_fromUtf8("styleFolderLayout"))
        self.styleFolderCheck = QtGui.QCheckBox(self.projectTab)
        self.styleFolderCheck.setText(_fromUtf8(""))
        self.styleFolderCheck.setObjectName(_fromUtf8("styleFolderCheck"))
        self.styleFolderLayout.addWidget(self.styleFolderCheck)
        self.styleFolderEdit = QtGui.QLineEdit(self.projectTab)
        self.styleFolderEdit.setEnabled(False)
        self.styleFolderEdit.setObjectName(_fromUtf8("styleFolderEdit"))
        self.styleFolderLayout.addWidget(self.styleFolderEdit)
        self.styleFolderButton = QtGui.QPushButton(self.projectTab)
        self.styleFolderButton.setEnabled(False)
        self.styleFolderButton.setIcon(icon)
        self.styleFolderButton.setObjectName(_fromUtf8("styleFolderButton"))
        self.styleFolderLayout.addWidget(self.styleFolderButton)
        self.gridLayout_5.addLayout(self.styleFolderLayout, 3, 2, 1, 1)
        self.customStylesLabel = QtGui.QLabel(self.projectTab)
        self.customStylesLabel.setObjectName(_fromUtf8("customStylesLabel"))
        self.gridLayout_5.addWidget(self.customStylesLabel, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 5, 2, 1, 1)
        self.siteCodeEdit = QtGui.QLineEdit(self.projectTab)
        self.siteCodeEdit.setObjectName(_fromUtf8("siteCodeEdit"))
        self.gridLayout_5.addWidget(self.siteCodeEdit, 2, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.useArkCheck = QtGui.QCheckBox(self.projectTab)
        self.useArkCheck.setText(_fromUtf8(""))
        self.useArkCheck.setObjectName(_fromUtf8("useArkCheck"))
        self.horizontalLayout.addWidget(self.useArkCheck)
        self.arkUrlEdit = QtGui.QLineEdit(self.projectTab)
        self.arkUrlEdit.setEnabled(False)
        self.arkUrlEdit.setObjectName(_fromUtf8("arkUrlEdit"))
        self.horizontalLayout.addWidget(self.arkUrlEdit)
        self.gridLayout_5.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.tabWidget.addTab(self.projectTab, _fromUtf8(""))
        self.gridTab = QtGui.QWidget()
        self.gridTab.setObjectName(_fromUtf8("gridTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridPolygonsNameLabel = QtGui.QLabel(self.gridTab)
        self.gridPolygonsNameLabel.setObjectName(_fromUtf8("gridPolygonsNameLabel"))
        self.gridLayout_4.addWidget(self.gridPolygonsNameLabel, 4, 0, 1, 1)
        self.gridGroupNameLabel = QtGui.QLabel(self.gridTab)
        self.gridGroupNameLabel.setObjectName(_fromUtf8("gridGroupNameLabel"))
        self.gridLayout_4.addWidget(self.gridGroupNameLabel, 1, 0, 1, 1)
        self.gridPointsNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridPointsNameEdit.setObjectName(_fromUtf8("gridPointsNameEdit"))
        self.gridLayout_4.addWidget(self.gridPointsNameEdit, 2, 1, 1, 1)
        self.gridLinesNameLabel = QtGui.QLabel(self.gridTab)
        self.gridLinesNameLabel.setObjectName(_fromUtf8("gridLinesNameLabel"))
        self.gridLayout_4.addWidget(self.gridLinesNameLabel, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 1, 1, 1)
        self.gridPolygonsNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridPolygonsNameEdit.setObjectName(_fromUtf8("gridPolygonsNameEdit"))
        self.gridLayout_4.addWidget(self.gridPolygonsNameEdit, 4, 1, 1, 1)
        self.gridGroupNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridGroupNameEdit.setObjectName(_fromUtf8("gridGroupNameEdit"))
        self.gridLayout_4.addWidget(self.gridGroupNameEdit, 1, 1, 1, 1)
        self.gridPointNameLabel = QtGui.QLabel(self.gridTab)
        self.gridPointNameLabel.setObjectName(_fromUtf8("gridPointNameLabel"))
        self.gridLayout_4.addWidget(self.gridPointNameLabel, 2, 0, 1, 1)
        self.gridLinesNameEdit = QtGui.QLineEdit(self.gridTab)
        self.gridLinesNameEdit.setObjectName(_fromUtf8("gridLinesNameEdit"))
        self.gridLayout_4.addWidget(self.gridLinesNameEdit, 3, 1, 1, 1)
        self.gridFolderLabel = QtGui.QLabel(self.gridTab)
        self.gridFolderLabel.setObjectName(_fromUtf8("gridFolderLabel"))
        self.gridLayout_4.addWidget(self.gridFolderLabel, 5, 0, 1, 1)
        self.gridFolderLayout = QtGui.QHBoxLayout()
        self.gridFolderLayout.setObjectName(_fromUtf8("gridFolderLayout"))
        self.gridFolderCheck = QtGui.QCheckBox(self.gridTab)
        self.gridFolderCheck.setText(_fromUtf8(""))
        self.gridFolderCheck.setObjectName(_fromUtf8("gridFolderCheck"))
        self.gridFolderLayout.addWidget(self.gridFolderCheck)
        self.gridFolderEdit = QtGui.QLineEdit(self.gridTab)
        self.gridFolderEdit.setEnabled(False)
        self.gridFolderEdit.setObjectName(_fromUtf8("gridFolderEdit"))
        self.gridFolderLayout.addWidget(self.gridFolderEdit)
        self.gridFolderButton = QtGui.QPushButton(self.gridTab)
        self.gridFolderButton.setEnabled(False)
        self.gridFolderButton.setIcon(icon)
        self.gridFolderButton.setObjectName(_fromUtf8("gridFolderButton"))
        self.gridFolderLayout.addWidget(self.gridFolderButton)
        self.gridLayout_4.addLayout(self.gridFolderLayout, 5, 1, 1, 1)
        self.tabWidget.addTab(self.gridTab, _fromUtf8(""))
        self.baseTab = QtGui.QWidget()
        self.baseTab.setObjectName(_fromUtf8("baseTab"))
        self.gridLayout = QtGui.QGridLayout(self.baseTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.basePointsNameEdit = QtGui.QLineEdit(self.baseTab)
        self.basePointsNameEdit.setObjectName(_fromUtf8("basePointsNameEdit"))
        self.gridLayout.addWidget(self.basePointsNameEdit, 2, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 99, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        self.baseLinesNameEdit = QtGui.QLineEdit(self.baseTab)
        self.baseLinesNameEdit.setObjectName(_fromUtf8("baseLinesNameEdit"))
        self.gridLayout.addWidget(self.baseLinesNameEdit, 3, 1, 1, 2)
        self.baseLinesNameLabel = QtGui.QLabel(self.baseTab)
        self.baseLinesNameLabel.setObjectName(_fromUtf8("baseLinesNameLabel"))
        self.gridLayout.addWidget(self.baseLinesNameLabel, 3, 0, 1, 1)
        self.baseGroupNameLabel = QtGui.QLabel(self.baseTab)
        self.baseGroupNameLabel.setObjectName(_fromUtf8("baseGroupNameLabel"))
        self.gridLayout.addWidget(self.baseGroupNameLabel, 1, 0, 1, 1)
        self.basePointsNameLabel = QtGui.QLabel(self.baseTab)
        self.basePointsNameLabel.setObjectName(_fromUtf8("basePointsNameLabel"))
        self.gridLayout.addWidget(self.basePointsNameLabel, 2, 0, 1, 1)
        self.basePolygonsNameEdit = QtGui.QLineEdit(self.baseTab)
        self.basePolygonsNameEdit.setObjectName(_fromUtf8("basePolygonsNameEdit"))
        self.gridLayout.addWidget(self.basePolygonsNameEdit, 4, 1, 1, 2)
        self.basePolygonsNameLabel = QtGui.QLabel(self.baseTab)
        self.basePolygonsNameLabel.setObjectName(_fromUtf8("basePolygonsNameLabel"))
        self.gridLayout.addWidget(self.basePolygonsNameLabel, 4, 0, 1, 1)
        self.baseGroupNameEdit = QtGui.QLineEdit(self.baseTab)
        self.baseGroupNameEdit.setObjectName(_fromUtf8("baseGroupNameEdit"))
        self.gridLayout.addWidget(self.baseGroupNameEdit, 1, 1, 1, 2)
        self.baseFolderLabel = QtGui.QLabel(self.baseTab)
        self.baseFolderLabel.setObjectName(_fromUtf8("baseFolderLabel"))
        self.gridLayout.addWidget(self.baseFolderLabel, 5, 0, 1, 1)
        self.baseFolderLayout = QtGui.QHBoxLayout()
        self.baseFolderLayout.setObjectName(_fromUtf8("baseFolderLayout"))
        self.baseFolderCheck = QtGui.QCheckBox(self.baseTab)
        self.baseFolderCheck.setText(_fromUtf8(""))
        self.baseFolderCheck.setObjectName(_fromUtf8("baseFolderCheck"))
        self.baseFolderLayout.addWidget(self.baseFolderCheck)
        self.baseFolderEdit = QtGui.QLineEdit(self.baseTab)
        self.baseFolderEdit.setEnabled(False)
        self.baseFolderEdit.setObjectName(_fromUtf8("baseFolderEdit"))
        self.baseFolderLayout.addWidget(self.baseFolderEdit)
        self.baseFolderButton = QtGui.QPushButton(self.baseTab)
        self.baseFolderButton.setEnabled(False)
        self.baseFolderButton.setIcon(icon)
        self.baseFolderButton.setObjectName(_fromUtf8("baseFolderButton"))
        self.baseFolderLayout.addWidget(self.baseFolderButton)
        self.gridLayout.addLayout(self.baseFolderLayout, 5, 1, 1, 2)
        self.tabWidget.addTab(self.baseTab, _fromUtf8(""))
        self.planTab = QtGui.QWidget()
        self.planTab.setObjectName(_fromUtf8("planTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.planTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.planPointsNameEdit = QtGui.QLineEdit(self.planTab)
        self.planPointsNameEdit.setObjectName(_fromUtf8("planPointsNameEdit"))
        self.gridLayout_6.addWidget(self.planPointsNameEdit, 4, 1, 1, 1)
        self.planPolygonsNameLabel = QtGui.QLabel(self.planTab)
        self.planPolygonsNameLabel.setObjectName(_fromUtf8("planPolygonsNameLabel"))
        self.gridLayout_6.addWidget(self.planPolygonsNameLabel, 6, 0, 1, 1)
        self.planBufferGroupNameEdit = QtGui.QLineEdit(self.planTab)
        self.planBufferGroupNameEdit.setObjectName(_fromUtf8("planBufferGroupNameEdit"))
        self.gridLayout_6.addWidget(self.planBufferGroupNameEdit, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 12, 1, 1, 1)
        self.planLinesNameEdit = QtGui.QLineEdit(self.planTab)
        self.planLinesNameEdit.setObjectName(_fromUtf8("planLinesNameEdit"))
        self.gridLayout_6.addWidget(self.planLinesNameEdit, 5, 1, 1, 1)
        self.planPointNameLabel = QtGui.QLabel(self.planTab)
        self.planPointNameLabel.setObjectName(_fromUtf8("planPointNameLabel"))
        self.gridLayout_6.addWidget(self.planPointNameLabel, 4, 0, 1, 1)
        self.planBufferGroupNameLabel = QtGui.QLabel(self.planTab)
        self.planBufferGroupNameLabel.setObjectName(_fromUtf8("planBufferGroupNameLabel"))
        self.gridLayout_6.addWidget(self.planBufferGroupNameLabel, 3, 0, 1, 1)
        self.planDataGroupNameLabel = QtGui.QLabel(self.planTab)
        self.planDataGroupNameLabel.setObjectName(_fromUtf8("planDataGroupNameLabel"))
        self.gridLayout_6.addWidget(self.planDataGroupNameLabel, 1, 0, 1, 1)
        self.planPolygonsNameEdit = QtGui.QLineEdit(self.planTab)
        self.planPolygonsNameEdit.setObjectName(_fromUtf8("planPolygonsNameEdit"))
        self.gridLayout_6.addWidget(self.planPolygonsNameEdit, 6, 1, 1, 1)
        self.planLinesNameLabel = QtGui.QLabel(self.planTab)
        self.planLinesNameLabel.setObjectName(_fromUtf8("planLinesNameLabel"))
        self.gridLayout_6.addWidget(self.planLinesNameLabel, 5, 0, 1, 1)
        self.planDataGroupNameEdit = QtGui.QLineEdit(self.planTab)
        self.planDataGroupNameEdit.setObjectName(_fromUtf8("planDataGroupNameEdit"))
        self.gridLayout_6.addWidget(self.planDataGroupNameEdit, 1, 1, 1, 1)
        self.planVectorFolderLabel = QtGui.QLabel(self.planTab)
        self.planVectorFolderLabel.setObjectName(_fromUtf8("planVectorFolderLabel"))
        self.gridLayout_6.addWidget(self.planVectorFolderLabel, 7, 0, 1, 1)
        self.planDataFolderLayout = QtGui.QHBoxLayout()
        self.planDataFolderLayout.setObjectName(_fromUtf8("planDataFolderLayout"))
        self.planDataFolderCheck = QtGui.QCheckBox(self.planTab)
        self.planDataFolderCheck.setText(_fromUtf8(""))
        self.planDataFolderCheck.setObjectName(_fromUtf8("planDataFolderCheck"))
        self.planDataFolderLayout.addWidget(self.planDataFolderCheck)
        self.planDataFolderEdit = QtGui.QLineEdit(self.planTab)
        self.planDataFolderEdit.setEnabled(False)
        self.planDataFolderEdit.setObjectName(_fromUtf8("planDataFolderEdit"))
        self.planDataFolderLayout.addWidget(self.planDataFolderEdit)
        self.planDataFolderButton = QtGui.QPushButton(self.planTab)
        self.planDataFolderButton.setEnabled(False)
        self.planDataFolderButton.setIcon(icon)
        self.planDataFolderButton.setObjectName(_fromUtf8("planDataFolderButton"))
        self.planDataFolderLayout.addWidget(self.planDataFolderButton)
        self.gridLayout_6.addLayout(self.planDataFolderLayout, 7, 1, 1, 1)
        self.tabWidget.addTab(self.planTab, _fromUtf8(""))
        self.drawingsTab = QtGui.QWidget()
        self.drawingsTab.setObjectName(_fromUtf8("drawingsTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.drawingsTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.drawingTransparencySpin = QtGui.QSpinBox(self.drawingsTab)
        self.drawingTransparencySpin.setMaximum(100)
        self.drawingTransparencySpin.setProperty("value", 50)
        self.drawingTransparencySpin.setObjectName(_fromUtf8("drawingTransparencySpin"))
        self.horizontalLayout_4.addWidget(self.drawingTransparencySpin)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 2, 1, 1)
        self.contextDrawingFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.contextDrawingFolderLabel.setObjectName(_fromUtf8("contextDrawingFolderLabel"))
        self.gridLayout_2.addWidget(self.contextDrawingFolderLabel, 3, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 46, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 5, 2, 1, 1)
        self.drawingTransparencyLabel = QtGui.QLabel(self.drawingsTab)
        self.drawingTransparencyLabel.setObjectName(_fromUtf8("drawingTransparencyLabel"))
        self.gridLayout_2.addWidget(self.drawingTransparencyLabel, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.planDrawingFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.planDrawingFolderCheck.setText(_fromUtf8(""))
        self.planDrawingFolderCheck.setObjectName(_fromUtf8("planDrawingFolderCheck"))
        self.horizontalLayout_3.addWidget(self.planDrawingFolderCheck)
        self.planDrawingFolderEdit = QtGui.QLineEdit(self.drawingsTab)
        self.planDrawingFolderEdit.setEnabled(False)
        self.planDrawingFolderEdit.setObjectName(_fromUtf8("planDrawingFolderEdit"))
        self.horizontalLayout_3.addWidget(self.planDrawingFolderEdit)
        self.planDrawingFolderButton = QtGui.QPushButton(self.drawingsTab)
        self.planDrawingFolderButton.setEnabled(False)
        self.planDrawingFolderButton.setIcon(icon)
        self.planDrawingFolderButton.setObjectName(_fromUtf8("planDrawingFolderButton"))
        self.horizontalLayout_3.addWidget(self.planDrawingFolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 2, 1, 1)
        self.georefFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.georefFolderLabel.setObjectName(_fromUtf8("georefFolderLabel"))
        self.gridLayout_2.addWidget(self.georefFolderLabel, 2, 0, 1, 1)
        self.planDrawingFolderLabel = QtGui.QLabel(self.drawingsTab)
        self.planDrawingFolderLabel.setObjectName(_fromUtf8("planDrawingFolderLabel"))
        self.gridLayout_2.addWidget(self.planDrawingFolderLabel, 4, 0, 1, 2)
        self.georefFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.georefFolderCheck.setText(_fromUtf8(""))
        self.georefFolderCheck.setChecked(True)
        self.georefFolderCheck.setObjectName(_fromUtf8("georefFolderCheck"))
        self.gridLayout_2.addWidget(self.georefFolderCheck, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.contextDrawingFolderCheck = QtGui.QCheckBox(self.drawingsTab)
        self.contextDrawingFolderCheck.setText(_fromUtf8(""))
        self.contextDrawingFolderCheck.setObjectName(_fromUtf8("contextDrawingFolderCheck"))
        self.horizontalLayout_2.addWidget(self.contextDrawingFolderCheck)
        self.contextDrawingFolderEdit = QtGui.QLineEdit(self.drawingsTab)
        self.contextDrawingFolderEdit.setEnabled(False)
        self.contextDrawingFolderEdit.setObjectName(_fromUtf8("contextDrawingFolderEdit"))
        self.horizontalLayout_2.addWidget(self.contextDrawingFolderEdit)
        self.contextDrawingFolderButton = QtGui.QPushButton(self.drawingsTab)
        self.contextDrawingFolderButton.setEnabled(False)
        self.contextDrawingFolderButton.setIcon(icon)
        self.contextDrawingFolderButton.setObjectName(_fromUtf8("contextDrawingFolderButton"))
        self.horizontalLayout_2.addWidget(self.contextDrawingFolderButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 2, 1, 1)
        self.drawingGroupNameLabel = QtGui.QLabel(self.drawingsTab)
        self.drawingGroupNameLabel.setObjectName(_fromUtf8("drawingGroupNameLabel"))
        self.gridLayout_2.addWidget(self.drawingGroupNameLabel, 0, 0, 1, 1)
        self.drawingGroupNameEdit = QtGui.QLineEdit(self.drawingsTab)
        self.drawingGroupNameEdit.setObjectName(_fromUtf8("drawingGroupNameEdit"))
        self.gridLayout_2.addWidget(self.drawingGroupNameEdit, 0, 2, 1, 1)
        self.tabWidget.addTab(self.drawingsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialogBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.projectFolderLabel.setBuddy(self.projectFolderEdit)
        self.siteCodeLabel.setBuddy(self.siteCodeEdit)
        self.multiSiteLabel.setBuddy(self.multiSiteCheck)
        self.customStylesLabel.setBuddy(self.styleFolderEdit)
        self.gridPolygonsNameLabel.setBuddy(self.gridPolygonsNameEdit)
        self.gridGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.gridLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.gridPointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.gridFolderLabel.setBuddy(self.gridFolderEdit)
        self.baseLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.baseGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.basePointsNameLabel.setBuddy(self.gridPointsNameEdit)
        self.baseFolderLabel.setBuddy(self.gridFolderEdit)
        self.planPolygonsNameLabel.setBuddy(self.gridPolygonsNameEdit)
        self.planPointNameLabel.setBuddy(self.gridPointsNameEdit)
        self.planDataGroupNameLabel.setBuddy(self.gridGroupNameEdit)
        self.planLinesNameLabel.setBuddy(self.gridLinesNameEdit)
        self.planVectorFolderLabel.setBuddy(self.gridFolderEdit)
        self.georefFolderLabel.setBuddy(self.georefFolderCheck)

        self.retranslateUi(SettingsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialogBase.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialogBase.reject)
        QtCore.QObject.connect(self.gridFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.gridFolderEdit.setEnabled)
        QtCore.QObject.connect(self.gridFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.gridFolderButton.setEnabled)
        QtCore.QObject.connect(self.baseFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.baseFolderEdit.setEnabled)
        QtCore.QObject.connect(self.baseFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.baseFolderButton.setEnabled)
        QtCore.QObject.connect(self.contextDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contextDrawingFolderButton.setEnabled)
        QtCore.QObject.connect(self.contextDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contextDrawingFolderEdit.setEnabled)
        QtCore.QObject.connect(self.planDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.planDrawingFolderButton.setEnabled)
        QtCore.QObject.connect(self.planDrawingFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.planDrawingFolderEdit.setEnabled)
        QtCore.QObject.connect(self.planDataFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.planDataFolderButton.setEnabled)
        QtCore.QObject.connect(self.planDataFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.planDataFolderEdit.setEnabled)
        QtCore.QObject.connect(self.styleFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.styleFolderButton.setEnabled)
        QtCore.QObject.connect(self.styleFolderCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.styleFolderEdit.setEnabled)
        QtCore.QObject.connect(self.useArkCheck, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.arkUrlEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogBase)
        SettingsDialogBase.setTabOrder(self.projectFolderEdit, self.projectFolderButton)
        SettingsDialogBase.setTabOrder(self.projectFolderButton, self.multiSiteCheck)
        SettingsDialogBase.setTabOrder(self.multiSiteCheck, self.siteCodeEdit)
        SettingsDialogBase.setTabOrder(self.siteCodeEdit, self.styleFolderCheck)
        SettingsDialogBase.setTabOrder(self.styleFolderCheck, self.styleFolderEdit)
        SettingsDialogBase.setTabOrder(self.styleFolderEdit, self.styleFolderButton)
        SettingsDialogBase.setTabOrder(self.styleFolderButton, self.buttonBox)
        SettingsDialogBase.setTabOrder(self.buttonBox, self.tabWidget)
        SettingsDialogBase.setTabOrder(self.tabWidget, self.gridLinesNameEdit)
        SettingsDialogBase.setTabOrder(self.gridLinesNameEdit, self.gridPolygonsNameEdit)
        SettingsDialogBase.setTabOrder(self.gridPolygonsNameEdit, self.gridGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.gridGroupNameEdit, self.gridPointsNameEdit)
        SettingsDialogBase.setTabOrder(self.gridPointsNameEdit, self.gridFolderEdit)
        SettingsDialogBase.setTabOrder(self.gridFolderEdit, self.gridFolderButton)
        SettingsDialogBase.setTabOrder(self.gridFolderButton, self.baseGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.baseGroupNameEdit, self.basePointsNameEdit)
        SettingsDialogBase.setTabOrder(self.basePointsNameEdit, self.baseFolderEdit)
        SettingsDialogBase.setTabOrder(self.baseFolderEdit, self.baseFolderButton)
        SettingsDialogBase.setTabOrder(self.baseFolderButton, self.baseLinesNameEdit)
        SettingsDialogBase.setTabOrder(self.baseLinesNameEdit, self.basePolygonsNameEdit)
        SettingsDialogBase.setTabOrder(self.basePolygonsNameEdit, self.planLinesNameEdit)
        SettingsDialogBase.setTabOrder(self.planLinesNameEdit, self.planPointsNameEdit)
        SettingsDialogBase.setTabOrder(self.planPointsNameEdit, self.planBufferGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.planBufferGroupNameEdit, self.planPolygonsNameEdit)
        SettingsDialogBase.setTabOrder(self.planPolygonsNameEdit, self.planDataGroupNameEdit)
        SettingsDialogBase.setTabOrder(self.planDataGroupNameEdit, self.planDataFolderEdit)
        SettingsDialogBase.setTabOrder(self.planDataFolderEdit, self.planDataFolderButton)
        SettingsDialogBase.setTabOrder(self.planDataFolderButton, self.gridFolderCheck)
        SettingsDialogBase.setTabOrder(self.gridFolderCheck, self.baseFolderCheck)
        SettingsDialogBase.setTabOrder(self.baseFolderCheck, self.contextDrawingFolderEdit)
        SettingsDialogBase.setTabOrder(self.contextDrawingFolderEdit, self.contextDrawingFolderButton)
        SettingsDialogBase.setTabOrder(self.contextDrawingFolderButton, self.drawingTransparencySpin)
        SettingsDialogBase.setTabOrder(self.drawingTransparencySpin, self.georefFolderCheck)
        SettingsDialogBase.setTabOrder(self.georefFolderCheck, self.contextDrawingFolderCheck)
        SettingsDialogBase.setTabOrder(self.contextDrawingFolderCheck, self.planDrawingFolderCheck)
        SettingsDialogBase.setTabOrder(self.planDrawingFolderCheck, self.planDrawingFolderEdit)
        SettingsDialogBase.setTabOrder(self.planDrawingFolderEdit, self.planDrawingFolderButton)
        SettingsDialogBase.setTabOrder(self.planDrawingFolderButton, self.planDataFolderCheck)
        SettingsDialogBase.setTabOrder(self.planDataFolderCheck, self.drawingGroupNameEdit)

    def retranslateUi(self, SettingsDialogBase):
        SettingsDialogBase.setWindowTitle(_translate("SettingsDialogBase", "Settings", None))
        self.useArkLabel.setText(_translate("SettingsDialogBase", "Use ARK DB:", None))
        self.projectFolderLabel.setText(_translate("SettingsDialogBase", "Project Folder:", None))
        self.siteCodeLabel.setText(_translate("SettingsDialogBase", "Default Site Code:", None))
        self.multiSiteLabel.setText(_translate("SettingsDialogBase", "Multi-site Project", None))
        self.customStylesLabel.setText(_translate("SettingsDialogBase", "Custom Styles Folder:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectTab), _translate("SettingsDialogBase", "Project", None))
        self.gridPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.gridGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.gridLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.gridPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.gridFolderLabel.setText(_translate("SettingsDialogBase", "Custom Data Folder:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gridTab), _translate("SettingsDialogBase", "Grid", None))
        self.baseLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.baseGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.basePointsNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.basePolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.baseFolderLabel.setText(_translate("SettingsDialogBase", "Custom Data Folder:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.baseTab), _translate("SettingsDialogBase", "Base", None))
        self.planPolygonsNameLabel.setText(_translate("SettingsDialogBase", "Polygons Base Name:", None))
        self.planPointNameLabel.setText(_translate("SettingsDialogBase", "Points Base Name:", None))
        self.planBufferGroupNameLabel.setText(_translate("SettingsDialogBase", "Buffer Group Name:", None))
        self.planDataGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.planLinesNameLabel.setText(_translate("SettingsDialogBase", "Lines Base Name:", None))
        self.planVectorFolderLabel.setText(_translate("SettingsDialogBase", "Custom Data Folder:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.planTab), _translate("SettingsDialogBase", "Plan", None))
        self.drawingTransparencySpin.setSuffix(_translate("SettingsDialogBase", "%", None))
        self.contextDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Context Drawings:", None))
        self.drawingTransparencyLabel.setText(_translate("SettingsDialogBase", "Image tranparency:", None))
        self.georefFolderLabel.setText(_translate("SettingsDialogBase", "Separate georef folder:", None))
        self.planDrawingFolderLabel.setText(_translate("SettingsDialogBase", "Plan Drawings:", None))
        self.georefFolderCheck.setToolTip(_translate("SettingsDialogBase", "Select if the raw and processed plans should be stored in separate folders.", None))
        self.drawingGroupNameLabel.setText(_translate("SettingsDialogBase", "Group Name:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.drawingsTab), _translate("SettingsDialogBase", "Drawings", None))

import resources_rc
